export const WEBSITE_TEMPLATE_TYPES = {

  WEBSITE_TEMPLATE_CREATE_LOADING: "WEBSITE_TEMPLATE_CREATE_LOADING",
  WEBSITE_TEMPLATE_CREATE_SUCCESS: "WEBSITE_TEMPLATE_CREATE_SUCCESS",
  WEBSITE_TEMPLATE_CREATE_ERROR: "WEBSITE_TEMPLATE_CREATE_ERROR",
  WEBSITE_TEMPLATE_CREATE_RESET: "WEBSITE_TEMPLATE_CREATE_RESET",

  WEBSITE_TEMPLATE_LOADING: "WEBSITE_TEMPLATE_LOADING",
  WEBSITE_TEMPLATE_SUCCESS: "WEBSITE_TEMPLATE_SUCCESS",
  WEBSITE_TEMPLATE_ERROR: "WEBSITE_TEMPLATE_ERROR",
  WEBSITE_TEMPLATE_RESET: "WEBSITE_TEMPLATE_RESET",

  WEBSITE_TEMPLATE_DOMAIN_LOADING: "WEBSITE_TEMPLATE_DOMAIN_LOADING",
  WEBSITE_TEMPLATE_DOMAIN_SUCCESS: "WEBSITE_TEMPLATE_DOMAIN_SUCCESS",
  WEBSITE_TEMPLATE_DOMAIN_ERROR: "WEBSITE_TEMPLATE_DOMAIN_ERROR",
  WEBSITE_TEMPLATE_DOMAIN_RESET: "WEBSITE_TEMPLATE_DOMAIN_RESET",


  WEBSITE_TEMPLATE_LIST_LOADING: "WEBSITE_TEMPLATE_LIST_LOADING",
  WEBSITE_TEMPLATE_LIST_SUCCESS: "WEBSITE_TEMPLATE_LIST_SUCCESS",
  WEBSITE_TEMPLATE_LIST_ERROR: "WEBSITE_TEMPLATE_LIST_ERROR",
  WEBSITE_TEMPLATE_LIST_RESET: "WEBSITE_TEMPLATE_LIST_RESET",

  WEBSITE_TEMPLATE_EDIT_SETTINGS_LOADING: "WEBSITE_TEMPLATE_EDIT_SETTINGS_LOADING",
  WEBSITE_TEMPLATE_EDIT_SETTINGS_SUCCESS: "WEBSITE_TEMPLATE_EDIT_SETTINGS_SUCCESS",
  WEBSITE_TEMPLATE_EDIT_SETTINGS_ERROR: "WEBSITE_TEMPLATE_EDIT_SETTINGS_ERROR",
  WEBSITE_TEMPLATE_EDIT_SETTINGS_RESET: "WEBSITE_TEMPLATE_EDIT_SETTINGS_RESET",

  WEBSITE_TEMPLATE_EDIT_THEME_LOADING: "WEBSITE_TEMPLATE_EDIT_THEME_LOADING",
  WEBSITE_TEMPLATE_EDIT_THEME_SUCCESS: "WEBSITE_TEMPLATE_EDIT_THEME_SUCCESS",
  WEBSITE_TEMPLATE_EDIT_THEME_ERROR: "WEBSITE_TEMPLATE_EDIT_THEME_ERROR",
  WEBSITE_TEMPLATE_EDIT_THEME_RESET: "WEBSITE_TEMPLATE_EDIT_THEME_RESET",


  WEBSITE_TEMPLATE_CREATE_USER_THEME_LOADING: "WEBSITE_TEMPLATE_CREATE_USER_THEME_LOADING",
  WEBSITE_TEMPLATE_CREATE_USER_THEME_SUCCESS: "WEBSITE_TEMPLATE_CREATE_USER_THEME_SUCCESS",
  WEBSITE_TEMPLATE_CREATE_USER_THEME_ERROR: "WEBSITE_TEMPLATE_CREATE_USER_THEME_ERROR",
  WEBSITE_TEMPLATE_CREATE_USER_THEME_RESET: "WEBSITE_TEMPLATE_CREATE_USER_THEME_RESET",

  WEBSITE_TEMPLATE_SELECTED_THEME_LOADING: "WEBSITE_TEMPLATE_SELECTED_THEME_LOADING",
  WEBSITE_TEMPLATE_SELECTED_THEME_SUCCESS: "WEBSITE_TEMPLATE_SELECTED_THEME_SUCCESS",
  WEBSITE_TEMPLATE_SELECTED_THEME_ERROR: "WEBSITE_TEMPLATE_SELECTED_THEME_ERROR",
  WEBSITE_TEMPLATE_SELECTED_THEME_RESET: "WEBSITE_TEMPLATE_SELECTED_THEME_RESET",

  DELETE_USER_TEMPLATE_LOADING: "DELETE_USER_TEMPLATE_LOADING",
  DELETE_USER_TEMPLATE_SUCCESS: "DELETE_USER_TEMPLATE_SUCCESS",
  DELETE_USER_TEMPLATE_RESET: "DELETE_USER_TEMPLATE_RESET",

  WEBSITE_TEMPLATE_EDIT_PAGES_LOADING: "WEBSITE_TEMPLATE_EDIT_PAGES_LOADING",
  WEBSITE_TEMPLATE_EDIT_PAGES_SUCCESS: "WEBSITE_TEMPLATE_EDIT_PAGES_SUCCESS",
  WEBSITE_TEMPLATE_EDIT_PAGES_ERROR: "WEBSITE_TEMPLATE_EDIT_PAGES_ERROR",
  WEBSITE_TEMPLATE_EDIT_PAGES_RESET: "WEBSITE_TEMPLATE_EDIT_PAGES_RESET",

  WEBSITE_TEMPLATE_EDIT_LOADING: "WEBSITE_TEMPLATE_EDIT_LOADING",
  WEBSITE_TEMPLATE_EDIT_SUCCESS: "WEBSITE_TEMPLATE_EDIT_SUCCESS",
  WEBSITE_TEMPLATE_EDIT_ERROR: "WEBSITE_TEMPLATE_EDIT_ERROR",
  WEBSITE_TEMPLATE_EDIT_RESET: "WEBSITE_TEMPLATE_EDIT_RESET",

  WEBSITE_TEMPLATE_GET_USER_TEMPLATES_LOADING: "WEBSITE_TEMPLATE_GET_USER_TEMPLATES_LOADING",
  WEBSITE_TEMPLATE_GET_USER_TEMPLATES_SUCCESS: "WEBSITE_TEMPLATE_GET_USER_TEMPLATES_SUCCESS",
  WEBSITE_TEMPLATE_GET_USER_TEMPLATES_ERROR: "WEBSITE_TEMPLATE_GET_USER_TEMPLATES_ERROR",
  WEBSITE_TEMPLATE_GET_USER_TEMPLATES_RESET: "WEBSITE_TEMPLATE_GET_USER_TEMPLATES_RESET",


  ACTIVATE_WEBSITE_TEMPLATE_LOADING: "ACTIVATE_WEBSITE_TEMPLATE_LOADING",
  ACTIVATE_WEBSITE_TEMPLATE_SUCCESS: "ACTIVATE_WEBSITE_TEMPLATE_SUCCESS",
  ACTIVATE_WEBSITE_TEMPLATE_ERROR: "ACTIVATE_WEBSITE_TEMPLATE_ERROR",
  ACTIVATE_WEBSITE_TEMPLATE_RESET: "ACTIVATE_WEBSITE_TEMPLATE_RESET",

  UPDATE_DYNAMIC_WEBSITE_TEMPLATE: "UPDATE_DYNAMIC_WEBSITE_TEMPLATE",
  UPDATE_DYNAMIC_SETTINGS_WEBSITE_TEMPLATE: "UPDATE_DYNAMIC_SETTINGS_WEBSITE_TEMPLATE",
  SELECT_ROUTE_PREVIEW: "SELECT_ROUTE_PREVIEW",

  WEBSITE_TEMPLATE_DOMAIN_CHECK: "WEBSITE_TEMPLATE_DOMAIN_CHECK",

  GET_GALLERY_ALBUM_LOADING: "GET_GALLERY_ALBUM_LOADING",
  GET_GALLERY_ALBUM_SUCCESS: "GET_GALLERY_ALBUM_SUCCESS",
  GET_GALLERY_ALBUM_RESET: "GET_GALLERY_ALBUM_RESET",

  GET_GALLERY_LOADING: "GET_GALLERY_LOADING",
  GET_GALLERY_SUCCESS: "GET_GALLERY_SUCCESS",
  GET_GALLERY_RESET: "GET_GALLERY_RESET",
  GET_VALUE_PUSH: "GET_VALUE_PUSH",
  GET_VALUE_RESET: "GET_VALUE_RESET",

}