export const MENUHEADERTYPES = {
  GET_MENU_HEADER_LIST_LOADING: "GET_MENU_HEADER_LIST_LOADING",
  GET_MENU_HEADER_LIST_LOADED: "GET_MENU_HEADER_LIST_LOADED",
  GET_MENU_HEADER_LIST_ERROR: "GET_MENU_HEADER_LIST_ERROR",
  GET_MENU_HEADER_LIST_RESET: "GET_MENU_HEADER_LIST_RESET",

  UPDATE_MENU_HEADER_LOADING: "UPDATE_MENU_HEADER_LOADING",
  UPDATE_MENU_HEADER_LOADED: "UPDATE_MENU_HEADER_LOADED",
  UPDATE_MENU_HEADER_ERROR: "UPDATE_MENU_HEADER_ERROR",
  UPDATE_MENU_HEADER_RESET: "UPDATE_MENU_HEADER_RESET",

  DYNAMIC_MENU_HEADERS_LOADING: "DYNAMIC_MENU_HEADERS_LOADING",
  DYNAMIC_MENU_HEADERS: "DYNAMIC_MENU_HEADERS"
}