export const VacancyActionTypes = {
    VACANCY_CREATING: "VACANCY_CREATING",
    VACANCY_CREATING_SAVE: "VACANCY_CREATING_SAVE",
    VACANCY_CREATED: "VACANCY_CREATED",
    VACANCY_CREATE_ERROR: "VACANCY_CREATE_ERROR",
    VACANCY_CREATE_RESET: "VACANCY_CREATE_RESET",

    VACANCY_LIST_LOADING: "VACANCY_LIST_LOADING",
    VACANCY_LIST_LOADED: "VACANCY_LIST_LOADED",
    VACANCY_LIST_ERROR: "VACANCY_LIST_ERROR",
    VACANCY_LIST_RESET: "VACANCY_LIST_RESET",

    APPLICANT_LIST_LOADING: "APPLICANT_LIST_LOADING",
    APPLICANT_LIST_LOADED: "APPLICANT_LIST_LOADED",
    APPLICANT_LIST_ERROR: "APPLICANT_LIST_ERROR",
    APPLICANT_LIST_RESET: "APPLICANT_LIST_RESET",

    VACANCY_LIST_SELECTION_LOADING: "VACANCY_LIST_SELECTION_LOADING",
    VACANCY_LIST_SELECTION_LOADED: "VACANCY_LIST_SELECTION_LOADED",
    VACANCY_LIST_SELECTION_ERROR: "VACANCY_LIST_SELECTION_ERROR",
    VACANCY_LIST_SELECTION_RESET: "VACANCY_LIST_SELECTION_RESET",


    VACANCY_UPDATING: "VACANCY_UPDATING",
    VACANCY_UPDATED: "VACANCY_UPDATED",
    VACANCY_UPDATE_ERROR: "VACANCY_UPDATE_ERROR",
    VACANCY_UPDATE_RESET: "VACANCY_UPDATE_RESET",

    VACANCY_SELECTION_UPDATING: "VACANCY_SELECTION_UPDATING",
    VACANCY_SELECTION_UPDATED: "VACANCY_SELECTION_UPDATED",
    VACANCY_UPDATE_SELECTION_ERROR: "VACANCY_UPDATE_SELECTION_ERROR",

    VACANCY_DELETE: "VACANCY_DELETE",
    VACANCY_DELETE_LOADING: "VACANCY_DELETE_LOADING",
    VACANCY_DELETE_RESET: "VACANCY_DELETE_RESET",

    UPDATE_LIST_STATUS: "UPDATE_LIST_STATUS",

    APPLICANT_UPDATE_LIST_STATUS: "APPLICANT_UPDATE_LIST_STATUS",

    APPLICANT_UPDATE_EMAIL_NOTIFY: "APPLICANT_UPDATE_EMAIL_NOTIFY",

    VACANCY_CANCEL: "VACANCY_CANCEL",

    VACANCY_DETAIL_LOADING: "VACANCY_DETAIL_LOADING",
    VACANCY_DETAIL_LOADED: "VACANCY_DETAIL_LOADED",
    VACANCY_DETAIL_LOADING_ERROR: "VACANCY_DETAIL_LOADING_ERROR",
    VACANCY_DETAIL_LOADING_RESET: "VACANCY_DETAIL_LOADING_RESET",


    VACANCY_TITLE_LOADING: "VACANCY_TITLE_LOADING",
    VACANCY_TITLE_LOADED: " VACANCY_TITLE_LOADED",
    VACANCY_TITLE_LOADING_ERROR: " VACANCY_TITLE_LOADING_ERROR",
    VACANCY_TITLE_LOADING_RESET: " VACANCY_TITLE_LOADING_RESET",

}