export const studentHolidaysActionTypes = {
  STUDENT_HOLIDAYS_LIST_LOADING: "GET_STUDENT_HOLIDAY_LIST_LOADING",
  STUDENT_HOLIDAYS_LIST_LOADED: 'GET_STUDENT_HOLIDAY_LIST_LOADED',
  STUDENT_HOLIDAYS_LIST_ERROR: "GET_STUDENT_HOLIDAY_LIST_ERROR",
  STUDENT_HOLIDAYS_LIST_RESET: "GET_STUDENT_HOLIDAY_LIST_RESET",

  STUDENT_HOLIDAYS_LIST_SORTBY_LOADING: "STUDENT_HOLIDAY_LIST_SORTBY_LOADING",
  STUDENT_HOLIDAYS_LIST_SORTBY_LOADED: "STUDENT_HOLIDAY_LIST_SORTBY_LOADED",
  STUDENT_HOLIDAYS_LIST_SORTBY_ERROR: "STUDENT_HOLIDAY_LIST_SORTBY_ERROR",
  STUDENT_HOLIDAYS_LIST_SORTBY_RESET: "STUDENT_HOLIDAY_LIST_SORTBY_RESET",

  STUDENT_HOLIDAYS_LIST_BY_YEAR_LOADING: "STUDENT_HOLIDAYS_LIST_YEAR_LOADING",
  STUDENT_HOLIDAYS_LIST_BY_YEAR_LOADED: "STUDENT_HOLIDAYS_LIST_YEAR_LOADING",
  STUDENT_HOLIDAYS_LIST_BY_YEAR_ERROR: "STUDENT_HOLIDAYS_LIST_YEAR_ERROR",
  STUDENT_HOLIDAYS_LIST_BY_YEAR_RESET: "STUDENT_HOLIDAYS_LIST_YEAR_RESET",

  GET_SINGLE_HOLIDAY_LOADING: "GET_SINGLE_HOLIDAY_LOADING",
  GET_SINGLE_HOLIDAY_LOADED: "GET_SINGLE_HOLIDAY_LOADED",
  GET_SINGLE_HOLIDAY_ERROR: "GET_SINGLE_HOLIDAY_ERROR",
  GET_SINGLE_HOLIDAY_RESET: "GET_SINGLE_HOLIDAY_RESET",

}