export const EDNEEDYOUTUBETYPES = {
  GETALLYOUTUBEVIDEOS: "GETALLYOUTUBEVIDEOS",
  GETALLYOUTUBEVIDEOSLOADING: "GETALLYOUTUBEVIDEOSLOADING",
  SORTYOUTUBEVIDEOS: "SORTYOUTUBEVIDEOS",


  GET_VIDEOS_LOADING: 'GET_VIDEOS_LOADING',
  GET_VIDEOS_LOADED: 'GET_VIDEOS_LOADED',
  GET_VIDEOS_ERROR: 'GET_VIDEOS_ERROR',

}