export const INS_FACULTY_ACTION_TYPES = {
  INS_FAC_LIST_LOADING: "INS_FAC_LIST_LOADING",
  INS_FAC_LIST_LOADED: "INS_FAC_LIST_LOADED",
  INS_FAC_LIST_LOADING_ERROR: "INS_FAC_LIST_LOADING_ERROR",
  INS_FAC_MORELIST_LOADING: "INS_FAC_MORELIST_LOADING",
  INS_FAC_MORELIST_LOADED: "INS_FAC_MORELIST_LOADED",
  INS_FAC_MORELIST_LOADING_ERROR: "INS_FAC_MORELIST_LOADING_ERROR",
  INS_FAC_LIST_RESET: "INS_FAC_LIST_RESET",
}