export const TeacherAttendanceActionTypes = {
    POST_TEACHER_ATTENDANCE_LOADING:"POST_TEACHER_ATTENDANCE_LOADING",
    POST_TEACHER_ATTENDANCE_LOADED:"POST_TEACHER_ATTENDANCE_LOADED",
    POST_TEACHER_ATTENDANCE_RESET:"POST_TEACHER_ATTENDANCE_RESET",
    POST_TEACHER_ATTENDANCE_ERROR:"POST_TEACHER_ATTENDANCE_ERROR",

    GET_TEACHER_STUDENT_ATTENDANCE_LIST:"GET_TEACHER_STUDENT_ATTENDANCE_LIST",
    GET_TEACHER_STUDENT_ATTENDANCE_LIST_LOADING:"GET_TEACHER_STUDENT_ATTENDANCE_LIST_LOADING",
    GET_TEACHER_STUDENT_ATTENDANCE_LIST_RESET:"GET_TEACHER_STUDENT_ATTENDANCE_LIST_RESET",

    EDIT_TEACHER_ATTENDANCE_LOADING:"EDIT_TEACHER_ATTENDANCE_LOADING",
    EDIT_TEACHER_ATTENDANCE_LOADED:"EDIT_TEACHER_ATTENDANCE_LOADED",
    SET_EDIT_ATTENDANCE_STATIC_DATA:"SET_EDIT_ATTENDANCE_STATIC_DATA",
    
    GET_SINGLE_ATTENDANCE_INFO_LOADING:"GET_SINGLE_ATTENDANCE_INFO_LOADING",
    GET_SINGLE_ATTENDANCE_INFO_LOADED:"GET_SINGLE_ATTENDANCE_INFO_LOADED",
    GET_SINGLE_ATTENDANCE_INFO_RESET:"GET_SINGLE_ATTENDANCE_INFO_RESET",

    SEARCH_STUDENT_ATTENDANCE:"SEARCH_STUDENT_ATTENDANCE",

    GET_SINGLE_STUDENT_PERIOD_DATA_LOADED:"GET_SINGLE_STUDENT_PERIOD_DATA_LOADED",
    GET_SINGLE_STUDENT_PERIOD_DATA_LOADING:"GET_SINGLE_STUDENT_PERIOD_DATA_LOADING",
    GET_SINGLE_STUDENT_PERIOD_DATA_RESET:"GET_SINGLE_STUDENT_PERIOD_DATA_RESET",

    GET_TEACHER_LEAVE_REQUESTS_LOADING:"GET_TEACHER_LEAVE_REQUESTS_LOADING",
    GET_TEACHER_LEAVE_REQUESTS:"GET_TEACHER_LEAVE_REQUESTS",
    GET_TEACHER_LEAVE_REQUESTS_RESET:"GET_TEACHER_LEAVE_REQUESTS_RESET",

    SEARCH_STUDENT_REQUEST_LIST:"SEARCH_STUDENT_REQUEST_LIST",

    ACCEPT_LEAVE_LEQUEST_LOADING:"ACCEPT_LEAVE_LEQUEST_LOADING",
    ACCEPT_LEAVE_LEQUEST:"ACCEPT_LEAVE_LEQUEST",
    ACCEPT_LEAVE_LEQUEST_RESET:"ACCEPT_LEAVE_LEQUEST_RESET",

    GET_SINGLE_LEAVE_REQUEST:"GET_SINGLE_LEAVE_REQUEST",
    GET_SINGLE_LEAVE_REQUEST_LOADING:"GET_SINGLE_LEAVE_REQUEST_LOADING",
    GET_SINGLE_LEAVE_REQUEST_RESET:"GET_SINGLE_LEAVE_REQUEST_RESET",
    
    DELETE_ATTENDANCE:'DELETE_ATTENDANCE',
    DELETE_ATTENDANCE_RESET:"DELETE_ATTENDANCE_RESET"
}