export const FEE_MANAGEMENT_TYPE = {
  // kunal code

  INSTITUTE_COURSE_SCROLLING_LOADED: "INSTITUTE_COURSE_SCROLLING_LOADED",
  INSTITUTE_COURSE_SEARCHING_LOADED: "INSTITUTE_COURSE_SEARCHING_LOADED",


  INSTITUTE_FEE_STRCTURE_LIST_LOADING: "INSTITUTE_FEE_STRCTURE_LIST_LOADING",
  INSTITUTE_FEE_STRCTURE_LIST_LOADED: "INSTITUTE_FEE_STRCTURE_LIST_LOADED",

  INSTITUTE_COURSE_LIST_LOADING: "INSTITUTE_COURSE_LIST_LOADING",
  INSTITUTE_COURSE_LIST_LOADED: "INSTITUTE_COURSE_LIST_LOADED",
  INSTITUTE_COURSE_LIST_SCROLLING: "INSTITUTE_COURSE_LIST_SCROLLING",

  STUDENT_FEE_EDIT_LOADING: "STUDENT_FEE_EDIT_LOADING",
  STUDENT_FEE_EDIT_LOADED: "STUDENT_FEE_EDIT_LOADED",
  STUDENT_FEE_EDIT_RESET: "STUDENT_FEE_EDIT_RESET",


  STUDENT_COLLECT_FEE_GET_LOADING: "STUDENT_FEE_GET_LOADING",
  STUDENT_COLLECT_FEE_GET_LOADED: "STUDENT_FEE_GET_LOADED",

  STUDENT_COLLECT_FEE_POST_LOADING: "STUDENT_FEE_POST_LOADING",
  STUDENT_COLLECT_FEE_POST_LOADED: "STUDENT_FEE_POST_LOADED",
  STUDENT_COLLECT_FEE_POST_RESET: "STUDENT_COLLECT_FEE_POST_RESET",

  FEE_STRUCTURE_IS_EXIST_LOADING: "FEE_STRUCTURE_IS_EXIST_LOADING",
  FEE_STRUCTURE_IS_EXIST_LOADED: "FEE_STRUCTURE_IS_EXIST_LOADED",
  FEE_STRUCTURE_IS_EXIST_RESET: "FEE_STRUCTURE_IS_EXIST_RESET",

  RAZORPAY_ACCOUNT_CREATE_LOADING: "RAZORPAY_ACCOUNT_CREATE_LOADING",
  RAZORPAY_ACCOUNT_CREATE_LOADED: "RAZORPAY_ACCOUNT_CREATE_LOADED",

  FEE_MANAGEMENT_LMS_UPDATE_FEE: "FEE_MANAGEMENT_LMS_UPDATE_FEE",

  FEE_MANAGEMENT_POST_EXCEL_SHEET_COLUMNS_LOADING: "FEE_MANAGEMENT_POST_EXCEL_SHEET_COLUMNS_LOADING",
  FEE_MANAGEMENT_POST_EXCEL_SHEET_COLUMNS_SUCCESS: "FEE_MANAGEMENT_POST_EXCEL_SHEET_COLUMNS_SUCCESS",
  FEE_MANAGEMENT_POST_EXCEL_SHEET_COLUMNS_RESET: "FEE_MANAGEMENT_POST_EXCEL_SHEET_COLUMNS_RESET"
};
