export const VIEWSTUDENTCLASSROOM = {
    GET_COURSE_CLASSROOM_INFO_LOADING: "GET_COURSE_CLASSROOM_INFO_LOADING",
    GET_COURSE_CLASSROOM_INFO_LOADED: "GET_COURSE_CLASSROOM_INFO_LOADED",



    GET_ASSIGNMENT_LIST_STUDENT_CLASSROOM_LOADING: "GET_ASSIGNMENT_LIST_STUDENT_CLASSROOM_LOADING",
    GET_ASSIGNMENT_LIST_STUDENT_CLASSROOM_LOADED: "GET_ASSIGNMENT_LIST_STUDENT_CLASSROOM_LOADED",


    GET_TEACHER_LIST_STUDENT_CLASSROOM_LOADING: "GET_TEACHER_LIST_STUDENT_CLASSROOM_LOADING",
    GET_TEACHER_LIST_STUDENT_CLASSROOM_LOADED: "GET_TEACHER_LIST_STUDENT_CLASSROOM_LOADED",


    GET_SUBJECT_ONLINE_CLASS_LIST_LOADING: "GET_SUBJECT_ONLINE_CLASS_LIST_LOADING",
    GET_SUBJECT_ONLINE_CLASS_LIST_LOADED: "GET_SUBJECT_ONLINE_CLASS_LIST_LOADED",


    GET_SUBJECT_COURSES_LOADING: "GET_SUBJECT_COURSES_LIST_LOADING",
    GET_SUBJECT_COURSES_LOADED: "GET_SUBJECT_COURSES_LIST_LOADED",

    SEARCH_SORTBY_STUDENT_COURSE_LIST: "SEARCH_SORTBY_STUDENT_COURSE_LIST",

    SEARCH_SORT_BY_STUDENT_ONLINE_CLASSES_LIST: "SEARCH_SORT_BY_STUDENT_ONLINE_CLASSES_LIST",
    SEARCH_SORT_BY_STUDENT_ASSIGNMENTS_LIST: "SEARCH_SORT_BY_STUDENT_ASSIGNMENTS_LIST",

    SEARCH_SORT_BY_STUDENT_TEACHER_LIST: "SEARCH_SORT_BY_STUDENT_TEACHER_LIST",

    CREATED_BY_FILTER_STUDENT_COURSES_LIST: "CREATED_BY_FILTER_STUDENT_COURSES_LIST"
}