export const StudentCourseActionTypes = {
  GET_STUDENT_COURSES_LIST_LOADING:"GET_STUDENT_COURSES_LIST_LOADING",
  GET_STUDENT_COURSES_LIST_LOADED:"GET_STUDENT_COURSES_LIST_LOADED",
  GET_STUDENT_COURSES_LIST_RESET:"GET_STUDENT_COURSES_LIST_RESET",
  


  GET_STUDENT_COURSES_FILTER_LIST_LOADING:"GET_STUDENT_COURSES_LIST_LOADING",
  GET_STUDENT_COURSES_FILTER_LIST_LOADED:"GET_STUDENT_COURSES_LIST_LOADED",
  GET_STUDENT_COURSES_FILTER_LIST_RESET:"GET_STUDENT_COURSES_LIST_RESET",


  GET_STUDENT_COURSE_DETAILS:"GET_STUDENT_COURSE_DETAILS",
  GET_STUDENT_COURSE_DETAILS_LOADING:"GET_STUDENT_COURSE_DETAILS_LOADING",
  GET_STUDENT_COURSE_DETAILS_RESET:"GET_STUDENT_COURSE_DETAILS_RESET",

  SORTBY_FILTER_STUDENT_COURSE_LIST:"SORTBY_FILTER_STUDENT_COURSE_LIST",

  COURSE_CLASSROOM_FILTER_STUDENT_LIST:"COURSE_CLASSROOM_FILTER_STUDENT_LIST",

  CREATED_BY_FILTER_STUDENT_COURSES_LIST:"CREATED_BY_FILTER_STUDENT_COURSES_LIST"
}