export const VerifyContactActionTypes = {

  VERIFY_CONTACT_OTP_REQUEST_LOADING: "VERIFY_CONTACT_OTP_REQUEST_LOADING",
  VERIFY_CONTACT_OTP_REQUEST_LOADED: "VERIFY_CONTACT_OTP_REQUEST_LOADED",
  VERIFY_CONTACT_OTP_REQUEST_ERROR_MESSAGE: "VERIFY_CONTACT_OTP_REQUEST_ERROR_MESSAGE",
  VERIFY_CONTACT_OTP_REQUEST_ERROR: "VERIFY_CONTACT_OTP_REQUEST_ERROR",
  VERIFY_CONTACT_OTP_REQUEST_RESET: "VERIFY_CONTACT_OTP_REQUEST_RESET",

  WHATSAPP_CONTACT_REQUEST_LOADING: "WHATSAPP_CONTACT_REQUEST_LOADING",
  WHATSAPP_CONTACT_REQUEST_LOADED: "WHATSAPP_CONTACT_REQUEST_LOADED",
  WHATSAPP_CONTACT_REQUEST_ERROR: "WHATSAPP_CONTACT_REQUEST_ERROR",
  WHATSAPP_CONTACT_REQUEST_RESET: "WHATSAPP_CONTACT_REQUEST_RESET",

  VERIFY_CONTACT_OTP_VERIFY_LOADING: "VERIFY_CONTACT_OTP_VERIFY_LOADING",
  VERIFY_CONTACT_OTP_VERIFY_LOADED: "VERIFY_CONTACT_OTP_VERIFY_LOADED",
  VERIFY_CONTACT_OTP_VERIFY_ERROR: "VERIFY_CONTACT_OTP_VERIFY_ERROR",
  VERIFY_CONTACT_OTP_VERIFY_RESET: "VERIFY_CONTACT_OTP_VERIFY_RESET",

  ADD_CONTACT_WHATSAPP_LOADING: "ADD_CONTACT_WHATSAPP_LOADING",
  ADD_CONTACT_WHATSAPP_LOADED: "ADD_CONTACT_WHATSAPP_LOADED",
  ADD_CONTACT_WHATSAPP_ERROR: "ADD_CONTACT_WHATSAPP_ERROR",
  ADD_CONTACT_WHATSAPP_RESET: "ADD_CONTACT_WHATSAPP_RESET",



}
