export const PRIVATE_DOMAINE_ACTION_TYPE = {
  GET_DOMAIN_AVAILABILITY_LOADING: "GET_DOMAIN_AVAILABILITY_LOADING",
  GET_DOMAIN_AVAILABILITY_LOADED: "GET_DOMAIN_AVAILABILITY_LOADED",
  GET_DOMAIN_AVAILABILITY_ERROR: "GET_DOMAIN_AVAILABILITY_ERROR",
  GET_DOMAIN_AVAILABILITY_RESET: "GET_DOMAIN_AVAILABILITY_RESET",

  POST_USER_DETAILS_ONLINE_LOADING: "POST_USER_DETAILS_LOADING",
  POST_USER_DETAILS_ONLINE_LOADED: "POST_USER_DETAILS_LOADED",
  POST_USER_DETAILS_ONLINE_ERROR: "POST_USER_DETAILS_ERROR",
  POST_USER_DETAILS_ONLINE_RESET: "POST_USER_DETAILS_RESET",

  POST_USER_DETAILS_OFFLINE_LOADING: "POST_USER_DETAILS_LOADING",
  POST_USER_DETAILS_OFFLINE_LOADED: "POST_USER_DETAILS_LOADED",
  POST_USER_DETAILS_OFFLINE_ERROR: "POST_USER_DETAILS_ERROR",
  POST_USER_DETAILS_OFFLINE_RESET: "POST_USER_DETAILS_RESET",

  POST_CART_DETAILS_LOADING: "POST_CART_DETAILS_LOADING",
  POST_CART_DETAILS_LOADED: "POST_CART_DETAILS_LOADED",
  POST_CART_DETAILS_ERROR: "POST_CART_DETAILS_ERROR",
  POST_CART_DETAILS_RESET: "POST_CART_DETAILS_RESET",

  GET_TLDS_PRICE_LOADING: "GET_TLDS_PRICE_LOADING",
  GET_TLDS_PRICE_LOADED: "GET_TLDS_PRICE_LOADED",
  GET_TLDS_PRICE_ERROR: "GET_TLDS_PRICE_ERROR",
  GET_TLDS_PRICE_RESET: "GET_TLDS_PRICE_RESET",

  POST_DOMAIN_SUBMIT_LOADING: "POST_DOMAIN_SUBMIT_LOADING",
  POST_DOMAIN_SUBMIT_LOADED: "POST_DOMAIN_SUBMIT_LOADED",
  POST_DOMAIN_SUBMIT_ERROR: "POST_DOMAIN_SUBMIT_ERROR",
  POST_DOMAIN_SUBMIT_RESET: "POST_DOMAIN_SUBMIT_RESET",

  PATCH_CREATE_WEBSITE_LOADING: "PATCH_CREATE_WEBSITE_LOADING",
  PATCH_CREATE_WEBSITE_LOADED: "PATCH_CREATE_WEBSITE_LOADED",
  PATCH_CREATE_WEBSITE_ERROR: "PATCH_CREATE_WEBSITE_ERROR",
  PATCH_CREATE_WEBSITE_RESET: "PATCH_CREATE_WEBSITE_RESET",

  PATCH_INSTITUTE_DETAILS_LOADING: "PATCH_INSTITUTE_DETAILS_LOADING",
  PATCH_INSTITUTE_DETAILS_LOADED: "PATCH_INSTITUTE_DETAILS_LOADED",
  PATCH_INSTITUTE_DETAILS_ERROR: "PATCH_INSTITUTE_DETAILS_ERROR",
  PATCH_INSTITUTE_DETAILS_RESET: "PATCH_INSTITUTE_DETAILS_RESET",

  GET_DOMAIN_CUSTOMER_REGISTER_LOADING: "GET_DOMAIN_CUSTOMER_REGISTER_LOADING",
  GET_DOMAIN_CUSTOMER_REGISTER_LOADED: "GET_DOMAIN_CUSTOMER_REGISTER_LOADED",
  GET_DOMAIN_CUSTOMER_REGISTER_ERROR: "GET_DOMAIN_CUSTOMER_REGISTER_ERROR",
  GET_DOMAIN_CUSTOMER_REGISTER_RESET: "GET_DOMAIN_CUSTOMER_REGISTER_RESET",

  GET_DOMAIN_REGISTER_LOADING: "GET_DOMAIN_REGISTER_LOADING",
  GET_DOMAIN_REGISTER_LOADED: "GET_DOMAIN_REGISTER_LOADED",
  GET_DOMAIN_REGISTER_ERROR: "GET_DOMAIN_REGISTER_ERROR",
  GET_DOMAIN_REGISTER_RESET: "GET_DOMAIN_REGISTER_RESET",

  GET_ORDER_DETAILS_LOADING: "GET_ORDER_DETAILS_LOADING",
  GET_ORDER_DETAILS_LOADED: "GET_ORDER_DETAILS_LOADED",
  GET_ORDER_DETAILS_ERROR: "GET_ORDER_DETAILS_ERROR",
  GET_ORDER_DETAILS_RESET: "GET_ORDER_DETAILS_RESET",

  GET_DOMAIN_DETAILS_LOADING: "GET_DOMAIN_DETAILS_LOADING",
  GET_DOMAIN_DETAILS_LOADED: "GET_DOMAIN_DETAILS_LOADED",
  GET_DOMAIN_DETAILS_ERROR: "GET_DOMAIN_DETAILS_ERROR",
  GET_DOMAIN_DETAILS_RESET: "GET_DOMAIN_DETAILS_RESET",

  GET_INSTITUTE_DETAILS_LOADING: "GET_INSTITUTE_DETAILS_LOADING",
  GET_INSTITUTE_DETAILS_LOADED: "GET_INSTITUTE_DETAILS_LOADED",
  GET_INSTITUTE_DETAILS_ERROR: "GET_INSTITUTE_DETAILS_ERROR",
  GET_INSTITUTE_DETAILS_RESET: "GET_INSTITUTE_DETAILS_RESET",

  GET_USER_DETAILS_LOADING: "GET_USER_DETAILS_LOADING",
  GET_USER_DETAILS_LOADED: "GET_USER_DETAILS_LOADED",
  GET_USER_DETAILS_ERROR: "GET_USER_DETAILS_ERROR",
  GET_USER_DETAILS_RESET: "GET_USER_DETAILS_RESET",

  CREATE_ORDER_LOADING: "CREATE_ORDER_LOADING",
  CREATE_ORDER_LOADED: "CREATE_ORDER_LOADED",
  CREATE_ORDER_ERROR: "CREATE_ORDER_ERROR",
  CREATE_ORDER_RESET: "CREATE_ORDER_RESET",

  SEND_MAILER1_LOADING: "SEND_MAILER1_LOADING",
  SEND_MAILER1_LOADED: "SEND_MAILER1_LOADED",
  SEND_MAILER1_ERROR: "SEND_MAILER1_ERROR",
  SEND_MAILER1_RESET: "SEND_MAILER1_RESET",

  SEND_MAILER2_LOADING: "SEND_MAILER2_LOADING",
  SEND_MAILER2_LOADED: "SEND_MAILER2_LOADED",
  SEND_MAILER2_ERROR: "SEND_MAILER2_ERROR",
  SEND_MAILER2_RESET: "SEND_MAILER2_RESET",

  SEND_MAILER3_LOADING: "SEND_MAILER3_LOADING",
  SEND_MAILER3_LOADED: "SEND_MAILER3_LOADED",
  SEND_MAILER3_ERROR: "SEND_MAILER3_ERROR",
  SEND_MAILER3_RESET: "SEND_MAILER3_RESET",

  SEND_MAILER4_LOADING: "SEND_MAILER4_LOADING",
  SEND_MAILER4_LOADED: "SEND_MAILER4_LOADED",
  SEND_MAILER4_ERROR: "SEND_MAILER4_ERROR",
  SEND_MAILER4_RESET: "SEND_MAILER4_RESET",

  POST_SUPPORT_MAIL_LOADING: "POST_SUPPORT_MAIL_LOADING",
  POST_SUPPORT_MAIL_LOADED: "POST_SUPPORT_MAIL_LOADED",
  POST_SUPPORT_MAIL_ERROR: "POST_SUPPORT_MAIL_ERROR",
  POST_SUPPORT_MAIL_RESET: "POST_SUPPORT_MAIL_RESET",


  SUPPORT_MAIL_LOADING: "SUPPORT_MAIL_LOADING",
  SUPPORT_MAIL_LOADED: "SUPPORT_MAIL_LOADED",
  SUPPORT_MAIL_ERROR: "SUPPORT_MAIL_ERROR",


  SET_REVIEW_LOADING: "SET_REVIEW_LOADING",
  SET_REVIEW_LOADED: "SET_REVIEW_LOADED",
  SET_REVIEW_ERROR: "SET_REVIEW_ERROR",


  TECH_SUPPORT_FORM_LOADING: "TECH_SUPPORT_FORM_LOADING",
  TECH_SUPPORT_FORM_LOADED: "TECH_SUPPORT_FORM_LOADED",
  TECH_SUPPORT_FORM_ERROR: "TECH_SUPPORT_FORM_ERROR",
  TECH_SUPPORT_FORM_RESET: "TECH_SUPPORT_FORM_RESET",

}