export const VISITORTYPES = {
  POST_VISITOR_LOADING: "POST_VISITOR_LOADING",
  POST_VISITOR_CANCEL_LOADING: "POST_VISITOR_CANCEL_LOADING",
  POST_VISITOR_LOADED: "POST_VISITOR_LOADED",
  POST_VISITOR_ERROR: "POST_VISITOR_ERROR",
  POST_VISITOR_RESET: "POST_VISITOR_RESET",

  //ALL ADMIN /GUARD
  GET_VISITOR_LIST_LOADING: "GET_VISITOR_LIST_LOADING",
  GET_VISITOR_LIST_LOADED: "GET_VISITOR_LIST_LOADED",
  GET_VISITOR_LIST_ERROR: "GET_VISITOR_LIST_ERROR",
  GET_VISITOR_LIST_RESET: "GET_VISITOR_LIST_RESET",

  GET_SINGLE_VISITOR_LOADING: "GET_SINGLE_VISITOR_LOADING",
  GET_SINGLE_VISITOR_LOADED: "GET_SINGLE_VISITOR_LOADED",
  GET_SINGLE_VISITOR_ERROR: "GET_SINGLE_VISITOR_ERROR",
  GET_SINGLE_VISITOR_RESET: "GET_SINGLE_VISITOR_RESET",

  EDIT_VISITOR_LOADING: "EDIT_VISITOR_LOADING",
  EDIT_VISITOR_LOADED: "EDIT_VISITOR_LOADED",
  EDIT_VISITOR_ERROR: "EDIT_VISITOR_ERROR",
  EDIT_VISITOR_RESET: "EDIT_VISITOR_RESET",

  SEARCH_VISITOR: "SEARCH_VISITOR",

  SORT_VISITOR: "SORT_VISITOR",

  //teacher
  GET_TEACHER_VISITOR_LIST_LOADING: "GET_TEACHER_VISITOR_LIST_LOADING",
  GET_TEACHER_VISITOR_LIST_LOADED: "GET_TEACHER_VISITOR_LIST_LOADED",
  GET_TEACHER_VISITOR_LIST_ERROR: "GET_TEACHER_VISITOR_LIST_ERROR",

  GET_TEACHER_SORT_VISITOR: "GET_TEACHER_SORT_VISITOR",
  SEARCH_TEACHER_VISITOR: "SEARCH_TEACHER_VISITOR",
  STATUS_CANCELED: "STATUS_CANCELED",

  SEARCH_VISITOR_DATA: "SEARCH_VISITOR_DATA",

  //teacher status
  VISITOR_STATUS: "VISITOR_STATUS",

}