export const ClassroomDetailActionType = {
  CLASSROOM_DETAIL_LIST_LOADING: "CLASSROOM_DETAIL_LIST_LOADING",
  CLASSROOM_DETAIL_LIST_LOADED: "CLASSROOM_DETAIL_LIST_LOADED",
  CLASSROOM_DETAIL_LIST_ERROR: "CLASSROOM_DETAIL_LIST_ERROR",
  CLASSROOM_DETAIL_LIST_RESET: "CLASSROOM_DETAIL_LIST_RESET",

  CLASSROOM_DETAIL_ONLINE_TEST_LIST_LOADING: "CLASSROOM_DETAIL_ONLINE_TEST_LIST_LOADING",
  CLASSROOM_DETAIL_ONLINE_TEST_LIST_LOADED: "CLASSROOM_DETAIL_ONLINE_TEST_LIST_LOADED",
  CLASSROOM_DETAIL_ONLINE_TEST_LIST_ERROR: "CLASSROOM_DETAIL_ONLINE_TEST_LIST_ERROR",
  CLASSROOM_DETAIL_ONLINE_TEST_LIST_RESET: "CLASSROOM_DETAIL_ONLINE_TEST_LIST_RESET",

  CLASSROOM_DETAIL_ONLINE_CLASS_LIST_LOADING: "CLASSROOM_DETAIL_ONLINE_CLASS_LIST_LOADING",
  CLASSROOM_DETAIL_ONLINE_CLASS_LIST_LOADED: "CLASSROOM_DETAIL_ONLINE_CLASS_LIST_LOADED",
  CLASSROOM_DETAIL_ONLINE_CLASS_LIST_ERROR: "CLASSROOM_DETAIL_ONLINE_CLASS_LIST_ERROR",
  CLASSROOM_DETAIL_ONLINE_CLASS_LIST_RESET: "CLASSROOM_DETAIL_ONLINE_CLASS_LIST_RESET",

  CLASSROOM_DETAIL_ASSIGNMENT_LIST_LOADING: "CLASSROOM_DETAIL_ASSIGNMENT_LIST_LOADING",
  CLASSROOM_DETAIL_ASSIGNMENT_LIST_LOADED: "CLASSROOM_DETAIL_ASSIGNMENT_LIST_LOADED",
  CLASSROOM_DETAIL_ASSIGNMENT_LIST_ERROR: "CLASSROOM_DETAIL_ASSIGNMENT_LIST_ERROR",
  CLASSROOM_DETAIL_ASSIGNMENT_LIST_RESET: "CLASSROOM_DETAIL_ASSIGNMENT_LIST_RESET",

  CLASSROOM_DETAIL_TEACHER_LIST_LOADING: "CLASSROOM_DETAIL_TEACHER_LIST_LOADING",
  CLASSROOM_DETAIL_TEACHER_LIST_LOADED: "CLASSROOM_DETAIL_TEACHER_LIST_LOADED",
  CLASSROOM_DETAIL_TEACHER_LIST_ERROR: "CLASSROOM_DETAIL_TEACHER_LIST_ERROR",
  CLASSROOM_DETAIL_TEACHER_LIST_RESET: "CLASSROOM_DETAIL_TEACHER_LIST_RESET",

  CLASSROOM_DETAIL_STUDENT_LIST_LOADING: "CLASSROOM_DETAIL_STUDENT_LIST_LOADING",
  CLASSROOM_DETAIL_STUDENT_LIST_LOADED: "CLASSROOM_DETAIL_STUDENT_LIST_LOADED",
  CLASSROOM_DETAIL_STUDENT_LIST_ERROR: "CLASSROOM_DETAIL_STUDENT_LIST_ERROR",
  CLASSROOM_DETAIL_STUDENT_LIST_RESET: "CLASSROOM_DETAIL_STUDENT_LIST_RESET",

  CLASSROOM_DETAIL_COURSE_LIST_LOADING: "CLASSROOM_DETAIL_COURSE_LIST_LOADING",
  CLASSROOM_DETAIL_COURSE_LIST_LOADED: "CLASSROOM_DETAIL_COURSE_LIST_LOADED",
  CLASSROOM_DETAIL_COURSE_LIST_ERROR: "CLASSROOM_DETAIL_COURSE_LIST_ERROR",
  CLASSROOM_DETAIL_COURSE_LIST_RESET: "CLASSROOM_DETAIL_COURSE_LIST_RESET",

  CLASSROOM_DETAIL_ONLINE_CLASS_LOADING: "CLASSROOM_DETAIL_ONLINE_CLASS_LOADING",
  CLASSROOM_DETAIL_ONLINE_CLASS_LOADED: "CLASSROOM_DETAIL_ONLINE_CLASS_LOADED",
  CLASSROOM_DETAIL_ONLINE_CLASS_ERROR: "CLASSROOM_DETAIL_ONLINE_CLASS_ERROR",
  CLASSROOM_DETAIL_ONLINE_CLASS_RESET: "CLASSROOM_DETAIL_ONLINE_CLASS_RESET",

  CLASSROOM_DETAIL_ASSIGNMENT_TEACHER_LIST_LOADING:
    "CLASSROOM_DETAIL_ASSIGNMENT_TEACHER_LIST_LOADING",
  CLASSROOM_DETAIL_ASSIGNMENT_TEACHER_LIST_LOADED:
    "CLASSROOM_DETAIL_ASSIGNMENT_TEACHER_LIST_LOADED",
  CLASSROOM_DETAIL_ASSIGNMENT_TEACHER_LIST_ERROR:
    "CLASSROOM_DETAIL_ASSIGNMENT_TEACHER_LIST_ERROR",
  CLASSROOM_DETAIL_ASSIGNMENT_TEACHER_LIST_RESET:
    "CLASSROOM_DETAIL_ASSIGNMENT_TEACHER_LIST_RESET",

  CLASSROOM_DETAIL_DELETE_LOADING: "CLASSROOM_DETAIL_DELETE_LOADING",
  CLASSROOM_DETAIL_DELETE_LOADED: "CLASSROOM_DETAIL_DELETE_LOADED",
  CLASSROOM_DETAIL_DELETE_ERROR: "CLASSROOM_DETAIL_DELETE_ERROR",
  CLASSROOM_DETAIL_DELETE_RESET: "CLASSROOM_DETAIL_DELETE_RESET",

  CLASSROOM_DETAIL_SEARCH_LOADING: "CLASSROOM_DETAIL_SEARCH_LOADING",
  CLASSROOM_DETAIL_SEARCH_LOADED: "CLASSROOM_DETAIL_SEARCH_LOADED",
  CLASSROOM_DETAIL_SEARCH_ERROR: "CLASSROOM_DETAIL_SEARCH_ERROR",
  CLASSROOM_DETAIL_SEARCH_RESET: "CLASSROOM_DETAIL_SEARCH_RESET",

  CLASSROOM_DETAIL_CLASSROOM_ID_LOADING:
    "CLASSROOM_DETAIL_CLASSROOM_ID_LOADING",
  CLASSROOM_DETAIL_CLASSROOM_ID_LOADED: "CLASSROOM_DETAIL_CLASSROOM_ID_LOADED",
  CLASSROOM_DETAIL_CLASSROOM_ID_ERROR: "CLASSROOM_DETAIL_CLASSROOM_ID_ERROR",
  CLASSROOM_DETAIL_CLASSROOM_ID_RESET: "CLASSROOM_DETAIL_CLASSROOM_ID_RESET",

  CLASSROOM_DETAIL_ADD_TEACHER_LOADING: "CLASSROOM_DETAIL_ADD_TEACHER_LOADING",
  CLASSROOM_DETAIL_ADD_TEACHER_LOADED: "CLASSROOM_DETAIL_ADD_TEACHER_LOADED",
  CLASSROOM_DETAIL_ADD_TEACHER_ERROR: "CLASSROOM_DETAIL_ADD_TEACHER_ERROR",
  CLASSROOM_DETAIL_ADD_TEACHER_RESET: "CLASSROOM_DETAIL_ADD_TEACHER_RESET",

  CLASSROOM_DETAIL_ASSIGN_TO_UPDATE_LOADING:
    "CLASSROOM_DETAIL_ASSIGN_TO_UPDATE_LOADING",
  CLASSROOM_DETAIL_ASSIGN_TO_UPDATE_LOADED:
    "CLASSROOM_DETAIL_ASSIGN_TO_UPDATE_LOADED",
  CLASSROOM_DETAIL_ASSIGN_TO_UPDATE_ERROR:
    "CLASSROOM_DETAIL_ASSIGN_TO_UPDATE_ERROR",
  CLASSROOM_DETAIL_ASSIGN_TO_UPDATE_RESET:
    "CLASSROOM_DETAIL_ASSIGN_TO_UPDATE_RESET",

  ONLINE_CLASSROOM_ASSIGN_TO_UPDATE_LOADING:
    "ONLINE_CLASSROOM_ASSIGN_TO_UPDATE_LOADING",
  ONLINE_CLASSROOM_ASSIGN_TO_UPDATE_LOADED:
    "ONLINE_CLASSROOM_ASSIGN_TO_UPDATE_LOADED",
  ONLINE_CLASSROOM_ASSIGN_TO_UPDATE_ERROR:
    "ONLINE_CLASSROOM_ASSIGN_TO_UPDATE_ERROR",
  ONLINE_CLASSROOM_ASSIGN_TO_UPDATE_RESET:
    "ONLINE_CLASSROOM_ASSIGN_TO_UPDATE_RESET",

  CLASSROOM_DETAIL_ADD_ASSIGNMENT_LOADING:
    "CLASSROOM_DETAIL_ADD_ASSIGNMENT_LOADING",
  CLASSROOM_DETAIL_ADD_ASSIGNMENT_LOADED:
    "CLASSROOM_DETAIL_ADD_ASSIGNMENT_LOADED",
  CLASSROOM_DETAIL_ADD_ASSIGNMENT_ERROR:
    "CLASSROOM_DETAIL_ADD_ASSIGNMENT_ERROR",
  CLASSROOM_DETAIL_ADD_ASSIGNMENT_RESET:
    "CLASSROOM_DETAIL_ADD_ASSIGNMENT_RESET",

  CLASSROOM_DETAIL_UPDATE_ASSIGNMENT_LOADING:
    "CLASSROOM_DETAIL_UPDATE_ASSIGNMENT_LOADING",
  CLASSROOM_DETAIL_UPDATE_ASSIGNMENT_LOADED:
    "CLASSROOM_DETAIL_UPDATE_ASSIGNMENT_LOADED",
  CLASSROOM_DETAIL_UPDATE_ASSIGNMENT_ERROR:
    "CLASSROOM_DETAIL_UPDATE_ASSIGNMENT_ERROR",
  CLASSROOM_DETAIL_UPDATE_ASSIGNMENT_RESET:
    "CLASSROOM_DETAIL_UPDATE_ASSIGNMENT_RESET",

  CLASSROOM_DETAIL_SORT_TEACHER_LOADING:
    "CLASSROOM_DETAIL_SORT_TEACHER_LOADING",
  CLASSROOM_DETAIL_SORT_TEACHER_LOADED: "CLASSROOM_DETAIL_SORT_TEACHER_LOADED",
  CLASSROOM_DETAIL_SORT_TEACHER_ERROR: "CLASSROOM_DETAIL_SORT_TEACHER_ERROR",
  CLASSROOM_DETAIL_SORT_TEACHER_RESET: "CLASSROOM_DETAIL_SORT_TEACHERRESET",

  CLASSROOM_DETAIL_ASSIGNMENT_SELECTION_LOADING:
    "CLASSROOM_DETAIL_ASSIGNMENT_SELECTION_LOADING",
  CLASSROOM_DETAIL_ASSIGNMENT_SELECTION_LOADED:
    "CLASSROOM_DETAIL_ASSIGNMENT_SELECTION_LOADED",
  CLASSROOM_DETAIL_ASSIGNMENT_SELECTION_ERROR:
    "CLASSROOM_DETAIL_ASSIGNMENT_SELECTION_ERROR",
  CLASSROOM_DETAIL_ASSIGNMENT_SELECTION_RESET:
    "CLASSROOM_DETAIL_ASSIGNMENT_SELECTION_RESET",
  CLASSROOM_DETAILS_RESET: "CLASSROOM_DETAILS_RESET",
  SORT_BY_TOGGLE: "SORT_BY_TOGGLE",


  ONLINE_TEST_ASSIGN_TO_UPDATE_LOADING: "ONLINE_TEST_ASSIGN_TO_UPDATE_LOADING",
  ONLINE_TEST_ASSIGN_TO_UPDATE_LOADED: "ONLINE_TEST_ASSIGN_TO_UPDATE_LOADED",
  ONLINE_TEST_ASSIGN_TO_UPDATE_ERROR: "ONLINE_TEST_ASSIGN_TO_UPDATE_ERROR",
  ONLINE_TEST_ASSIGN_TO_UPDATE_RESET: "ONLINE_TEST_ASSIGN_TO_UPDATE_RESET",
  ONLINE_TEST_NOTIFY: "ONLINE_TEST_NOTIFY",
  ONLINE_TEST_DELETE: "ONLINE_TEST_DELETE",
  ONLINE_TEST_CANCEL: "ONLINE_TEST_CANCEL"
}
