export const userActionType = {
  CHANGE_USER_PHOTO_HEADER: "CHANGE_USER_PHOTO_HEADER",
  SET_USER_LOGIN: "SET_USER_LOGIN",
  // SET_SUBDOMAIN_USER_LOGIN: "SET_SUBDOMAIN_USER_LOGIN",
  SET_USER_ACTIVE_ROLE: "SET_USER_ACTIVE_ROLE",
  SET_USER_BUSINESS_TYPE: "SET_USER_BUSINESS_TYPE",
  SET_INSTITUTE_INFORMATION: "SET_INSTITUTE_INFORMATION",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  USER__LIST: "USER__LIST",

  DELETE_ACCOUNT_LOADING: "DELETE_ACCOUNT_LOADING",
  DELETE_ACCOUNT_LOADED: "DELETE_ACCOUNT_LOADED",
  DELETE_ACCOUNT_ERROR: "DELETE_ACCOUNT_ERROR",
  DELETE_ACCOUNT_RESET: "DELETE_ACCOUNT_RESET",

  CHANGE_PASSWORD_LOADING: "CHANGE_PASSWORD_LOADING",
  CHANGE_PASSWORD_LOADED: "CHANGE_PASSWORD_LOADED",
  CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR",
  CHANGE_PASSWORD_RESET: "CHANGE_PASSWORD_RESET",
};
