export const insUserByRoleActionType = {
    INS_USER_BY_ROLE_LOADING:"INS_USER_BY_ROLE_LOADING",
    INS_USER_BY_ROLE_LOADED:"INS_USER_BY_ROLE_LOADED",
    INS_USER_BY_ROLE_LOADING_ERROR:"INS_USER_BY_ROLE_LOADING_ERROR",
    INS_USER_BY_ROLE_MORE_LOADING:"INS_USER_BY_ROLE_MORE_LOADING",
    INS_USER_BY_ROLE_MORE_LOADED:"INS_USER_BY_ROLE_MORE_LOADED",
    INS_USER_BY_ROLE_MORE_LOADING_ERROR:"INS_USER_BY_ROLE_MORE_LOADING_ERROR",
}