export const INSTITUTE_PAGE_WEBSITE_SECTION_LIST_AT = {
  INSTITUTE_PAGE_WEBSITE_SECTION_LIST: "INSTITUTE_PAGE_WEBSITE_SECTION_LIST",

  INS_INFO_SOCIAL_LINKS: "INS_INFO_SOCIAL_LINKS",
  INS_INFO_SOCIAL_LINKS_LOADING: "INS_INFO_SOCIAL_LINKS_LOADING",
  INS_INFO_SOCIAL_LINKS_LOADED: "INS_INFO_SOCIAL_LINKS_LOADED",
  ADD_SOCIAL_LINKS_INS_INFO: "ADD_SOCIAL_LINKS_INS_INFO",
};
