export const StudentOnlineExamActionTypes = {
  SOE_CREATING: "SOE_CREATING",
  SOE_CREATED: "SOE_CREATED",
  SOE_CREATE_ERROR: "SOE_CREATE_ERROR",
  SOE_LIST_LOADING: "SOE_LIST_LOADING",
  SOE_LIST_LOADED: "SOE_LIST_LOADED",
  SOE_LIST_ERROR: "SOE_LIST_ERROR",
  SOE_UPDATING: "SOE_UPDATING",
  SOE_UPDATED: "SOE_UPDATED",
  SOE_UPDATE_ERROR: "SOE_UPDATE_ERROR",
  SOE_DELETE: "SOE_DELETE",
  SOE_COURSEID_GET: "SOE_COURSEID_GET",
  SEARCH_BY_SOE: "SEARCH_BY_SOE",
  FILTERBYCOURSES_SOE: "FILTERBYCOURSES_SOE",
  OES_GET_ASSIGN_LOADING_ERROR: "OES_GET_ASSIGN_LOADING_ERROR",
  OES_GET_ASSIGN_LOADED: "OES_GET_ASSIGN_LOADED",
  OES_GET_ASSIGN_LOADING: "OES_GET_ASSIGN_LOADING"
}