export const GALLERYUPLOADTYPES = {
  GALLERYUPLOAD_CREATE: "GALLERYUPLOAD_CREATE",
  GALLERYUPLOAD_DELETE: "GALLERYUPLOAD_DELETE",
  GALLERYUPLOAD_READ: "GALLERYUPLOAD_READ",
  GALLERYUPLOAD_EDIT: "GALLERYUPLOAD_EDIT",
  GALLERYUPLOAD_UPDATE_SELECTION: "GALLERYUPLOAD_UPDATE_SELECTION",
  GALLERYUPLOAD_UPDATE_SELECTION_LOADING: "GALLERYUPLOAD_UPDATE_SELECTION_LOADING",
  GALLERYUPLOAD_RESET:"GALLERYUPLOAD_RESET"
};
