export const EDNEED_FEED_AT = {

  EDNEED_FEED_COMMUNITY_LOADING: "EDNEED_FEED_COMMUNITY_LOADING",
  EDNEED_FEED_COMMUNITY_LOADED: "EDNEED_FEED_COMMUNITY_LOADED",
  EDNEED_FEED_COMMUNITY_ERROR: "EDNEED_FEED_COMMUNITY_ERROR",

  EDNEED_FEED_INSTITUTE_LISTING_LOADING: "EDNEED_FEED_INSTITUTE_LISTING_LOADING",
  EDNEED_FEED_INSTITUTE_LISTING_LOADED: "EDNEED_FEED_INSTITUTE_LISTING_LOADED",
  EDNEED_FEED_INSTITUTE_LISTING_ERROR: "EDNEED_FEED_INSTITUTE_LISTING_LOADING",


  EDNEED_FEED_INSTITUTE_LIKE_LOADING: "EDNEED_FEED_INSTITUTE_LIKE_LOADING",
  EDNEED_FEED_INSTITUTE_LIKE_LOADED: "EDNEED_FEED_INSTITUTE_LIKE_LOADED",
  EDNEED_FEED_INSTITUTE_LIKE_ERROR: "EDNEED_FEED_INSTITUTE_LIKE_LOADING",

  EDNEED_FEED_INSTAGRAM_LOADING: "EDNEED_FEED_INSTAGRAM_LOADING",
  EDNEED_FEED_INSTAGRAM_LOADED: "EDNEED_FEED_INSTAGRAM_LOADED",
  EDNEED_FEED_INSTAGRAM_ERROR: "EDNEED_FEED_INSTAGRAM_ERROR",


}