export const DEMOREQUEST = {
  POSTDEMODATA: "POSTDEMODATA",
  POSTDEMODATALOADING:"POSTDEMODATALOADING",
  RESETDEMOREQUEST: "RESETDEMOREQUEST",
  INVALID_EMAIL_ERROR:"INVALID_EMAIL_ERROR",
  RESET_ERROR:"RESET_ERROR"
}