export const FACULTYTYPE = {
    FACULTY_LOADING: "FACULTY_LOADING",
    FACULTY_LOADED: "FACULTY_LOADED",


    
    FACULTY_READ:"FACULTY_READ",
    FACULTY_CREATE:"FACULTY_CREATE",
    FACULTY_EDIT:"FACULTY_EDIT",
    FACULTY_DELETE:"FACULTY_DELETE",
  };
  