export const SERVICE_TEMPLATE_TYPES = {



  SERVICE_TEMPLATE_LOADING: "SERVICE_TEMPLATE_LOADING",
  SERVICE_TEMPLATE_SUCCESS: "SERVICE_TEMPLATE_SUCCESS",
  SERVICE_TEMPLATE_ERROR: "SERVICE_TEMPLATE_ERROR",
  SERVICE_TEMPLATE_RESET: "SERVICE_TEMPLATE_RESET",

  SERVICE_TEMPLATE_DOMAIN_LOADING: "SERVICE_TEMPLATE_DOMAIN_LOADING",
  SERVICE_TEMPLATE_DOMAIN_SUCCESS: "SERVICE_TEMPLATE_DOMAIN_SUCCESS",
  SERVICE_TEMPLATE_DOMAIN_ERROR: "SERVICE_TEMPLATE_DOMAIN_ERROR",
  SERVICE_TEMPLATE_DOMAIN_RESET: "SERVICE_TEMPLATE_DOMAIN_RESET",


  SERVICE_TEMPLATE_LIST_LOADING: "SERVICE_TEMPLATE_LIST_LOADING",
  SERVICE_TEMPLATE_LIST_SUCCESS: "SERVICE_TEMPLATE_LIST_SUCCESS",
  SERVICE_TEMPLATE_LIST_ERROR: "SERVICE_TEMPLATE_LIST_ERROR",
  SERVICE_TEMPLATE_LIST_RESET: "SERVICE_TEMPLATE_LIST_RESET",

  SERVICE_TEMPLATE_EDIT_SETTINGS_LOADING: "SERVICE_TEMPLATE_EDIT_SETTINGS_LOADING",
  SERVICE_TEMPLATE_EDIT_SETTINGS_SUCCESS: "SERVICE_TEMPLATE_EDIT_SETTINGS_SUCCESS",
  SERVICE_TEMPLATE_EDIT_SETTINGS_ERROR: "SERVICE_TEMPLATE_EDIT_SETTINGS_ERROR",
  SERVICE_TEMPLATE_EDIT_SETTINGS_RESET: "SERVICE_TEMPLATE_EDIT_SETTINGS_RESET",

  SERVICE_TEMPLATE_EDIT_THEME_LOADING: "SERVICE_TEMPLATE_EDIT_THEME_LOADING",
  SERVICE_TEMPLATE_EDIT_THEME_SUCCESS: "SERVICE_TEMPLATE_EDIT_THEME_SUCCESS",
  SERVICE_TEMPLATE_EDIT_THEME_ERROR: "SERVICE_TEMPLATE_EDIT_THEME_ERROR",
  SERVICE_TEMPLATE_EDIT_THEME_RESET: "SERVICE_TEMPLATE_EDIT_THEME_RESET",


  SERVICE_TEMPLATE_CREATE_USER_THEME_LOADING: "SERVICE_TEMPLATE_CREATE_USER_THEME_LOADING",
  SERVICE_TEMPLATE_CREATE_USER_THEME_SUCCESS: "SERVICE_TEMPLATE_CREATE_USER_THEME_SUCCESS",
  SERVICE_TEMPLATE_CREATE_USER_THEME_ERROR: "SERVICE_TEMPLATE_CREATE_USER_THEME_ERROR",
  SERVICE_TEMPLATE_CREATE_USER_THEME_RESET: "SERVICE_TEMPLATE_CREATE_USER_THEME_RESET",

  SERVICE_TEMPLATE_SELECTED_THEME_LOADING: "SERVICE_TEMPLATE_SELECTED_THEME_LOADING",
  SERVICE_TEMPLATE_SELECTED_THEME_SUCCESS: "SERVICE_TEMPLATE_SELECTED_THEME_SUCCESS",
  SERVICE_TEMPLATE_SELECTED_THEME_ERROR: "SERVICE_TEMPLATE_SELECTED_THEME_ERROR",
  SERVICE_TEMPLATE_SELECTED_THEME_RESET: "SERVICE_TEMPLATE_SELECTED_THEME_RESET",

  DELETE_USER_TEMPLATE_LOADING: "DELETE_USER_TEMPLATE_LOADING",
  DELETE_USER_TEMPLATE_SUCCESS: "DELETE_USER_TEMPLATE_SUCCESS",
  DELETE_USER_TEMPLATE_RESET: "DELETE_USER_TEMPLATE_RESET",

  SERVICE_TEMPLATE_EDIT_PAGES_LOADING: "SERVICE_TEMPLATE_EDIT_PAGES_LOADING",
  SERVICE_TEMPLATE_EDIT_PAGES_SUCCESS: "SERVICE_TEMPLATE_EDIT_PAGES_SUCCESS",
  SERVICE_TEMPLATE_EDIT_PAGES_ERROR: "SERVICE_TEMPLATE_EDIT_PAGES_ERROR",
  SERVICE_TEMPLATE_EDIT_PAGES_RESET: "SERVICE_TEMPLATE_EDIT_PAGES_RESET",

  SERVICE_TEMPLATE_EDIT_LOADING: "SERVICE_TEMPLATE_EDIT_LOADING",
  SERVICE_TEMPLATE_EDIT_SUCCESS: "SERVICE_TEMPLATE_EDIT_SUCCESS",
  SERVICE_TEMPLATE_EDIT_ERROR: "SERVICE_TEMPLATE_EDIT_ERROR",
  SERVICE_TEMPLATE_EDIT_RESET: "SERVICE_TEMPLATE_EDIT_RESET",

  SERVICE_TEMPLATE_GET_USER_TEMPLATES_LOADING: "SERVICE_TEMPLATE_GET_USER_TEMPLATES_LOADING",
  SERVICE_TEMPLATE_GET_USER_TEMPLATES_SUCCESS: "SERVICE_TEMPLATE_GET_USER_TEMPLATES_SUCCESS",
  SERVICE_TEMPLATE_GET_USER_TEMPLATES_ERROR: "SERVICE_TEMPLATE_GET_USER_TEMPLATES_ERROR",
  SERVICE_TEMPLATE_GET_USER_TEMPLATES_RESET: "SERVICE_TEMPLATE_GET_USER_TEMPLATES_RESET",


  ACTIVATE_SERVICE_TEMPLATE_LOADING: "ACTIVATE_SERVICE_TEMPLATE_LOADING",
  ACTIVATE_SERVICE_TEMPLATE_SUCCESS: "ACTIVATE_SERVICE_TEMPLATE_SUCCESS",
  ACTIVATE_SERVICE_TEMPLATE_ERROR: "ACTIVATE_SERVICE_TEMPLATE_ERROR",
  ACTIVATE_SERVICE_TEMPLATE_RESET: "ACTIVATE_SERVICE_TEMPLATE_RESET",

  UPDATE_DYNAMIC_SERVICE_TEMPLATE: "UPDATE_DYNAMIC_SERVICE_TEMPLATE",
  UPDATE_DYNAMIC_SETTINGS_SERVICE_TEMPLATE: "UPDATE_DYNAMIC_SETTINGS_SERVICE_TEMPLATE",
  SELECT_ROUTE_PREVIEW: "SELECT_ROUTE_PREVIEW",
  SET_PARAMS_ID: "SET_PARAMS_ID",
  SERVICE_TEMPLATE_DOMAIN_CHECK: "SERVICE_TEMPLATE_DOMAIN_CHECK",

  GET_GALLERY_ALBUM_LOADING: "GET_GALLERY_ALBUM_LOADING",
  GET_GALLERY_ALBUM_SUCCESS: "GET_GALLERY_ALBUM_SUCCESS",
  GET_GALLERY_ALBUM_RESET: "GET_GALLERY_ALBUM_RESET",

  GET_GALLERY_LOADING: "GET_GALLERY_LOADING",
  GET_GALLERY_SUCCESS: "GET_GALLERY_SUCCESS",
  GET_GALLERY_RESET: "GET_GALLERY_RESET",

  GET_SERVICE_DETAIL_LOADING: "GET_SERVICE_DETAIL_LOADING",
  GET_SERVICE_DETAIL_SUCCESS: "GET_SERVICE_DETAIL_SUCCESS",
  GET_SERVICE_DETAIL_RESET: "GET_SERVICE_DETAIL_RESET",

  GET_FACULTY_DETAIL_LOADING: "GET_FACULTY_DETAIL_LOADING",
  GET_FACULTY_DETAIL_SUCCESS: "GET_FACULTY_DETAIL_SUCCESS",
  GET_FACULTY_DETAIL_RESET: "GET_FACULTY_DETAIL_RESET",
  
  GET_CATEGORY_DETAIL_LOADING: "GET_CATEGORY_DETAIL_LOADING",
  GET_CATEGORY_DETAIL_SUCCESS: "GET_CATEGORY_DETAIL_SUCCESS",
  GET_CATEGORY_DETAIL_RESET: "GET_CATEGORY_DETAIL_RESET",
  GET_CATEGORY_DETAIL_ERROR: "GET_CATEGORY_DETAIL_ERROR",

  GET_ALLSERVICES_OF_CATEGORY_LOADING: "GET_ALLSERVICES_OF_CATEGORY_LOADING",
  GET_ALLSERVICES_OF_CATEGORY_SUCCESS: "GET_ALLSERVICES_OF_CATEGORY_SUCCESS",
  GET_ALLSERVICES_OF_CATEGORY_RESET: "GET_ALLSERVICES_OF_CATEGORY_RESET",
  GET_ALLSERVICES_OF_CATEGORY_ERROR: "GET_ALLSERVICES_OF_CATEGORY_ERROR",

  GET_SINGLE_CATEGORY_LOADING: "GET_SINGLE_CATEGORY_LOADING",
  GET_SINGLE_CATEGORY_SUCCESS: "GET_SINGLE_CATEGORY_SUCCESS",
  GET_SINGLE_CATEGORY_RESET: "GET_SINGLE_CATEGORY_RESET",
  GET_SINGLE_CATEGORY_ERROR: "GET_SINGLE_CATEGORY_ERROR",
}