export const GALLERYTYPES = {
  GALLERY_CREATE: "GALLERY_CREATE",
  GALLERY_DELETE: "GALLERY_DELETE",
  GALLERY_READ: "GALLERY_READ",
  GALLERY_EDIT: "GALLERY_EDIT",
  GALLERY_UPDATE_SELECTION: "GALLERY_UPDATE_SELECTION",

  GALLERY_READ_ID: "GALLERY_READ_ID",
};
