export const INS_BLOG_ACTION_TYPES = {
  GET_CATEGORY_LIST_LOADING: "GET_CATEGORY_LIST_LOADING",
  GET_CATEGORY_LIST_LOADED: "GET_CATEGORY_LIST_LOADED",
  GET_CATEGORY_LIST_RESET: "GET_CATEGORY_LIST_RESET",
  GET_CATEGORY_LIST_ERROR: "GET_CATEGORY_LIST_ERROR",

  POST_CATEGORY_LOADING: "POST_CATEGORY_LOADING",
  POST_CATEGORY_LOADED: "POST_CATEGORY_LOADED",
  POST_CATEGORY_RESET: "POST_CATEGORY_RESET",
  POST_CATEGORY_ERROR: "POST_CATEGORY_ERROR",
  POST_CATEGORY_DUPLICATE_ERROR: "POST_CATEGORY_DUPLICATE_ERROR",

  DELETE_CATEGORY_LOADING: "DELETE_CATEGORY_LOADING",
  DELETE_CATEGORY_LOADED: "DELETE_CATEGORY_LOADED",
  DELETE_CATEGORY_RESET: "DELETE_CATEGORY_RESET",
  DELETE_CATEGORY_ERROR: "DELETE_CATEGORY_ERROR",

  GET_SINGLE_CATEGORY_LOADING: "GET_SINGLE_CATEGORY_LOADING",
  GET_SINGLE_CATEGORY_LOADED: "GET_SINGLE_CATEGORY_LOADED",
  GET_SINGLE_CATEGORY_RESET: "GET_SINGLE_CATEGORY_RESET",
  GET_SINGLE_CATEGORY_ERROR: "GET_SINGLE_CATEGORY_ERROR",

  PATCH_CATEGORY_LOADING: "PATCH_CATEGORY_LOADING",
  PATCH_CATEGORY_LOADED: "PATCH_CATEGORY_LOADED",
  PATCH_CATEGORY_RESET: "PATCH_CATEGORY_RESET",
  PATCH_CATEGORY_ERROR: "PATCH_CATEGORY_ERROR",

  SEARCH_CATEGORY: "SEARCH_CATEGORY",

  GET_BLOG_LIST_LOADING: "GET_BLOG_LIST_LOADING",
  GET_BLOG_LIST_LOADED: "GET_BLOG_LIST_LOADED",
  GET_BLOG_LIST_RESET: "GET_BLOG_LIST_RESET",
  GET_BLOG_LIST_ERROR: "GET_BLOG_LIST_ERROR",

  GET_AUTHOR_DESCRIPTION_LOADED: "GET_AUTHOR_DESCRIPTION_LOADED",

  GET_CATEGORY_WISE_BLOGS_LOADED: "GET_CATEGORY_WISE_BLOGS_LOADED",

  POST_BLOG_LOADING: "POST_BLOG_LOADING",
  POST_BLOG_SAVE_LOADING: "POST_BLOG_SAVE_LOADING",
  POST_BLOG_LOADED: "POST_BLOG_LOADED",
  POST_BLOG_RESET: "POST_BLOG_RESET",
  POST_BLOG_ERROR: "POST_BLOG_ERROR",

  DELETE_BLOG_LOADING: "DELETE_BLOG_LOADING",
  DELETE_BLOG_LOADED: "DELETE_BLOG_LOADED",
  DELETE_BLOG_RESET: "DELETE_BLOG_RESET",
  DELETE_BLOG_ERROR: "DELETE_BLOG_ERROR",

  GET_SINGLE_BLOG_LOADING: "GET_SINGLE_BLOG_LOADING",
  GET_SINGLE_BLOG_LOADED: "GET_SINGLE_BLOG_LOADED",
  GET_SINGLE_BLOG_RESET: "GET_SINGLE_BLOG_RESET",
  GET_SINGLE_BLOG_ERROR: "GET_SINGLE_BLOG_ERROR",

  PATCH_BLOG_LOADING: "PATCH_BLOG_LOADING",
  PATCH_BLOG_SAVE_LOADING: "PATCH_BLOG_SAVE_LOADING",
  PATCH_BLOG_LOADED: "PATCH_BLOG_LOADED",
  PATCH_BLOG_RESET: "PATCH_BLOG_RESET",
  PATCH_BLOG_ERROR: "PATCH_BLOG_ERROR",

  RESTORE_TRASH_BLOGS: "RESTORE_TRASH_BLOGS",

  MULTIPLE_DELETE_SUCCESS: "MULTIPLE_DELETE_SUCCESS",

  ACCEPT_REJECT_BLOGS: "ACCEPT_REJECT_BLOGS",

  DOWNLOAD_EXCEL_SHEET: "DOWNLOAD_EXCEL_SHEET",

  GET_WEBSITE_BLOG_LIST_LOADING: "GET_WEBSITE_BLOG_LIST_LOADING",
  GET_WEBSITE_BLOG_LIST_LOADED: "GET_WEBSITE_BLOG_LIST_LOADED",
  GET_WEBSITE_BLOG_LIST_RESET: "GET_WEBSITE_BLOG_LIST_RESET",
  GET_WEBSITE_BLOG_LIST_ERROR: "GET_WEBSITE_BLOG_LIST_ERROR",

  LIKE_BLOG_LOADING: "LIKE_BLOG_LOADING",
  LIKE_BLOG_LOADED: "LIKE_BLOG_LOADED",
  LIKE_BLOG_ERROR: "LIKE_BLOG_ERROR",
  LIKE_BLOG_RESET: "LIKE_BLOG_RESET",

  GET_BLOG_LIKES_LOADING: "GET_BLOG_LIKES_LOADING",
  GET_BLOG_LIKES_LOADED: "GET_BLOG_LIKES_LOADED",
  GET_BLOG_LIKES_ERROR: "GET_BLOG_LIKES_ERROR",
  GET_BLOG_LIKES_RESET: "GET_BLOG_LIKES_RESET",

  GET_WEBSITE_FEATURE_BLOG_LOADING: "GET_WEBSITE_FEATURE_BLOG_LOADING",
  GET_WEBSITE_FEATURE_BLOG_LOADED: "GET_WEBSITE_FEATURE_BLOG_LOADED",
  GET_WEBSITE_FEATURE_BLOG_RESET: "GET_WEBSITE_FEATURE_BLOG_RESET",
  GET_WEBSITE_FEATURE_BLOG_ERROR: "GET_WEBSITE_FEATURE_BLOG_ERROR",

}