export const ANNOUNCEMENT_LIST_AT = {

    ANNOUNCEMENT_READ: "ANNOUNCEMENT_READ",

    ANNOUNCEMENT_CREATE: "ANNOUNCEMENT_CREATE",
    ANNOUNCEMENT_CREATE_LOADING: "ANNOUNCEMENT_CREATE_LOADING",
    ANNOUNCEMENT_CREATE_ERROR: "ANNOUNCEMENT_CREATE_ERROR",
    ANNOUNCEMENT_CREATE_RESET: "ANNOUNCEMENT_CREATE_RESET",

    ANNOUNCEMENT_EDIT_LOADING: "ANNOUNCEMENT_EDIT_LOADING",
    ANNOUNCEMENT_EDIT: "ANNOUNCEMENT_EDIT",
    ANNOUNCEMENT_EDIT_RESET: "ANNOUNCEMENT_EDIT_RESET",
    ANNOUNCEMENT_EDIT_ERROR: "ANNOUNCEMENT_EDIT_ERROR",

    ANNOUNCEMENT_DELETE_LOADING: "ANNOUNCEMENT_DELETE_LOADING",
    ANNOUNCEMENT_DELETE: "ANNOUNCEMENT_DELETE",
    ANNOUNCEMENT_DELETE_RESET: "ANNOUNCEMENT_DELETE_RESET",
    
    ANNOUNCEMENT_UPDATE_SELECTION: "ANNOUNCEMENT_UPDATE_SELECTION",
    ANNOUNCEMENT_UPDATE_SELECTION_CLEAR: "ANNOUNCEMENT_UPDATE_SELECTION_CLEAR",
    ANNOUNCEMENT_UPDATE: "ANNOUNCEMENT_UPDATE",
    ANNOUNCEMENT_UPDATE_ERROR: "ANNOUNCEMENT_UPDATE_ERROR",
    ANNOUNCEMENT_UPDATED: "ANNOUNCEMENT_UPDATED",
    ANNOUNCEMENT_UPDATE_LIST_STATUS: "ANNOUNCEMENT_UPDATE_LIST_STATUS",

}