export const CLASSROOM_ASSIGNED_TYPE = {
  CLASSROOM_ASSIGNED_READ: "CLASSROOM_ASSIGNED_READ",
  CLASSROOM_ASSIGNED_CHANGE: "CLASSROOM_ASSIGNED_CHANGE",
  CLASSROOM_ASSIGNED_CHANGE_RESET: "CLASSROOM_ASSIGNED_CHANGE_RESET",
  CLASSROOM_ASSIGNED_FACULTY: "CLASSROOM_ASSIGNED_FACULTY",
  CLASSROOM_ASSIGNED_DELETE: "CLASSROOM_ASSIGNED_DELETE",
  POST_COURSE_ASSIGNED: "POST_COURSE_ASSIGNED",


  UPDATE_SELECTION_COURSE_ID: "UPDATE_SELECTION_COURSE_ID",
  ASSIGNED_TEACHER_CLASSROOM_DATA: "ASSIGNED_TEACHER_CLASSROOM_DATA",
  ASSIGNED_TEACHER_CLASSROOM_DATA_LOADING: "ASSIGNED_TEACHER_CLASSROOM_DATA_LOADING",
  DELETE_ASSIGNED_CLASSROOM: "DELETE_ASSIGNED_CLASSROOM",

};
