export const INSTITUTE_THEME_ACTION_TYPES = {
  INSTITUTE_CHANGE_THEME: "INSTITUTE_CHANGE_THEME",
  INSTITUTE_UPDATE_THEME: "INSTITUTE_UPDATE_THEME",
  INSTITUTE_DEFAULT_THEME: "INSTITUTE_DEFAULT_THEME",
  INSTITUTE_GET_DEFAULT_THEME: "INSTITUTE_GET_DEFAULT_THEME",
  INSTITUTE_USER_CUSTOME_THEME: "INSTITUTE_USER_CUSTOME_THEME",
  INSTITUTE_GET_USER_CUSTOME_THEME: "INSTITUTE_GET_USER_CUSTOME_THEME",
  INSTITUTE_ACTIVATE_THEME: "INSTITUTE_ACTIVATE_THEME",
  INSTITUTE_ACTIVATE_DEFAULT_THEME: "INSTITUTE_ACTIVATE_DEFAULT_THEME",
  INSTITUTE_ACTIVATE_CUSTOM_THEME: "INSTITUTE_ACTIVATE_CUSTOM_THEME",
  INSTITUTE_DELETE_CUSTOM_THEME: "INSTITUTE_DELETE_CUSTOM_THEME",
  INSTITUTE_EDIT_CUSTOM_THEME: "INSTITUTE_EDIT_CUSTOM_THEME",
  INSTITUTE_CREATE_NEW_CUSTOM_THEME: "INSTITUTE_CREATE_NEW_CUSTOM_THEME",
  INSTITUTE_CREATE_NEW_CUSTOM_THEME_SAVE:
    "INSTITUTE_CREATE_NEW_CUSTOM_THEME_SAVE",
  INSTITUTE__DEFAULT_THEME: "INSTITUTE_ACTIVATE_DEFAULT_THEME",
  INSTITUTE_PREVIEW_DEFAULT_THEME: "INSTITUTE_PREVIEW_DEFAULT_THEME",
  INSTITUTE_CLONE_DEFAULT_THEME: "INSTITUTE_CLONE_DEFAULT_THEME",
  INSTITUTE_CLONE_THEME: "INSTITUTE_CLONE_THEME",
  INSTITUTE_GET_DEFAULT_THEME_LOADING: "INSTITUTE_GET_DEFAULT_THEME_LOADING",
  INSTITUTE_GET_CUSTOM_THEME_LOADING: "INSTITUTE_GET_CUSTOM_THEME_LOADING",
  INSTITUTE_UPDATE_THEME_VALUE: "INSTITUTE_UPDATE_THEME_VALUE",
  INSTITUTE_GET_PUBLIC_THEME: "INSTITUTE_GET_PUBLIC_THEME",
  INSTITUTE_UPDATE_THEME_SKIN_EDIT: "INSTITUTE_UPDATE_THEME_SKIN_EDIT",
  SET_THEME_SKIN_ID: "SET_THEME_SKIN_ID",

  //for edit custom theme to store
  INSTITUTE_GET_USER_CUSTOME_THEME_EDIT:
    "INSTITUTE_GET_USER_CUSTOME_THEME_EDIT",
  INSTITUTE_ACTIVATE_SIDE_THEME: "INSTITUTE_ACTIVATE_SIDE_THEME",
  CLONE_THEME_EMPTY: "CLONE_THEME_EMPTY",

  GET_SINGLGE_PREVIEW_THEME: "GET_SINGLGE_PREVIEW_THEME",
  EMPTY_CREATE_NEW_THEME: "EMPTY_CREATE_NEW_THEME",
  TEMPORARY_DISPLAY_PREFERED_SKIN_THEME:
    "TEMPORARY_DISPLAY_PREFERED_SKIN_THEME",
  TEMPORARY_DISPLAY_CUSTOM_SKIN_THEME: "TEMPORARY_DISPLAY_CUSTOM_SKIN_THEME",

  INSTITUTE_WEBSITE_ACTIVATE_THEME_LOADING:"INSTITUTE_WEBSITE_ACTIVATE_THEME_LOADING"
};
