export const TEACHERTYPE = {
  TEACHER_HISTORY: "TEACHER_HISTORY",
  TEACHER_INVITE_REST: "TEACHER_INVITE_REST",
  TEACHER_INVITE: "TEACHER_INVITE",
  TEACHER_INVITE_ERROR: "TEACHER_INVITE_ERROR",
  TEACHER_INVITE_ERROR_RESET: "TEACHER_INVITE_ERROR_RESET",
  TEACHER_INVITE_LOADING: "TEACHER_INVITE_LOADING",
  TEACHER_EDIT: "TEACHER_EDIT",
  TEACHER_DELETE: "TEACHER_DELETE",
  TEACHER_ID: "TEACHER_ID",
  TEACHER_POST_ID: "TEACHER_POST_ID",
  ERROR: "ERROR",
  GET_ERROR: "GET_ERROR",
  GET_HISTORY: "GET_HISTORY",
  LOADING: "LOADING",
  GET_NOT_ASSIGNED_CLASSROOMS: "GET_NOT_ASSIGNED_CLASSROOMS"
};
