export const NOTIFICATION_ACTION_TYPES = {
    NOTIFICATION_BELL_ICON_LOADING:"NOTIFICATION_BELL_ICON_LOADING",
    NOTIFICATION_BELL_ICON_LOADED:"NOTIFICATION_BELL_ICON_LOADED",
    NOTIFICATION_BELL_ICON_UPDATE:"NOTIFICATION_BELL_ICON_UPDATE",
    NOTIFICATION_BELL_ICON_REDUCE_COUNT:"NOTIFICATION_BELL_ICON_REDUCE_COUNT",
    NOTIFICATION_SHOWALL_PAGE_LOADING:"NOTIFICATION_SHOWALL_PAGE_LOADING",
    NOTIFICATION_SHOWALL_PAGE_LOADED:"NOTIFICATION_SHOWALL_PAGE_LOADED",
    GET_ALL_NOTIFICATIONS_LOADED:"GET_ALL_NOTIFICATIONS_LOADED",
    GET_ALL_NOTIFICATIONS_LOADING:"GET_ALL_NOTIFICATIONS_LOADING",
    CHANGE_BELL_ICON_TYPE:"CHANGE_BELL_ICON_TYPE",
    NOTIFICATION_BELL_ICON_UPDATE_UNREAD:"NOTIFICATION_BELL_ICON_UPDATE_UNREAD",
    RECENT_NOTIFICATION:"RECENT_NOTIFICATION"


}