export const AdminCourseActionTypes = {

    ADMIN_COURSE_CONTENT_CREATING: "ADMIN_COURSE_CONTENT_CREATING",
    ADMIN_COURSE_CONTENT_CREATED: "ADMIN_COURSE_CONTENT_CREATED",
    ADMIN_COURSE_CONTENT_CREATE_ERROR: "ADMIN_COURSE_CONTENT_CREATE_ERROR",
    ADMIN_COURSE_CONTENT_CREATE_RESET: "ADMIN_COURSE_CONTENT_CREATE_RESET",

    ADMIN_GET_COURSE_CONTENT_LOADING: "ADMIN_GET_COURSE_CONTENT_LOADING",
    ADMIN_GET_COURSE_CONTENT_LOADED: "ADMIN_GET_COURSE_CONTENT_LOADED",
    ADMIN_GET_COURSE_CONTENT_ERROR: "ADMIN_GET_COURSE_CONTENT_ERROR",
    ADMIN_GET_COURSE_CONTENT_RESET: "ADMIN_GET_COURSE_CONTENT_RESET",

    ADMIN_COURSE_INFO_CREATING: "ADMIN_COURSE_CREATING",
    ADMIN_COURSE_INFO_CREATING_SAVE: "ADMIN_COURSE_CREATING_SAVE",
    ADMIN_COURSE_INFO_CREATED: "ADMIN_COURSE_CREATED",
    ADMIN_COURSE_INFO_CREATE_ERROR: "ADMIN_COURSE_CREATE_ERROR",
    ADMIN_COURSE_INFO_CREATE_RESET: "ADMIN_COURSE_CREATE_RESET",

    ADMIN_GET_TEACHER_LIST: "ADMIN_GET_TEACHER_LIST",
    ADMIN_GET_TEACHER_LIST_LOADING: "ADMIN_GET_TEACHER_LIST_LOADING",
    ADMIN_GET_TEACHER_LIST_RESET: "ADMIN_GET_TEACHER_LIST_RESET",
    ADMIN_GET_TEACHER_LIST_ERROR: "ADMIN_GET_TEACHER_LIST_ERROR",

    ADMIN_GET_ALL_CLASSROOMS_SUBJECTS_LOADING: "ADMIN_GET_ALL_CLASSROOMS_SUBJECTS_LOADING",
    ADMIN_GET_ALL_CLASSROOMS_SUBJECTS: "ADMIN_GET_ALL_CLASSROOMS_SUBJECTS",
    ADMIN_GET_ALL_CLASSROOMS_SUBJECTS_ERROR: "ADMIN_GET_ALL_CLASSROOMS_SUBJECTS_ERROR",
    ADMIN_GET_ALL_CLASSROOMS_SUBJECTS_RESET: "ADMIN_GET_ALL_CLASSROOMS_SUBJECTS_RESET",

    ADMIN_ADD_NEW_CLASSROOM_LOADING: "ADMIN_ADD_NEW_CLASSROOM_LOADING",
    ADMIN_ADD_NEW_CLASSROOM: "ADMIN_ADD_NEW_CLASSROOM",
    ADMIN_ADD_NEW_CLASSROOM_RESET: "ADMIN_ADD_NEW_CLASSROOM_RESET",
    ADMIN_ADD_NEW_SAME_CLASSROOM_ERROR: "ADMIN_ADD_NEW_SAME_CLASSROOM_ERROR",
    ADMIN_ADD_NEW_SAME_CLASSROOM_RESET_ERROR: "ADMIN_ADD_NEW_SAME_CLASSROOM_RESET_ERROR",

    ADMIN_ADD_NEW_SUBJECT: "ADMIN_ADD_NEW_SUBJECT",
    ADMIN_ADD_NEW_SUBJECT_LOADING: "ADMIN_ADD_NEW_SUBJECT_LOADING",
    ADMIN_ADD_NEW_SUBJECT_RESET: "ADMIN_ADD_NEW_SUBJECT_RESET",
    ADMIN_ADD_NEW_SUBJECT_ERROR: "ADMIN_ADD_NEW_SUBJECT_ERROR",

    ADMIN_COURSE_LIST_LOADING: "ADMIN_COURSE_LIST_LOADING",
    ADMIN_COURSE_LIST_LOADED: "ADMIN_COURSE_LIST_LOADED",
    ADMIN_COURSE_LIST_ERROR: "ADMIN_COURSE_LIST_ERROR",
    ADMIN_COURSE_LIST_RESET: "ADMIN_COURSE_LIST_RESET",


    GET_ADMIN_COURSE_INFO_DATA_LOADING: "GET_ADMIN_COURSE_INFO_DATA_LOADING",
    GET_ADMIN_COURSE_INFO_DATA_LOADED: "GET_ADMIN_COURSE_INFO_DATA_LOADED",
    GET_ADMIN_COURSE_INFO_DATA_ERROR: "GET_ADMIN_COURSE_INFO_DATA_ERROR",
    GET_ADMIN_COURSE_INFO_DATA_RESET: "GET_ADMIN_COURSE_INFO_DATA_RESET",


    ADMIN_FILTER_COURSE_LIST: "ADMIN_FILTER_COURSE_LIST",

    EDIT_COURSE_INFO_LOADING: "EDIT_COURSE_INFO_LOADING",
    EDIT_COURSE_INFO: " EDIT_COURSE_INFO",
    EDIT_COURSE_INFO_RESET: "EDIT_COURSE_INFO_RESET",
    EDIT_COURSE_INFO_ERROR: "EDIT_COURSE_INFO_ERROR",
    ADMIN_COURSE_RESET_MAIN: "ADMIN_COURSE_RESET_MAIN",


    DELETE_COURSE_LOADING: "DELETE_COURSE_LOADING",
    DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
    DELETE_COURSE_RESET: "DELETE_COURSE_RESET",

    EDIT_TAXANOMY_LOADING: "EDIT_TAXANOMY_LOADING",
    EDIT_TAXANOMY_SUCCESS: "EDIT_TAXANOMY_SUCCESS",
    EDIT_TAXANOMY_RESET: "EDIT_TAXANOMY_RESET",

    GET_TAXANOMY_LOADING: "GET_TAXANOMY_LOADING",
    GET_TAXANOMY_SUCCESS: "GET_TAXANOMY_SUCCESS",
    GET_TAXANOMY_RESET: "GET_TAXANOMY_RESET",

    IMAGE_POPUP_SHOW: "IMAGE_POPUP_SHOW",
    IMAGE_POPUP_RESET: "IMAGE_POPUP_RESET",


    POST_ASSIGNED_DATA:"POST_ASSIGNED_DATA",
    POST_ASSIGNED_DATA_LOADING:"POST_ASSIGNED_DATA_LOADING",
    POST_ASSIGNED_DATA_RESET:"POST_ASSIGNED_DATA_RESET",

    FILTER_ADMIN_LIST_COURSE_CLASSROOMS:"FILTER_ADMIN_LIST_COURSE_CLASSROOMS",
    FILTER_ADMIN_LIST_ASSIGNTO:"FILTER_ADMIN_LIST_ASSIGNTO"
}