export const FEE_MANAGEMENT_STUDENT_TYPE = {

  GET_STUDENT_FEE_LOADING: "GET_STUDENT_FEE_LOADING",
  GET_STUDENT_FEE_LOADED: "GET_STUDENT_FEE_LOADED",
  GET_STUDENT_FEE_RESET: "GET_STUDENT_FEE_RESET",

  GET_STUDENT_FEE_SINGLE_LOADING: "GET_STUDENT_FEE_SINGLE_LOADING",
  GET_STUDENT_FEE_SINGLE_LOADED: "GET_STUDENT_FEE_SINGLE_LOADED",
  GET_STUDENT_FEE_SINGLE_RESET: "GET_STUDENT_FEE_SINGLE_RESET",


  GET_STUDENT_COURSE_DATA_LOADING: "GET_STUDENT_COURSE_DATA_LOADING",
  GET_STUDENT_COURSE_DATA_LOADED: "GET_STUDENT_COURSE_DATAE_LOADED",
  GET_STUDENT_COURSE_DATA_RESET: "GET_STUDENT_COURSE_DATA_RESET",


  CREATE_RAZORPAY_ORDER_LOADING: "CREATE_RAZORPAY_ORDER_LOADING",
  CREATE_RAZORPAY_ORDER_LOADED: "CREATE_RAZORPAY_ORDER_LOADED",
  CREATE_RAZORPAY_ORDER_ERROR: "CREATE_RAZORPAY_ORDER_ERROR",
  CREATE_RAZORPAY_ORDER_RESET: "CREATE_RAZORPAY_ORDER_RESET",

  GET_ORDER_DETAILS_LOADING: "GET_ORDER_DETAILS_LOADING",
  GET_ORDER_DETAILS_LOADED: "GET_ORDER_DETAILS_LOADED",
  GET_ORDER_DETAILS_RESET: "GET_ORDER_DETAILS_RESET",


  GET_STUDENT_FEE_VIEW_DETAILS_LOADING: "GET_STUDENT_FEE_VIEW_DETAILS_LOADING",
  GET_STUDENT_FEE_VIEW_DETAILS_LOADED: "GET_STUDENT_FEE_VIEW_DETAILS_LOADED",
  GET_STUDENT_FEE_VIEW_DETAILS_RESET: "GET_STUDENT_FEE_VIEW_DETAILS_RESET",

  
  GET_STUDENT_INVOICE_DETAILS_LOADING: "GET_STUDENT_INVOICE_DETAILS_LOADING",
  GET_STUDENT_INVOICE_DETAILS_LOADED: "GET_STUDENT_INVOICE_DETAILS_LOADED",
  GET_STUDENT_INVOICE_DETAILS_RESET:"GET_STUDENT_INVOICE_DETAILS_RESET"


};
