export const EDITTEACHERLIST = {

    EDIT_TEACHER_LIST_READ: "EDIT_TEACHER_LIST_READ",
    EDIT_TEACHER_LIST_READ_RESET: "EDIT_TEACHER_LIST_READ_RESET",
    EDIT_TEACHER_LIST_READ_COUNT: "EDIT_TEACHER_LIST_READ_COUNT",
    EDIT_TEACHER_LIST_USERNAME_READ: "EDIT_TEACHER_LIST_USERNAME_READ",
    EDIT_ASSIGNED_TEACHER_LIST_ClASSROOM_READ: "EDIT_ASSIGNED_TEACHER_LIST_ClASSROOM_READ",
    EDIT_ASSIGNED_TEACHER_LIST_ClASSROOM_READ_CLEAR: "EDIT_ASSIGNED_TEACHER_LIST_ClASSROOM_READ_CLEAR",
    EDIT_TEACHER_LIST_CREATE: "EDIT_TEACHER_LIST_CREATE",
    EDIT_TEACHER_LIST_ASSIGN_CLASSROOM: "EDIT_TEACHER_LIST_ASSIGN_CLASSROOM",
    EDIT_TEACHER_LIST_EDIT: "EDIT_TEACHER_LIST_EDIT",
    EDIT_TEACHER_LIST_DELETE: "EDIT_TEACHER_LIST_DELETE",
    EDIT_TEACHER_LIST_CLASSROOM_DELETE: "EDIT_TEACHER_LIST_CLASSROOM_DELETE",
    EDIT_TEACHER_LIST_UPDATE_SELECTION: "EDIT_TEACHER_LIST_UPDATE_SELECTION",
    EDIT_TEACHER_LIST_UPDATE: "EDIT_TEACHER_LIST_UPDATE",
    EDIT_TEACHER_LIST_UPDATE_ERROR: "EDIT_TEACHER_LIST_UPDATE_ERROR",
    EDIT_TEACHER_LIST_UPDATED: "EDIT_TEACHER_LIST_UPDATED",
    EDIT_TEACHER_LIST_UPDATE_CLEAR: "EDIT_TEACHER_LIST_UPDATE_CLEAR",
    POST_CLASS_TEACHER: "POST_CLASS_TEACHER",
    EDIT_TEACHER_LIST_USERNAME_RESET: "EDIT_TEACHER_LIST_USERNAME_RESET"
}