export const PUBLIC_PROFILE_TYPE = {
  CREATE_PUBLIC_PROFILE: "CREATE_PUBLIC_PROFILE",
  PUBLIC_PROFILES: "PUBLIC_PROFILES",
  PUBLIC_PROFILE_BY_ID: "PUBLIC_PROFILE_BY_ID",
  POST_LIKE: "POST_LIKE",

  PUBLIC_PROFILE_SORT: "PUBLIC_PROFILE_SORT",
  PUBLIC_PROFILE_SORT_MORE: "PUBLIC_PROFILE_SORT_MORE",
  PUBLIC_PROFILE_SEARCH: "PUBLIC_PROFILE_SEARCH",
  PUBLIC_PROFILE_SEARCH_SCROLL:"PUBLIC_PROFILE_SEARCH_SCROLL",
  PUBLIC_PROFILE_SEARCH_TYPE_SCROLL:"PUBLIC_PROFILE_SEARCH_TYPE_SCROLL",
  PUBLIC_PROFILE_USERNAME_SEARCH: "PUBLIC_PROFILE_USERNAME_SEARCH",
  PUBLIC_PROFILES_LOADED: "PUBLIC_PROFILES_LOADED",
  PUBLIC_PROFILES_LOADING: "PUBLIC_PROFILES_LOADING",
  PUBLIC_PROFILES_SUCCESS: "PUBLIC_PROFILES_SUCCESS",
  PUBLIC_PROFILES_ERROR: "PUBLIC-PROFILES_ERROR",
  PUBLIC_PROFILES_SORT_SCROLL_MORE:"PUBLIC_PROFILES_SORT_SCROLL_MORE",
  PUBLIC_PROFILES_MORE_LOAD_SUCCESS: "PUBLIC_PROFILES_MORE_LOAD_SUCCESS",

  PUBLIC_PROFILE_BY_ID_LOADED: "PUBLIC_PROFILE_BY_ID_LOADED",
  PUBLIC_PROFILE_BY_ID_LOADING: "PUBLIC_PROFILE_BY_ID_LOADING",
  PUBLIC_PROFILE_BY_ID_SUCCESS: "PUBLIC_PROFILE_BY_ID_SUCCESS",
  PUBLIC_PROFILE_BY_ID_ERROR: "PUBLIC_PROFILE_BY_ID_ERROR",

  PUT_LIKE: "PUT_LIKE",
  PUT_LIKE_RESET: "PUT_LIKE_RESET",
  PUT_LIKE_LOADING: "PUT_LIKE_LOADING",
  PUT_LIKE_ERROR: "PUT_LIKE_ERROR",

  PUT_UNLIKE: "PUT_UNLIKE",
  PUT_UNLIKE_LOADING: "PUT_UNLIKE_LOADING",
  PUT_UNLIKE_RESET: "PUT_UNLIKE_RESET",
  PUT_UNLIKE_ERROR: "PUT_UNLIKE_ERROR",

  PUT_FOLLOWER: "PUT_FOLLOW",
  PUT_FOLLOWER_LOADING: "PUT_FOLLOW_LOADING",
  PUT_FOLLOWER_ERROR: "PUT_FOLLOW_ERROR",
  PUT_FOLLOWER_RESET: "PUT_FOLLOW_RESET",

  PUT_UNFOLLOWER: "PUT_UNFOLLOW",
  PUT_UNFOLLOWER_LOADING: "PUT_UNFOLLOW_LOADING",
  PUT_UNFOLLOWER_ERROR: "PUT_UNFOLLOW_ERROR",
  PUT_UNFOLLOWER_RESET: "PUT_UNFOLLOW_RESET",

  PUBLIC_PROFILE_UPDATE_LIKE: "PUBLIC_PROFILE_UPDATE_LIKE",
  PUBLIC_PROFILE_UPDATE_UNLIKE: "PUBLIC_PROFILE_UPDATE_UNLIKE",

  PUBLIC_PROFILE_UPDATE_FOLLOW: "PUBLIC_PROFILE_UPDATE_FOLLOW",
  PUBLIC_PROFILE_UPDATE_UNFOLLOW: "PUBLIC_PROFILE_UPDATE_UNFOLLOW",

  PUBLIC_PROFILE_GET_FOLLOWINGLIST: "PUBLIC_PROFILE_FOLLOWINGLIST",
  PUBLIC_PROFILE_GET_FOLLOWERLIST: "PUBLIC_PROFILE_FOLLOWERLIST",

  PUBLIC_PROFILE_FOLLOW_FOLLOWERLIST: "PUBLIC_PROFILE_FOLLOW_FOLLOWERLIST",
  PUBLIC_PROFILE_UNFOLLOW_FOLLOWERLIST: "PUBLIC_PROFILE_UNFOLLOW_FOLLOWERLIST",

  PUBLIC_PROFILE_FOLLOW_FOLLOWINGLIST: "PUBLIC_PROFILE_FOLLOW_FOLLOWINGLIST",
  PUBLIC_PROFILE_UNFOLLOW_FOLLOWINGLIST:
    "PUBLIC_PROFILE_UNFOLLOW_FOLLOWINGLIST",

  PUBLIC_PROFILE_REMOVE_FOLLOWERS: "PUBLIC_PROFILE_REMOVE_FOLLOWERS",

  // GET_FOLLOWERLIST_FOLLOWERS:"GET_FOLLOWERLIST_FOLLOWERS",
  // GET_FOLLOWINGLIST_FOLLOWERS:"GET_FOLLOWINGLIST_FOLLOWERS",

  PUBLIC_PROFILE_EXPERIENCE_GET: "PUBLIC_PROFILE_EXPERIENCE_GET",
  PUBLIC_PROFILE_EXPERIENCE_ADD: "PUBLIC_PROFILE_EXPERIENCE_ADD",
  PUBLIC_PROFILE_EXPERIENCE_ADD_LOADING:
    "PUBLIC_PROFILE_EXPERIENCE_ADD_LOADING",

  PUBLIC_PROFILE_EXPERIENCE_EDIT: "PUBLIC_PROFILE_EXPERIENCE_EDIT",
  PUBLIC_PROFILE_EXPERIENCE_EDIT_LOADING:
    "PUBLIC_PROFILE_EXPERIENCE_EDIT_LOADING",

  PUBLIC_PROFILE_EXPERIENCE_DELETE: "PUBLIC_PROFILE_EXPERIENCE_DELETE",
  PUBLIC_PROFILE_EXPERIENCE_DELETE_LOADING:
    "PUBLIC_PROFILE_EXPERIENCE_DELETE_LOADING",

  PUBLIC_PROFILE_EXPERIENCE_LIST_UPDATE:
    "PUBLIC_PROFILE_EXPERIENCE_LIST_UPDATE",

  PUBLIC_PROFILE_EDIT_LINK: "PUBLIC_PROFILE_EDIT_LINK",
  PUBLIC_PROFILE_EDIT_LINK_LOADING: "PUBLIC_PROFILE_EDIT_LINK_LOADING",
  PUBLIC_PROFILE_EDIT_LINK_UPDATE: "PUBLIC_PROFILE_EDIT_LINK_UPDATE",

  PUBLIC_PROFILES_AFFILIATE_GET: "PUBLIC_PROFILES_AFFILIATE_GET",
  PUBLIC_PROFILES_AFFILIATE_POST: "PUBLIC_PROFILES_AFFILIATE_POST",
  PUBLIC_PROFILES_AFFILIATE_DELETE: "PUBLIC_PROFILES_AFFILIATE_DELETE",
  PUBLIC_PROFILES_AFFILIATE_PATCH: "PUBLIC_PROFILES_AFFILIATE_PATCH",

  PUBLIC_PROFILES_EDUCATION: "PUBLIC_PROFILES_EDUCATION",
  PUBLIC_PROFILES_EXPERIENCE: "PUBLIC_PROFILES_EXPERIENCE",
  PUBLIC_PROFILES_LANGUAGE: "PUBLIC_PROFILES_LANGUAGE",

  GET_PUBLIC_PROFILES_REVIEWS: "GET_PUBLIC_PROFILES_REVIEWS",
  PUBLIC_PROFILE_POST_REVIEW: "PUBLIC_PROFILE_POST_REVIEW",
  PUBLIC_PROFILE_EDIT_REVIEW: "PUBLIC_PROFILE_EDIT_REVIEW",
  PUBLIC_PROFILE_DELETE_REVIEW: "PUBLIC_PROFILE_DELETE_REVIEW",

  PUBLIC_PROFILES_BANNER: "PUBLIC_PROFILES_BANNER",
  PUBLIC_PROFILES_ABOUT: "PUBLIC_PROFILES_ABOUT",
  PUBLIC_PROFILES_HIGHLIGHT: "PUBLIC_PROFILES_HIGHLIGHT",

  PUBLIC_PROFILES_LEVEL: "PUBLIC_PROFILES_LEVEL",
  PUBLIC_PROFILES_TEACHING_MODE: "PUBLIC_PROFILES_TEACHING_MODE",
  PUBLIC_PROFILES_TAUGHT_SUBJECT: "PUBLIC_PROFILES_TAUGHT_SUBJECT",
  PUBLIC_PROFILES_SKILLS: "PUBLIC_PROFILES_SKILLS",

  PUBLIC_PROFILES_GET_CONTACT: "PUBLIC_PROFILES_GET_CONTACT",
  PUBLIC_PROFILES_PATCH_CONTACT: "PUBLIC_PROFILES_PATCH_CONTACT",
  PUBLIC_PROFILES_PATCH_CONTACT_ADRRESS:
    "PUBLIC_PROFILES_PATCH_CONTACT_ADRRESS",

  PUBLIC_PROFILES_STORE_RATING: "PUBLIC_PROFILES_STORE_RATING",
  PUBLIC_PROFILES_GET_CONTACT_AND_ADDRESS:
    "PUBLIC_PROFILES_GET_CONTACT_AND_ADDRESS",

  PUBLIC_PROFILES_GET_PRIMARYADDRESS: "PUBLIC_PROFILES_GET_PRIMARYADDRESS",
  PUBLIC_PROFILES_POST_PRIMARYADDRESS: "PUBLIC_PROFILES_POST_PRIMARYADDRESS",
  PUBLIC_PROFILES_PATCH_PRIMARYADDRESS: "PUBLIC_PROFILES_PATCH_PRIMARYADDRESS",
  PUBLIC_PROFILES_DELETE_PRIMARYADDRESS:
    "PUBLIC_PROFILES_DELETE_PRIMARYADDRESS",
  PUBLIC_PROFILES_GET_WORKADDRESS: "PUBLIC_PROFILES_GET_WORKADDRESS",
  PUBLIC_PROFILES_PATCH_WORKADDRESS: "PUBLIC_PROFILES_PATCH_WORKADDRESS",
  PUBLIC_PROFILES_POST_WORKADDRESS: "PUBLIC_PROFILES_POST_WORKADDRESS",
  PUBLIC_PROFILES_DELETE_WORKADDRESS: "PUBLIC_PROFILES_DELETE_WORKADDRESS",

  PUBLIC_PROFILES_AWARD_GET: "PUBLIC_PROFILES_AWARD_GET",
  PUBLIC_PROFILES_AWARD_POST: "PUBLIC_PROFILES_AWARD_POST",
  PUBLIC_PROFILES_AWARD_EDIT: "PUBLIC_PROFILES_AWARD_EDIT",
  PUBLIC_PROFILES_AWARD_DELETE: "PUBLIC_PROFILES_AWARD_DELETE",

  PUBLIC_PROFILES_EDUCATION_GET: "PUBLIC_PROFILES_EDUCATION_GET",
  PUBLIC_PROFILES_EDUCATION_POST: "PUBLIC_PROFILES_EDUCATION_POST",
  PUBLIC_PROFILES_EDUCATION_EDIT: "PUBLIC_PROFILES_EDUCATION_EDIT",
  PUBLIC_PROFILES_EDUCATION_DELETE: "PUBLIC_PROFILES_EDUCATION_DELETE",

  PUBLIC_PROFILES_CERTIFICATE_GET: "PUBLIC_PROFILES_CERTIFICATE_GET",
  PUBLIC_PROFILES_CERTIFICATE_POST: "PUBLIC_PROFILES_CERTIFICATE_POST",
  PUBLIC_PROFILES_CERTIFICATE_EDIT: "PUBLIC_PROFILES_CERTIFICATE_EDIT",
  PUBLIC_PROFILES_CERTIFICATE_DELETE: "PUBLIC_PROFILES_CERTIFICATE_DELETE",

  PUBLIC_PROFILES_IMAGES_GET: "PUBLIC_PROFILES_IMAGES_GET",
  PUBLIC_PROFILES_IMAGES_POST: "PUBLIC_PROFILES_IMAGES_POST",
  PUBLIC_PROFILES_IMAGES_ADD: "PUBLIC_PROFILES_IMAGES_ADD",
  PUBLIC_PROFILES_IMAGES_DELETE: "PUBLIC_PROFILES_IMAGES_DELETE",

  PUBLIC_PROFILES_ALBUM_IMAGES_EDIT: "PUBLIC_PROFILES_ALBUM_IMAGES_EDIT",
  PUBLIC_PROFILES_ALBUM_IMAGES_DELETE: "PUBLIC_PROFILES_ALBUM_IMAGES_DELETE",

  PUBLIC_PROFILES_ALBUM_VIDEO_EDIT: "PUBLIC_PROFILES_ALBUM_VIDEO_EDIT",
  PUBLIC_PROFILES_ALBUM_VIDEO_DELETE: "PUBLIC_PROFILES_ALBUM_VIDEO_DELETE",

  PUBLIC_PROFILES_VIDEOS_GET: "PUBLIC_PROFILES_VIDEOS_GET",
  PUBLIC_PROFILES_VIDEOS_POST: "PUBLIC_PROFILES_VIDEOS_POST",
  PUBLIC_PROFILES_VIDEOS_ADD: "PUBLIC_PROFILES_VIDEOS_ADD",
  PUBLIC_PROFILES_VIDEOS_DELETE: "PUBLIC_PROFILES_VIDEOS_DELETE",

  PUBLIC_PROFILE_INTEREST_HOBBIES_GET: "PUBLIC_PROFILE_INTEREST_HOBBIES_GET",
  PUBLIC_PROFILE_INTEREST_HOBBIES_POST: "PUBLIC_PROFILE_INTEREST_HOBBIES_POST",
  PUBLIC_PROFILE_INTEREST_HOBBIES_DELETE:
    "PUBLIC_PROFILE_INTEREST_HOBBIES_DELETE",

  PUBLIC_PROFILE_LANGUAGES_GET: "PUBLIC_PROFILE_LANGUAGES_GET",
  PUBLIC_PROFILE_LANGUAGES_POST: "PUBLIC_PROFILE_LANGUAGES_POST",
  PUBLIC_PROFILE_LANGUAGES_PATCH: "PUBLIC_PROFILE_LANGUAGES_PATCH",
  PUBLIC_PROFILE_LANGUAGES_DELETE: "PUBLIC_PROFILE_LANGUAGES_DELETE",

  PUBLIC_PROFILE_USERTYPE_UPDATE: "PUBLIC_PROFILE_USERTYPE_UPDATE",

  NULL_USER_NAME_DATA: "NULL_USER_NAME_DATA",
};
