export const EdPartnerTYPES = {
  POST_PARTNER_LOADING: "POST_PARTNER_LOADING",
  POST_PARTNER_LOADED: "POST_PARTNER_LOADED",
  POST_PARTNER_ERROR: "POST_PARTNER_ERROR",
  POST_PARTNER_RESET: "POST_PARTNER_RESET",
}