export const InvitationHistoryActionType = {

  INVITATION_HISTORY_LIST_LOADING: "INVITATION_HISTORY_LIST_LOADING",
  INVITATION_HISTORY_LIST_LOADED: "INVITATION_HISTORY_LIST_LOADED",
  INVITATION_HISTORY_LIST_ERROR: "INVITATION_HISTORY_LIST_ERROR",
  INVITATION_HISTORY_LIST_RESET: "INVITATION_HISTORY_LIST_RESET",


  INVITATION_HISTORY_DELETE_LOADING: "INVITATION_HISTORY_DELETE_LOADING",
  INVITATION_HISTORY_DELETE_SUCCESS: "INVITATION_HISTORY_DELETE_SUCCESS",
  INVITATION_HISTORY_DELETE_RESET: "INVITATION_HISTORY_DELETE_RESET",
  INVITATION_HISTORY_DELETE_ERROR: "INVITATION_HISTORY_DELETE_ERROR",

  INVITATION_HISTORY_RESEND_LOADING: "INVITATION_HISTORY_RESEND_LOADING",
  INVITATION_HISTORY_RESEND_SUCCESS: "INVITATION_HISTORY_RESEND_SUCCESS",
  INVITATION_HISTORY_RESEND_RESET: "INVITATION_HISTORY_RESEND_RESET",
  INVITATION_HISTORY_RESEND_ERROR: "INVITATION_HISTORY_RESEND_ERROR",


  SEARCH_INVITATION_LIST_LOADING: "SEARCH_INVITATION_LIST_LOADING",
  SEARCH_INVITATION_LIST_LOADED: "SEARCH_INVITATION_LIST_LOADED",
  SEARCH_INVITATION_LIST_ERROR: "SEARCH_INVITATION_LIST_ERROR",
  SEARCH_INVITATION_LIST_RESET: "SEARCH_INVITATION_LIST_RESET",

  // STUDENT_INVITATION_LIST_LOADING: "STUDENT_INVITATION_LIST_LOADING",
  // STUDENT_INVITATION_LIST_LOADED: "STUDENT_INVITATION_LIST_LOADED",
  // STUDENT_INVITATION_LIST_ERROR: "STUDENT_INVITATION_LIST_ERROR",
  // STUDENT_INVITATION_LIST_RESET: "STUDENT_INVITATION_LIST_RESET",

  // TEACHER_INVITATION_DELETE_LOADING: "TEACHER_INVITATION_DELETE_LOADING",
  // TEACHER_INVITATION_DELETE_SUCCESS: "TEACHER_INVITATION_DELETE_SUCCESS",
  // TEACHER_INVITATION_DELETE_RESET: "TEACHER_INVITATION_DELETE_RESET",
  // TEACHER_INVITATION_DELETE_ERROR: "TEACHER_INVITATION_DELETE_ERROR",

  // STUDENT_INVITATION_DELETE_LOADING: "STUDENT_INVITATION_DELETE_LOADING",
  // STUDENT_INVITATION_DELETE_SUCCESS: "STUDENT_INVITATION_DELETE_SUCCESS",
  // STUDENT_INVITATION_DELETE_RESET: "STUDENT_INVITATION_DELETE_RESET",
  // STUDENT_INVITATION_DELETE_ERROR: "STUDENT_INVITATION_DELETE_ERROR",

  // STUDENT_INVITATION_RESEND_LOADING: "STUDENT_INVITATION_RESEND_LOADING",
  // STUDENT_INVITATION_RESEND_SUCCESS: "STUDENT_INVITATION_RESEND_SUCCESS",
  // STUDENT_INVITATION_RESEND_RESET: "STUDENT_INVITATION_RESEND_RESET",
  // STUDENT_INVITATION_RESEND_ERROR: "STUDENT_INVITATION_RESEND_ERROR",

  // TEACHER_INVITATION_RESEND_LOADING: "TEACHER_INVITATION_RESEND_LOADING",
  // TEACHER_INVITATION_RESEND_SUCCESS: "TEACHER_INVITATION_RESEND_SUCCESS",
  // TEACHER_INVITATION_RESEND_RESET: "TEACHER_INVITATION_RESEND_RESET",
  // TEACHER_INVITATION_RESEND_ERROR: "TEACHER_INVITATION_RESEND_ERROR",

}