export const TeacherClassroomsListActionTypes = {

    TEACHER_CLASSROOMS_LIST_LOADING: "TEACHER_CLASSROOMS_LIST_LOADING",
    TEACHER_CLASSROOMS_LIST_LOADED: "TEACHER_CLASSROOMS_LIST_LOADED",
    TEACHER_CLASSROOMS_LIST_ERROR: "TEACHER_CLASSROOMS_LIST_ERROR",
    TEACHER_CLASSROOMS_LIST_RESET: "TEACHER_CLASSROOMS_LIST_RESET",


    TEACHER_CLASSROOMS_LIST_SORTBY_LOADING: "TEACHER_CLASSROOMS_LIST_SORTBY_LOADING",
    TEACHER_CLASSROOMS_LIST_SORTBY_LOADED: "TEACHER_CLASSROOMS_LIST_SORTBY_LOADED",
    TEACHER_CLASSROOMS_LIST_SORTBY_ERROR: "TEACHER_CLASSROOMS_LIST_SORTBY_ERROR",
    TEACHER_CLASSROOMS_LIST_SORTBY_RESET: "TEACHER_CLASSROOMS_LIST_SORTBY_RESET",

    TEACHER_CLASSROOMS_LIST_SEARCH_LOADING: "TEACHER_CLASSROOMS_LIST_SEARCH_LOADING",
    TEACHER_CLASSROOMS_LIST_SEARCH_LOADED: "TEACHER_CLASSROOMS_LIST_SEARCH_LOADED",
    TEACHER_CLASSROOMS_LIST_SEARCH_ERROR: "TEACHER_CLASSROOMS_LIST_SEARCH_ERROR",
    TEACHER_CLASSROOMS_LIST_SEARCH_RESET: "TEACHER_CLASSROOMS_LIST_SEARCH_RESET",

}