export const USERINFOTYPES = {
  GET_USER_INFO: "GET_USER_INFO",
  POST_USER_INFO: "POST_USER_INFO",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  DELETE_USER_INFO: "DELETE_USER_INFO",
  USER_INFO_SELECTION: "USER_INFO_SELECTION",
};

export const USER_INFO_LIST_AT = {
    IS_LOADING: 'IS_LOADING',
    LOADED: 'LOADED',
    USER_INFO_LIST:"USER_INFO_LIST",
    USER_INFO_EDIT: "USER_INFO_EDIT",
 
}
