export const STUDENTCLASSROOM = {
  GET_STUDENT_CLASSROOM_LIST:"GET_STUDENT_CLASSROOM_LIST",
  STUDENT_CLASSROOM_LIST_LOADING:"STUDENT_CLASSROOM_LIST_LOADING",
  STUDENT_CLASSROOM_LIST_RESET:"STUDENT_CLASSROOM_LIST_RESET",
  STUDENT_SEARCH_CLASSROOM_LIST:"STUDENT_SEARCH_CLASSROOM_LIST",
  STUDENT_SORT_CLASSROOM_LIST:"STUDENT_SORT_CLASSROOM_LIST",


  // Single Classroom info 
  GET_STUDENT_SINGLE_CLASSROOM:"GET_STUDENT_SINGLE_CLASSROOM",
  GET_STUDENT_SINGLE_CLASSROOM_LOADING:"GET_STUDENT_SINGLE_CLASSROOM_LOADING",
  GET_STUDENT_SINGLE_CLASSROOM_RESET:"GET_STUDENT_SINGLE_CLASSROOM_RESET",

  // get All Classroom Subjects
  GET_STUDENT_CLASSROOM_SUBJECTS:"GET_STUDENT_CLASSROOM_SUBJECTS",
  GET_STUDENT_CLASSROOM_SUBJECTS_LOADING:"GET_STUDENT_CLASSROOM_SUBJECTS_LOADING",
  GET_STUDENT_CLASSROOM_SUBJECTS_RESET:"GET_STUDENT_CLASSROOM_SUBJECTS_RESET",
  SORT_STUDENT_CLASSROOM_SUBJECTS:"SORT_STUDENT_CLASSROOM_SUBJECTS",
  SEARCH_STUDENT_CLASSROOM_SUBJECT:"SEARCH_STUDENT_CLASSROOM_SUBJECT"
}