export const STUDENTTYPE = {
  STUDENT_LOADING: "STUDENT_LOADING",
  STUDENT_LOADED: "STUDENT_LOADED",
  STUDENT_INVITE: "STUDENT_INVITE",
  STUDENT_INVITE_ERROR: "STUDENT_INVITE_ERROR",
  STUDENT_INVITE_ERROR_RESET: "STUDENT_INVITE_ERROR_RESET",
  STUDENT_INVITE_CREATE_RESET: "STUDENT_INVITE_CREATE_RESET",
  STUDENT_INVITE_LOADING: "STUDENT_INVITE_LOADING",
  STUDENT_EDIT: "STUDENT_EDIT",
  STUDENT_ID: "STUDENT_ID",
  STUDENT_HISTORY: "STUDENT_HISTORY",
  STUDENT_ERROR: "STUDENT_ERROR",
  GET_ERROR: "GET_ERROR",
  LOADING: "LOADING",


  STUDENT_MANUAL_INVITE_LOADING: "STUDENT_MANUAL_INVITE_LOADING",
  STUDENT_MANUAL_INVITE_LOADED: "STUDENT_MANUAL_INVITE_LOADED",
  STUDENT_MANUAL_INVITE_ERROR: "STUDENT_MANUAL_INVITE_ERROR",
  STUDENT_MANUAL_INVITE_RESET: "STUDENT_MANUAL_INVITE_RESET"
};
