export const HOLIDAYTYPES = {
  CREATE_HOLIDAY_LOADING:"CREATE_HOLIDAY_LOADING",
  CREATE_HOLIDAY_LOADED:"CREATE_HOLIDAY_LOADED",
  CREATE_HOLIDAY_ERROR:"CREATE_HOLIDAY_ERROR",
  CREATE_HOLIDAY_RESET:"CREATE_HOLIDAY_RESET",

  GET_HOLIDAY_LIST_LOADING:"GET_HOLIDAY_LIST_LOADING",
  GET_HOLIDAY_LIST_LOADED:"GET_HOLIDAY_LIST_LOADED",
  GET_HOLIDAY_LIST_ERROR:"GET_HOLIDAY_LIST_ERROR",
  GET_HOLIDAY_LIST_RESET:"GET_HOLIDAY_LIST_RESET",

  GET_SINGLE_HOLIDAY_LOADING:"GET_SINGLE_HOLIDAY_LOADING",
  GET_SINGLE_HOLIDAY_SUCCESS:"GET_SINGLE_HOLIDAY_SUCCESS",
  GET_SINGLE_HOLIDAY_ERROR:"GET_SINGLE_HOLIDAY_ERROR",
  GET_SINGLE_HOLIDAY_RESET:"GET_SINGLE_HOLIDAY_RESET",

  EDIT_HOLIDAY_LOADING:"EDIT_HOLIDAY_LOADING",
  EDIT_HOLIDAY_LOADED:"EDIT_HOLIDAY_LOADED",
  EDIT_HOLIDAY_ERROR:"EDIT_HOLIDAY_ERROR",
  EDIT_HOLIDAY_RESET:"EDIT_HOLIDAY_RESET",

  SEARCH_SORT_HOLIDAY:"SEARCH_SORT_HOLIDAY",
  CLASSROOM_FILTER_HOLIDAY:"CLASSROOM_FILTER_HOLIDAY",

  DELETE_HOLIDAY_LOADING:"DELETE_HOLIDAY_LOADING",
  DELETE_HOLIDAY_SUCCESS:"DELETE_HOLIDAY_SUCCESS",
  DELETE_HOLIDAY_RESET:"DELETE_HOLIDAY_RESET",
  DELETE_HOLIDAY_ERROR:"DELETE_HOLIDAY_ERROR",
}