export const APPOINTMENTTYPES = {
  //appointment list
  POST_APPOINTMENT_LOADING: "POST_APPOINTMENT_LOADING",
  POST_APPOINTMENT_SUCCESS: "POST_APPOINTMENT_SUCCESS",
  POST_APPOINTMENT_ERROR: "POST_APPOINTMENT_ERROR",
  POST_APPOINTMENT_RESET: "POST_APPOINTMENT_RESET",

  GET_APPOINTMENT_LIST_LOADING: "GET_APPOINTMENT_LIST_LOADING",
  GET_APPOINTMENT_LIST_SUCCESS: "GET_APPOINTMENT_LIST_SUCCESS",
  GET_APPOINTMENT_LIST_ERROR: "GET_APPOINTMENT_LIST_ERROR",
  GET_APPOINTMENT_LIST_RESET: "GET_APPOINTMENT_LIST_RESET",

  GET_SINGLE_APPOINTMENT_LOADING: "GET_SINGLE_APPOINTMENT_LOADING",
  GET_SINGLE_APPOINTMENT_SUCCESS: "GET_SINGLE_APPOINTMENT_SUCCESS",
  GET_SINGLE_APPOINTMENT_ERROR: "GET_SINGLE_APPOINTMENT_ERROR",
  GET_SINGLE_APPOINTMENT_RESET: "GET_SINGLE_APPOINTMENT_RESET",

  EDIT_APPOINTMENT_LOADING: "EDIT_APPOINTMENT_LOADING",
  EDIT_APPOINTMENT_SUCCESS: "EDIT_APPOINTMENT_SUCCESS",
  EDIT_APPOINTMENT_ERROR: "EDIT_APPOINTMENT_ERROR",
  EDIT_APPOINTMENT_RESET: "EDIT_APPOINTMENT_RESET",

  DELETE_APPOINTMENT_LIST_LOADING: "DELETE_APPOINTMENT_LIST_LOADING",
  DELETE_APPOINTMENT_LIST_SUCCESS: "DELETE_APPOINTMENT_LIST_SUCCESS",
  DELETE_APPOINTMENT_LIST_RESET: "DELETE_APPOINTMENT_LIST_RESET",
  DELETE_APPOINTMENT_LIST_ERROR: "DELETE_APPOINTMENT_LIST_ERROR",

  //Servicess

  POST_SERVICE_LOADING: "POST_SERVICE_LOADING",
  POST_SERVICE_SUCCESS: "POST_SERVICE_SUCCESS",
  POST_SERVICE_ERROR: "POST_SERVICE_ERROR",
  POST_SERVICE_RESET: "POST_SERVICE_RESET",

  GET_SERVICE_LIST_LOADING: "GET_SERVICE_LIST_LOADING",
  GET_SERVICE_LIST_SUCCESS: "GET_SERVICE_LIST_SUCCESS",
  GET_SERVICE_LIST_ERROR: "GET_SERVICE_LIST_ERROR",
  GET_SERVICE_LIST_RESET: "GET_SERVICE_LIST_RESET",

  GET_SINGLE_SERVICE_LOADING: "GET_SINGLE_SERVICE_LOADING",
  GET_SINGLE_SERVICE_SUCCESS: "GET_SINGLE_SERVICE_SUCCESS",
  GET_SINGLE_SERVICE_ERROR: "GET_SINGLE_SERVICE_ERROR",
  GET_SINGLE_SERVICE_RESET: "GET_SINGLE_SERVICE_RESET",


  EDIT_SERVICE_LOADING: "EDIT_SERVICE_LOADING",
  EDIT_SERVICE_SUCCESS: "EDIT_SERVICE_SUCCESS",
  EDIT_SERVICE_ERROR: "EDIT_SERVICE_ERROR",
  EDIT_SERVICE_RESET: "EDIT_SERVICE_RESET",

  DELETE_SERVICE_LOADING: "DELETE_SERVICE_LOADING",
  DELETE_SERVICE_SUCCESS: "DELETE_SERVICE_SUCCESS",
  DELETE_SERVICE_RESET: "DELETE_SERVICE_RESET",
  DELETE_SERVICE_ERROR: "DELETE_SERVICE_ERROR",

  //MAIN_CATEGORY

  POST_MAIN_CATEGORY_LOADING: "POST_MAIN_CATEGORY_LOADING",
  POST_MAIN_CATEGORY_SUCCESS: "POST_MAIN_CATEGORY_SUCCESS",
  POST_MAIN_CATEGORY_ERROR: "POST_MAIN_CATEGORY_ERROR",
  POST_MAIN_CATEGORY_RESET: "POST_MAIN_CATEGORY_RESET",

  GET_MAIN_CATEGORY_LIST_LOADING: "GET_MAIN_CATEGORY_LIST_LOADING",
  GET_MAIN_CATEGORY_LIST_SUCCESS: "GET_MAIN_CATEGORY_LIST_SUCCESS",
  GET_MAIN_CATEGORY_LIST_ERROR: "GET_MAIN_CATEGORY_LIST_ERROR",
  GET_MAIN_CATEGORY_LIST_RESET: "GET_MAIN_CATEGORY_LIST_RESET",

  GET_UNCATEGORY_LIST_LOADING: "GET_UNCATEGORY_LIST_LOADING",
  GET_UNCATEGORY_LIST_SUCCESS: "GET_UNCATEGORY_LIST_SUCCESS",
  GET_UNCATEGORY_LIST_ERROR: "GET_UNCATEGORY_LIST_ERROR",
  GET_UNCATEGORY_LIST_RESET: "  GET_UNCATEGORY_LIST_RESET",


  GET_SINGLE_MAIN_CATEGORY_LOADING: "GET_SINGLE_MAIN_CATEGORY_LOADING",
  GET_SINGLE_MAIN_CATEGORY_SUCCESS: "GET_SINGLE_MAIN_CATEGORY_SUCCESS",
  GET_SINGLE_MAIN_CATEGORY_ERROR: "GET_SINGLE_MAIN_CATEGORY_ERROR",
  GET_SINGLE_MAIN_CATEGORY_RESET: "GET_SINGLE_MAIN_CATEGORY_RESET",


  EDIT_MAIN_CATEGORY_LIST_LOADING: "EDIT_MAIN_CATEGORY_LIST_LOADING",
  EDIT_MAIN_CATEGORY_LIST_SUCCESS: "EDIT_MAIN_CATEGORY_LIST_SUCCESS",
  EDIT_MAIN_CATEGORY_LIST_ERROR: "EDIT_MAIN_CATEGORY_LIST_ERROR",
  EDIT_MAIN_CATEGORY__LIST_RESET: "EDIT_MAIN_CATEGORY_LIST_RESET",

  EDIT_MAIN_CATEGORY_DATA_LOADING: "EDIT_MAIN_CATEGORY_DATA_LOADING",
  EDIT_MAIN_CATEGORY_DATA_SUCCESS: "EDIT_MAIN_CATEGORY_DATA_SUCCESS",
  EDIT_MAIN_CATEGORY_DATA_ERROR: "EDIT_MAIN_CATEGORY_DATA_ERROR",
  EDIT_MAIN_CATEGORY__DATA_RESET: "EDIT_MAIN_CATEGORY_DATA_RESET",

  DELETE_MAIN_CATEGORY_LIST_LOADING: "DELETE_MAIN_CATEGORY_LIST_LOADING",
  DELETE_MAIN_CATEGORY_LIST_SUCCESS: "DELETE_MAIN_CATEGORY_LIST_SUCCESS",
  DELETE_MAIN_CATEGORY_LIST_RESET: "DELETE_MAIN_CATEGORY_LIST_RESET",
  DELETE_MAIN_CATEGORY_LIST_ERROR: "DELETE_MAIN_CATEGORY_LIST_ERROR",


  SORT_APPOINTMENT_LIST: "SORT_APPOINTMENT_LIST",

  SEARCH_APPOINTMENT_LIST: "SEARCH_APPOINTMENT_LIST",

  APPOINTMENT_STATUS: "APPOINTMENT_STATUS",

  // Booking Settings
  GET_BOOK_SETTING_LOADING: "GET_BOOK_SETTING_LOADING",
  GET_BOOK_SETTING_SUCCESS: "GET_BOOK_SETTING_SUCCESS",
  GET_BOOK_SETTING_ERROR: "GET_BOOK_SETTING_ERROR",
  GET_BOOK_SETTING_RESET: "GET_BOOK_SETTING_RESET",

  CREATE_BOOK_SETTING_LOADING: "CREATE_BOOK_SETTING_LOADING",
  CREATE_BOOK_SETTING_SUCCESS: "CREATE_BOOK_SETTING_SUCCESS",
  CREATE_BOOK_SETTING_ERROR: "CREATE_BOOK_SETTING_ERROR",
  CREATE_BOOK_SETTING_RESET: "CREATE_BOOK_SETTING_RESET",

  UPDATE_BOOK_SETTING_LOADING: "UPDATE_BOOK_SETTING_LOADING",
  UPDATE_BOOK_SETTING_SUCCESS: "UPDATE_BOOK_SETTING_SUCCESS",
  UPDATE_BOOK_SETTING_ERROR: "UPDATE_BOOK_SETTING_ERROR",
  UPDATE_BOOK_SETTING_RESET: "UPDATE_BOOK_SETTING_RESET",


  GET_BOOKING_LIST_LOADING: "GET_BOOKING_LIST_LOADING",
  GET_BOOKING_LIST_LOADED: "GET_BOOKING_LIST_LOADED",
  GET_BOOKING_LIST_ERROR: "GET_BOOKING_LIST_ERROR",
  GET_BOOKING_LIST_RESET: "GET_BOOKING_LIST_RESET",

  // ADMIN SIDE BOOKING LIST 
  // EDIT_BOOKING_LIST_LOADING: "EDIT_BOOKING_LIST_LOADING",
  // EDIT_BOOKING_LIST_LOADED: "EDIT_BOOKING_LIST_LOADED",
  // EDIT_BOOKING_LIST_ERROR: "EDIT_BOOKING_LIST_ERROR",
  // EDIT_BOOKING_LIST_RESET: "EDIT_BOOKING_LIST_RESET",

  // ADMIN SIDE BOOKING LIST 
  GET_ALL_SERVICES_LIST_LOADING: "GET_ALL_SERVICES_LIST_LOADING",
  GET_ALL_SERVICES_LIST_LOADED: "GET_ALL_SERVICES_LIST_LOADED",
  GET_ALL_SERVICES_LIST_ERROR: "GET_ALL_SERVICES_LIST_ERROR",
  GET_ALL_SERVICES_LIST_RESET: "GET_ALL_SERVICES_LIST_RESET",

  // ADMIN SIDE BOOKING LIST 
  GET_ALL_SLOTS_LOADING: "GET_ALL_SLOTS_LOADING",
  GET_ALL_SLOTS_LOADED: "GET_ALL_SLOTS_LOADED",
  GET_ALL_SLOTS_ERROR: "GET_ALL_SLOTS_ERROR",
  GET_ALL_SLOTS_RESET: "GET_ALL_SLOTS_RESET",

  //SERVICE LIST

  GET_BOOK_SERVICELIST_LOADING: "GET_BOOK_SERVICELIST_LOADING",
  GET_BOOK_SERVICELIST_SUCCESS: "GET_BOOK_SERVICELIST_SUCCESS",
  GET_BOOK_SERVICELIST_ERROR: "GET_BOOK_SERVICELIST_ERROR",

  CREATE_BOOK_SERVICELIST_LOADING: "CREATE_BOOK_SERVICELIST_LOADING",
  CREATE_BOOK_SERVICELIST_SUCCESS: "CREATE_BOOK_SERVICELIST_SUCCESS",
  CREATE_BOOK_SERVICELIST_ERROR: "CREATE_BOOK_SERVICELIST_ERROR",

  UPDATE_BOOK_SERVICELIST_LOADING: "UPDATE_BOOK_SERVICELIST_LOADING",
  UPDATE_BOOK_SERVICELIST_SUCCESS: "UPDATE_BOOK_SERVICELIST_SUCCESS",
  UPDATE_BOOK_SERVICELIST_ERROR: "UPDATE_BOOK_SERVICELIST_ERROR",



  EDIT_USER_APPOINTMENT_LOADING: "EDIT_USER_APPOINTMENT_LOADING",
  EDIT_USER_APPOINTMENT_SUCCESS: "EDIT_USER_APPOINTMENT_SUCCESS",
  EDIT_USER_APPOINTMENT_ERROR: "EDIT_USER_APPOINTMENT_ERROR",

  ADMIN_COUNT_APPOINTMENT_LOADING: "ADMIN_COUNT_APPOINTMENT_LOADING",
  ADMIN_COUNT_APPOINTMENT_SUCCESS: "ADMIN_COUNT_APPOINTMENT_SUCCESS",
  ADMIN_COUNT_APPOINTMENT_ERROR: "ADMIN_COUNT_APPOINTMENT_ERROR",


  EDIT_STATUS: "EDIT_STATUS",

  //Services PAGE

  GET_SERVICE_LIST_BY_CATEGOERY_LOADING: "GET_SERVICE_LIST_BY_CATEGOERY_LOADING",
  GET_SERVICE_LIST_BY_CATEGOERY_SUCCESS: "GET_SERVICE_LIST_BY_CATEGOERY_SUCCESS",
  GET_SERVICE_LIST_BY_CATEGOERY_ERROR: "GET_SERVICE_LIST_BY_CATEGOERY_ERROR",
  GET_SERVICE_LIST_BY_CATEGOERY_RESET: "GET_SERVICE_LIST_BY_CATEGOERY_RESET",

  SEARCH_SERVICE: "SEARCH_SERVICE",

  GET_MAIN_BUSINESS_CATEGORY_LOADING: "GET_MAIN_BUSINESS_CATEGORY_LOADING",
  GET_MAIN_BUSINESS_CATEGORY_SUCCESS: "GET_MAIN_BUSINESS_CATEGORY_SUCCESS",
  GET_MAIN_BUSINESS_CATEGORY_ERROR: "GET_MAIN_BUSINESS_CATEGORY_ERROR",
  GET_MAIN_BUSINESS_CATEGORY_RESET: "GET_MAIN_BUSINESS_CATEGORY_RESET",

  EDIT_MAIN_BUSINESS_CATEGORY_LOADING: "EDIT_MAIN_BUSINESS_CATEGORY_LOADING",
  EDIT_MAIN_BUSINESS_CATEGORY_SUCCESS: "EDIT_MAIN_BUSINESS_CATEGORY_SUCCESS",
  EDIT_MAIN_BUSINESS_CATEGORY_ERROR: "EDIT_MAIN_BUSINESS_CATEGORY_ERROR",
  EDIT_MAIN_BUSINESS_CATEGORY_RESET: "EDIT_MAIN_BUSINESS_CATEGORY_RESET",

  MULTI_DELETE_UNCAT_LOADING: "MULTI_DELETE_UNCAT_LOADING",
  MULTI_DELETE_UNCAT_SUCCESS: "MULTI_DELETE_UNCAT_SUCCESS",
  MULTI_DELETE_UNCAT_ERROR: "MULTI_DELETE_UNCAT_ERROR",
  MULTI_DELETE_UNCAT_RESET: "MULTI_DELETE_UNCAT_RESET",

  DELETE_CATEGORY_LOADING: "DELETE_CATEGORY_LOADING",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_ERROR: "DELETE_CATEGORY_ERROR",
  DELETE_CATEGORY_RESET: "MDELETE_CATEGORY_RESET",




  // CREATE_SERVICE_SLUG_LOADING: "CREATE_SERVICE_SLUG_LOADING"


  POST_COLLECTION_LOADING: "POST_COLLECTION_LOADING",
  POST_COLLECTION_SUCCESS: "POST_COLLECTION_SUCCESS",
  POST_COLLECTION_ERROR: "POST_COLLECTION_ERROR",
  POST_COLLECTION_RESET: "POST_COLLECTION_RESET",

  GET_COLLECTION_LOADING: "GET_COLLECTION_LOADING",
  GET_COLLECTION_SUCCESS: "GET_COLLECTION_SUCCESS",
  GET_COLLECTION_ERROR: "GET_COLLECTION_ERROR",
  GET_COLLECTION_RESET: "GET_COLLECTION_RESET",


  GET_SINGLE_COLLECTION_LOADING: "GET_SINGLE_COLLECTION_LOADING",
  GET_SINGLE_COLLECTION_SUCCESS: "GET_SINGLE_COLLECTION_SUCCESS",
  GET_SINGLE_COLLECTION_ERROR: "GET_SINGLE_COLLECTION_ERROR",
  GET_SINGLE_COLLECTION_RESET: "GET_SINGLE_COLLECTION_RESET",

  GET_SINGLE_COLLECTION_ENDUSER_LOADING: "GET_SINGLE_COLLECTION_ENDUSER_LOADING",
  GET_SINGLE_COLLECTION_ENDUSER_SUCCESS: "GET_SINGLE_COLLECTION_ENDUSER_SUCCESS",
  GET_SINGLE_COLLECTION_ENDUSER_ERROR: "GET_SINGLE_COLLECTION_ENDUSER_ERROR",
  GET_SINGLE_COLLECTION_ENDUSER_RESET: "GET_SINGLE_COLLECTION_ENDUSER_RESET",

  
  GET_SHOW_ON_HEADER_COLLECTION_LOADING: "GET_SHOW_ON_HEADER_COLLECTION_LOADING",
  GET_SHOW_ON_HEADER_COLLECTION_SUCCESS: "GET_SHOW_ON_HEADER_COLLECTION_SUCCESS",
  GET_SHOW_ON_HEADER_COLLECTION_ERROR: "GET_SHOW_ON_HEADER_COLLECTION_ERROR",
  GET_SHOW_ON_HEADER_COLLECTION_RESET: "GET_SHOW_ON_HEADER_COLLECTION_RESET",

  EDIT_COLLECTION_LOADING: "EDIT_COLLECTION_LOADING",
  EDIT_COLLECTION_SUCCESS: "EDIT_COLLECTION_SUCCESS",
  EDIT_COLLECTION_ERROR: "EDIT_COLLECTION_ERROR",
  EDIT_COLLECTION_RESET: "EDIT_COLLECTION_RESET",

  GET_MAIN_BUSINESS_COLLECTION_LOADING: "GET_MAIN_BUSINESS_COLLECTION_LOADING",
  GET_MAIN_BUSINESS_COLLECTION_SUCCESS: "GET_MAIN_BUSINESS_COLLECTION_SUCCESS",
  GET_MAIN_BUSINESS_COLLECTION_ERROR: "GET_MAIN_BUSINESS_COLLECTION_ERROR",
  GET_MAIN_BUSINESS_COLLECTION_RESET: "GET_MAIN_BUSINESS_COLLECTION_RESET",

  EDIT_MAIN_BUSINESS_COLLECTION_LOADING: "EDIT_MAIN_BUSINESS_COLLECTION_LOADING",
  EDIT_MAIN_BUSINESS_COLLECTION_SUCCESS: "EDIT_MAIN_BUSINESS_COLLECTION_SUCCESS",
  EDIT_MAIN_BUSINESS_COLLECTION_ERROR: "EDIT_MAIN_BUSINESS_COLLECTION_ERROR",
  EDIT_MAIN_BUSINESS_COLLECTION_RESET: "EDIT_MAIN_BUSINESS_COLLECTION_RESET",

  DELETE_COLLECTION_LOADING: "DELETE_COLLECTION_LOADING",
  DELETE_COLLECTION_SUCCESS: "DELETE_COLLECTION_SUCCESS",
  DELETE_COLLECTION_ERROR: "DELETE_COLLECTION_ERROR",
  DELETE_COLLECTION_RESET: "DELETE_COLLECTION_RESET",

  // USER SIDE BOOKING FORM ON BOOKING BUTTON
  BOOKING_FORM_ON_BOOKING_BUTTON_LOADING: "BOOKING_FORM_ON_BOOKING_BUTTON_LOADING",
  BOOKING_FORM_ON_BOOKING_BUTTON_LOADED: "BOOKING_FORM_ON_BOOKING_BUTTON_LOADED",
  BOOKING_FORM_ON_BOOKING_BUTTON_ERROR: "BOOKING_FORM_ON_BOOKING_BUTTON_ERROR",
  BOOKING_FORM_ON_BOOKING_BUTTON_RESET: "BOOKING_FORM_ON_BOOKING_BUTTON_RESET",
  // GET FOR DISABLE BUTTON
  GET_DISABLE_BUTTON_DATA_LOADING: "GET_DISABLE_BUTTON_DATA_LOADING",
  GET_DISABLE_BUTTON_DATA_LOADED: "GET_DISABLE_BUTTON_DATA_LOADED",
  GET_DISABLE_BUTTON_DATA_ERROR: "GET_DISABLE_BUTTON_DATA_ERROR",
  GET_DISABLE_BUTTON_DATA_RESET: "GET_DISABLE_BUTTON_DATA_RESET",

    // PATCH FOR DISABLE BUTTON
    PATCH_DISABLE_BUTTON_DATA_LOADING: "PATCH_DISABLE_BUTTON_DATA_LOADING",
    PATCH_DISABLE_BUTTON_DATA_LOADED: "PATCH_DISABLE_BUTTON_DATA_LOADED",
    PATCH_DISABLE_BUTTON_DATA_ERROR: "PATCH_DISABLE_BUTTON_DATA_ERROR",
    PATCH_DISABLE_BUTTON_DATA_RESET: "PATCH_DISABLE_BUTTON_DATA_RESET"
}