export const instituteActionTypes = {
    INS_DETAIL_LOADING: "INS_DETAIL_LOADING",
    INS_DETAIL_LOADED: "INS_DETAIL_LOADED",
    INS_DETAIL_LOADING_ERROR: "INS_DETAIL_LOADING_ERROR",

    INS_DETAIL_COUNT_LOADING: "INS_DETAIL_COUNT_LOADING",
    INS_DETAIL_COUNT_LOADED: "INS_DETAIL_COUNT_LOADED",
    INS_DETAIL_COUNT_LOADING_ERROR: "INS_DETAIL_COUNT_LOADING_ERROR",

    SUBDOMAIN_CHECK_AVAIBILITY_LOADING: "SUBDOMAIN_CHECK_AVAIBILITY_LOADING",
    SUBDOMAIN_CHECK_AVAIBILITY_LOADED: "SUBDOMAIN_CHECK_AVAIBILITY_LOADED",
    SUBDOMAIN_CHECK_AVAIBILITY_RESET: "SUBDOMAIN_CHECK_AVAIBILITY_RESET",

    SUBDOMAIN_UPDATE_AVAIBILITY_LOADING: "SUBDOMAIN_UPDATE_AVAIBILITY_LOADING",
    SUBDOMAIN_UPDATE_AVAIBILITY_LOADED: "SUBDOMAIN_UPDATE_AVAIBILITY_LOADED",
    SUBDOMAIN_UPDATE_AVAIBILITY_RESET: "SUBDOMAIN_UPDATE_AVAIBILITY_RESET"
}