export const SIGNUP_CUSTOMER_OTP_LOADING = "SIGNUP_CUSTOMER_OTP_LOADING";
export const SIGNUP_CUSTOMER_OTP_SUCCESS = "SIGNUP_CUSTOMER_OTP_SUCCESS";
export const SIGNUP_CUSTOMER_OTP_FAIL = "SIGNUP_CUSTOMER_OTP_FAIL";
export const SIGNUP_CUSTOMER_OTP_RESET = "SIGNUP_CUSTOMER_OTP_RESET"

export const SIGNUP_CUSTOMER_LOADING = "SIGNUP_CUSTOMER_LOADING";
export const SIGNUP_CUSTOMER_SUCCESS = "SIGNUP_CUSTOMER_SUCCESS";
export const SIGNUP_CUSTOMER_FAIL = "SIGNUP_CUSTOMER_FAIL";
export const SIGNUP_CUSTOMER_RESET = "SIGNUP_CUSTOMER_RESET";

export const LOGIN_CUSTOMER_LOADING = "LOGIN_CUSTOMER_LOADING";
export const LOGIN_CUSTOMER_SUCCESS = "LOGIN_CUSTOMER_SUCCESS";
export const LOGIN_CUSTOMER_FAIL = "LOGIN_CUSTOMER_FAIL";
export const LOGIN_CUSTOMER_RESET = "LOGIN_CUSTOMER_RESET"

export const SAVED_CUSTOMER_LOADING = "SAVED_CUSTOMER_LOADING";
export const SAVED_CUSTOMER_SUCCESS = "SAVED_CUSTOMER_SUCCESS";
export const SAVED_CUSTOMER_FAIL = "SAVED_CUSTOMER_FAIL";

export const AuthActionTypes = {
  SIGNUP_CUSTOMER_OTP_LOADING: "SIGNUP_CUSTOMER_OTP_LOADING",
  SIGNUP_CUSTOMER_OTP_SUCCESS: "SIGNUP_CUSTOMER_OTP_SUCCESS",
  SIGNUP_CUSTOMER_OTP_FAIL: "SIGNUP_CUSTOMER_OTP_FAIL",
  SIGNUP_CUSTOMER_OTP_RESET: "SIGNUP_CUSTOMER_OTP_RESET",
  SIGNUP_CUSTOMER_LOADING: "SIGNUP_CUSTOMER_LOADING",
  SIGNUP_CUSTOMER_SUCCESS: "SIGNUP_CUSTOMER_SUCCESS",
  SIGNUP_CUSTOMER_FAIL: "SIGNUP_CUSTOMER_FAIL",
  SIGNUP_CUSTOMER_RESET: "SIGNUP_CUSTOMER_RESET",
  LOGIN_CUSTOMER_LOADING: "LOGIN_CUSTOMER_LOADING",
  LOGIN_CUSTOMER_SUCCESS: "LOGIN_CUSTOMER_SUCCESS",
  LOGIN_CUSTOMER_FAIL: "LOGIN_CUSTOMER_FAIL",
  LOGIN_CUSTOMER_RESET: "LOGIN_CUSTOMER_RESET",
  SAVED_CUSTOMER_LOADING: "SAVED_CUSTOMER_LOADING",
  SAVED_CUSTOMER_SUCCESS: "SAVED_CUSTOMER_SUCCESS",
  SAVED_CUSTOMER_FAIL: "SAVED_CUSTOMER_FAIL",
}
