export const ADMIN_ORDER_LIST_LOADING = "ADMIN_ORDER_LIST_LOADING";
export const ADMIN_ORDER_LIST_SUCCESS = "ADMIN_ORDER_LIST_SUCCESS";
export const ADMIN_ORDER_LIST_FAIL = "ADMIN_ORDER_LIST_FAIL";

export const CHANGE_ORDER_STATUS_LOADING = "CHANGE_ORDER_STATUS_LOADING";
export const CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";
export const CHANGE_ORDER_STATUS_FAIL = "CHANGE_ORDER_STATUS_FAIL";

export const UPDATE_ORDER_STATUS_LOADING = "UPDATE_ORDER_STATUS_LOADING";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_REJECT = "UPDATE_ORDER_STATUS_REJECT";

export const CUSTOMER_CART_LOADING = "CUSTOMER_CART_LOADING";
export const CUSTOMER_CART_SUCCESS = "CUSTOMER_CART_LIST_SUCCESS";
export const CUSTOMER_CART_FAIL = "CUSTOMER_CART_LIST_FAIL";

export const READ_CART_LOADING = "READ_CART_LOADING";
export const READ_CART_SUCCESS = "READ_CART_SUCCESS";
export const READ_CART_FAIL = "READ_CART_FAIL";

export const ADDRESS_LIST_LOADING = "ADDRESS_LIST_LOADING";
export const ADDRESS_LIST_SUCCESS = "ADDRESS_LIST_SUCCESS";
export const ADDRESS_LIST_FAIL = "ADDRESS_LIST_FAIL";

export const ADDRESS_OPERATIONS_LOADING = "ADDRESS_OPERATIONS_LOADING";
export const ADDRESS_OPERATIONS_SUCCESS = "ADDRESS_OPERATIONS_SUCCESS";
export const ADDRESS_OPERATIONS_FAIL = "ADDRESS_OPERATIONS_FAIL";

export const CREATE_CART_ORDER_LOADING = "CREATE_CART_ORDER_LOADING";
export const CREATE_CART_ORDER_SUCCESS = "CREATE_CART_ORDER_SUCCESS";
export const CREATE_CART_ORDER_FAIL = "CREATE_CART_ORDER_FAIL";

export const CUSTOMER_ORDER_DETAIL_LOADING = "CUSTOMER_ORDER_DETAIL_LOADING";
export const CUSTOMER_ORDER_DETAIL_SUCCESS = "CUSTOMER_ORDER_DETAIL_SUCCESS";
export const CUSTOMER_ORDER_DETAIL_FAIL = "CUSTOMER_ORDER_DETAIL_FAIL";
export const CUSTOMER_ORDER_DETAIL_RESET = "CUSTOMER_ORDER_DETAIL_RESET";

export const CUSTOMER_ORDER_LIST_LOADING = "CUSTOMER_ORDER_LIST_LOADING";
export const CUSTOMER_ORDER_LIST_SUCCESS = "CUSTOMER_ORDER_LIST_SUCCESS";
export const CUSTOMER_ORDER_LIST_FAIL = "CUSTOMER_ORDER_LIST_FAIL";

export const ADD_BANK_ACCOUNT_LOADING = "ADD_BANK_ACCOUNT_LOADING";
export const ADD_BANK_ACCOUNT_SUCCESS = "ADD_BANK_ACCOUNT_SUCCESS";
export const ADD_BANK_ACCOUNT_FAIL = "ADD_BANK_ACCOUNT_FAIL";
export const ADD_BANK_ACCOUNT_RESET = "ADD_BANK_ACCOUNT_RESET";


export const CREATE_RAZORPAY_ACCOUNT_LOADING = "CREATE_RAZORPAY_ACCOUNT_LOADING";
export const CREATE_RAZORPAY_ACCOUNT_SUCCESS = "CREATE_RAZORPAY_ACCOUNT_SUCCESS";
export const CREATE_RAZORPAY_ACCOUNT_FAIL = "CREATE_RAZORPAY_ACCOUNT_FAIL";
export const CREATE_RAZORPAY_ACCOUNT_RESET = "CREATE_RAZORPAY_ACCOUNT_RESET";

export const CREATE_RAZORPAY_ORDER_LOADING = "CREATE_RAZORPAY_ORDER_LOADING";
export const CREATE_RAZORPAY_ORDER_SUCCESS = "CREATE_RAZORPAY_ORDER_SUCCESS";
export const CREATE_RAZORPAY_ORDER_FAIL = "CREATE_RAZORPAY_ORDER_FAIL";

export const GET_RAZORPAY_ORDER_LOADING = "GET_RAZORPAY_ORDER_LOADING";
export const GET_RAZORPAY_ORDER_SUCCESS = "GET_RAZORPAY_ORDER_SUCCESS";
export const GET_RAZORPAY_ORDER_FAIL = "GET_RAZORPAY_ORDER_FAIL";

export const PAYMENT_CALLBACK_RAZORPAY_LOADING = "PAYMENT_CALLBACK_RAZORPAY_LOADING";
export const PAYMENT_CALLBACK_RAZORPAY_SUCCESS = "PAYMENT_CALLBACK_RAZORPAY_SUCCESS";
export const PAYMENT_CALLBACK_RAZORPAY_FAIL = "PAYMENT_CALLBACK_RAZORPAY_FAIL";

export const CUSTOMER_CANCEL_ORDER_LOADING = "CUSTOMER_CANCEL_ORDER_LOADING";
export const CUSTOMER_CANCEL_ORDER_SUCCESS = "CUSTOMER_CANCEL_ORDER_SUCCESS";
export const CUSTOMER_CANCEL_ORDER_FAIL = "CUSTOMER_CANCEL_ORDER_FAIL";

export const ADDRESS_LIST_OPERATIONS_CREATE = "ADDRESS_LIST_OPERATIONS_CREATE";
export const ADDRESS_LIST_OPERATIONS_EDIT = "ADDRESS_LIST_OPERATIONS_EDIT";
export const ADDRESS_LIST_OPERATIONS_DELETE = "ADDRESS_LIST_OPERATIONS_DELETE";
export const ADDRESS_OPERATIONS_RESET = "ADDRESS_OPERATIONS_RESET";

export const ProductActionTypes = {
  GET_ORDER_LIST_BY_STATUS_LOADING: "GET_ORDER_LIST_BY_STATUS_LOADING",
  GET_ORDER_LIST_BY_STATUS_SUCCESS: "GET_ORDER_LIST_BY_STATUS_SUCCESS",
  GET_ORDER_LIST_BY_STATUS_ERROR: "GET_ORDER_LIST_BY_STATUS_ERROR",
  GET_ORDER_LIST_BY_STATUS_RESET: "GET_ORDER_LIST_BY_STATUS_RESET",
};

export const CartActionTypes = {
  ADMIN_ORDER_LIST_LOADING: "ADMIN_ORDER_LIST_LOADING",
  ADMIN_ORDER_LIST_SUCCESS: "ADMIN_ORDER_LIST_SUCCESS",
  ADMIN_ORDER_LIST_FAIL: "ADMIN_ORDER_LIST_FAIL",
  ADMIN_ORDER_LIST_RESET: "ADMIN_ORDER_LIST_RESET",

  GET_ORDER_LIST_BY_STATUS: "GET_ORDER_LIST_BY_STATUS",

  SEARCH_ORDER_ADMINLIST: "SEARCH_ORDER_ADMINLIST",

  GET_ORDER_LIST_BY_DATE: "GET_ORDER_LIST_BY_DATE",

  GET_ORDER_LIST_SORTBY_LOADING: "GET_ORDER_LIST_SORTBY_LOADING",
  GET_ORDER_LIST_SORTBY: "GET_ORDER_LIST_SORTBY",

  CHANGE_ORDER_STATUS_LOADING: "CHANGE_ORDER_STATUS_LOADING",
  CHANGE_ORDER_STATUS_SUCCESS: "CHANGE_ORDER_STATUS_SUCCESS",
  CHANGE_ORDER_STATUS_FAIL: "CHANGE_ORDER_STATUS_FAIL",
  CUSTOMER_CART_LOADING: "CUSTOMER_CART_LOADING",
  CUSTOMER_CART_SUCCESS: "CUSTOMER_CART_LIST_SUCCESS",
  CUSTOMER_CART_FAIL: "CUSTOMER_CART_LIST_FAIL",
  CUSTOMER_CART_RESET: "CUSTOMER_CART_LIST_RESET",
  READ_CART_LOADING: "READ_CART_LOADING",
  READ_CART_SUCCESS: "READ_CART_SUCCESS",
  READ_CART_FAIL: "READ_CART_FAIL",
  ADDRESS_LIST_LOADING: "ADDRESS_LIST_LOADING",
  ADDRESS_LIST_SUCCESS: "ADDRESS_LIST_SUCCESS",
  ADDRESS_LIST_FAIL: "ADDRESS_LIST_FAIL",
  ADDRESS_OPERATIONS_LOADING: "ADDRESS_OPERATIONS_LOADING",
  ADDRESS_OPERATIONS_SUCCESS: "ADDRESS_OPERATIONS_SUCCESS",
  ADDRESS_OPERATIONS_FAIL: "ADDRESS_OPERATIONS_FAIL",
  CREATE_CART_ORDER_LOADING: "CREATE_CART_ORDER_LOADING",
  CREATE_CART_ORDER_SUCCESS: "CREATE_CART_ORDER_SUCCESS",
  CREATE_CART_ORDER_FAIL: "CREATE_CART_ORDER_FAIL",
  CUSTOMER_ORDER_DETAIL_LOADING: "CUSTOMER_ORDER_DETAIL_LOADING",
  CUSTOMER_ORDER_DETAIL_SUCCESS: "CUSTOMER_ORDER_DETAIL_SUCCESS",
  CUSTOMER_ORDER_DETAIL_FAIL: "CUSTOMER_ORDER_DETAIL_FAIL",
  CUSTOMER_ORDER_DETAIL_RESET: "CUSTOMER_ORDER_DETAIL_RESET",

  CUSTOMER_ORDER_LIST_LOADING: "CUSTOMER_ORDER_LIST_LOADING",
  CUSTOMER_ORDER_LIST_SUCCESS: "CUSTOMER_ORDER_LIST_SUCCESS",
  CUSTOMER_ORDER_LIST_FAIL: "CUSTOMER_ORDER_LIST_FAIL",
  ADD_BANK_ACCOUNT_LOADING: "ADD_BANK_ACCOUNT_LOADING",
  ADD_BANK_ACCOUNT_SUCCESS: "ADD_BANK_ACCOUNT_SUCCESS",
  ADD_BANK_ACCOUNT_FAIL: "ADD_BANK_ACCOUNT_FAIL",
  ADD_BANK_ACCOUNT_RESET: "ADD_BANK_ACCOUNT_RESET",
  CREATE_RAZORPAY_ACCOUNT_LOADING: "CREATE_RAZORPAY_ACCOUNT_LOADING",
  CREATE_RAZORPAY_ACCOUNT_SUCCESS: "CREATE_RAZORPAY_ACCOUNT_SUCCESS",
  CREATE_RAZORPAY_ACCOUNT_FAIL: "CREATE_RAZORPAY_ACCOUNT_FAIL",
  CREATE_RAZORPAY_ACCOUNT_RESET: "CREATE_RAZORPAY_ACCOUNT_RESET",
  CREATE_RAZORPAY_ORDER_LOADING: "CREATE_RAZORPAY_ORDER_LOADING",
  CREATE_RAZORPAY_ORDER_SUCCESS: "CREATE_RAZORPAY_ORDER_SUCCESS",
  CREATE_RAZORPAY_ORDER_FAIL: "CREATE_RAZORPAY_ORDER_FAIL",
  GET_RAZORPAY_ORDER_LOADING: "GET_RAZORPAY_ORDER_LOADING",
  GET_RAZORPAY_ORDER_SUCCESS: "GET_RAZORPAY_ORDER_SUCCESS",
  GET_RAZORPAY_ORDER_FAIL: "GET_RAZORPAY_ORDER_FAIL",
  PAYMENT_CALLBACK_RAZORPAY_LOADING: "PAYMENT_CALLBACK_RAZORPAY_LOADING",
  PAYMENT_CALLBACK_RAZORPAY_SUCCESS: "PAYMENT_CALLBACK_RAZORPAY_SUCCESS",
  PAYMENT_CALLBACK_RAZORPAY_FAIL: "PAYMENT_CALLBACK_RAZORPAY_FAIL",
  CUSTOMER_CANCEL_ORDER_LOADING: "CUSTOMER_CANCEL_ORDER_LOADING",
  CUSTOMER_CANCEL_ORDER_SUCCESS: "CUSTOMER_CANCEL_ORDER_SUCCESS",
  CUSTOMER_CANCEL_ORDER_FAIL: "CUSTOMER_CANCEL_ORDER_FAIL",
  ADDRESS_LIST_OPERATIONS_CREATE: "ADDRESS_LIST_OPERATIONS_CREATE",
  ADDRESS_LIST_OPERATIONS_EDIT: "ADDRESS_LIST_OPERATIONS_EDIT",
  ADDRESS_LIST_OPERATIONS_DELETE: "ADDRESS_LIST_OPERATIONS_DELETE",
  ADDRESS_OPERATIONS_RESET: "ADDRESS_OPERATIONS_RESET",

  ADD_TO_CART_POST_LOADING: "ADD_TO_CART_POST_LOADING",
  ADD_TO_CART_POST_LOADED: "ADD_TO_CART_POST_LOADED",
  ADD_TO_CART_POST_ERROR: 'ADD_TO_CART_POST_ERROR',
  ADD_TO_CART_POST_RESET: 'ADD_TO_CART_POST_RESET',

  ADD_TO_CART_GET_LOADING: "ADD_TO_CART_GET_LOADING",
  ADD_TO_CART_GET_LOADED: "ADD_TO_CART_GET_LOADED",
  ADD_TO_CART_GET_ERROR: 'ADD_TO_CART_GET_ERROR',

  ADD_TO_CART_PATCH_LOADING: "ADD_TO_CART_PATCH_LOADING",
  ADD_TO_CART_PATCH_LOADED: "ADD_TO_CART_PATCH_LOADED",
  ADD_TO_CART_PATCH_ERROR: 'ADD_TO_CART_PATCH_ERROR',

  CART_PATCH_LOADING: "CART_PATCH_LOADING",
  CART_PATCH_LOADED: "CART_PATCH_LOADED",
  CART_PATCH_ERROR: 'CART_PATCH_ERROR',


  UPDATE_ORDER_STATUS_LOADING: "UPDATE_ORDER_STATUS_LOADING",
  UPDATE_ORDER_STATUS_SUCCESS: "UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_REJECT: "UPDATE_ORDER_STATUS_REJECT",

  GET_All_CUSTOMER_ORDER_LOADING: "GET_All_CUSTOMER_ORDER_LOADING",
  GET_All_CUSTOMER_ORDER_SUCCESS: "GET_All_CUSTOMER_ORDER_SUCCESS",
  GET_All_CUSTOMER_ORDER_ERROR: "GET_All_CUSTOMER_ORDER_ERROR",

  GET_SINGLE_ORDER_LOADING: "GET_SINGLE_ORDER_LOADING",
  GET_SINGLE_ORDER_SUCCESS: " GET_SINGLE_ORDER_SUCCESS",
  GET_SINGLE_ORDER_ERROR: "GET_SINGLE__ORDER_ERROR",

  UPDATE_ORDER_STATUS_BY_CUSTOMER_LOADING: "UPDATE_ORDER_STATUS_BY_CUSTOMER_LOADING",
  UPDATE_ORDER_STATUS_BY_CUSTOMER_SUCCESS: "UPDATE_ORDER_STATUS_BY_CUSTOMER_SUCCESS",
  UPDATE_ORDER_STATUS_BY_CUSTOMER_ERROR: "UPDATE_ORDER_STATUS_BY_CUSTOMER_ERROR",
  UPDATE_ORDER_STATUS_BY_CUSTOMER_RESET: "UPDATE_ORDER_STATUS_BY_CUSTOMER_RESET",

  // CANCEL_ALL_ORDER_CUSTOMER_LOADING: "CANCEL_ALL_ORDER_CUSTOMER_LOADING",
  // CANCEL_ALL_ORDER_CUSTOMER_SUCCESS: "CANCEL_ALL_ORDER_CUSTOMER_SUCCESS",
  // CANCEL_ALL_ORDER_CUSTOMER_ERROR: "CANCEL_ALL_ORDER_CUSTOMER_ERROR",
  // CANCEL_ALL_ORDER_CUSTOMER_RESET: "CANCEL_ALL_ORDER_CUSTOMER_RESET",

  GET_SHIPPING_DETAILS_LOADING: "GET_SHIPPING_DETAILS_LOADING",
  GET_SHIPPING_DETAILS_LOADED: "GET_SHIPPING_DETAILS_LOADED",
  GET_SHIPPING_DETAILS_RESET: "GET_SHIPPING_DETAILS_RESET",

  CART_QUANTITY_LOADING: "CART_QUANTITY_LOADING"

}

export const subOrderActionType = {
  GET_ITEM_SUBORDERD_LOADING: "GET_ITEM_SUBORDERD_LOADING",
  GET_ITEM_SUBORDERD_LOADED: "GET_ITEM_SUBORDERD_LOADED",
  UPDATE_SUBORDERD_SHIP_LOADING: "UPDATE_SUBORDERD_SHIP_LOADING",
  UPDATE_SUBORDERD_SHIP_LOADED: "UPDATE_SUBORDERD_SHIP_LOADED",
  GET_SHIP_ITEM_LOADING: "GET_SHIP_ITEM_LOADING",
  GET_SHIP_ITEM_LOADED: "GET_SHIP_ITEM_LOADED",
  UPDATE_FAIL_DELIVR_SUBORDER_LOADED: "UPDATE_FAIL_DELIVR_SUBORDER_LOADED",
  UPDATE_FAIL_DELIVR_SUBORDER_LOADING: "UPDATE_FAIL_DELIVR_SUBORDER_LOADING",

  GET_FAIL_ITEM_LOADING: "GET_FAIL_ITEM_LOADING",
  GET_FAIL_ITEM_LOADED: "GET_FAIL_ITEM_LOADED",
  GET_DELIVER_ITEM_LOADING: "GET_DELIVER_ITEM_LOADING",
  GET_DELIVER_ITEM_LOADED: "GET_DELIVER_ITEM_LOADED",

  POST_SHIPPING_PARTNER_LOADING:"POST_SHIPPING_PARTNER_LOADING",
  POST_SHIPPING_PARTNER_LOADED:"POST_SHIPPING_PARTNER_LOADED"
}
