export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';
export const GET_CART_LOADING = 'GET_CART_LOADING';

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const ADD_TO_CART_LOADING = 'ADD_TO_CART_LOADING';

export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';
export const REMOVE_FROM_CART_LOADING = 'REMOVE_FROM_CART_LOADING';

export const EDIT_CART_SUCCESS = 'EDIT_CART_SUCCESS';
export const EDIT_CART_FAIL = 'EDIT_CART_FAIL';
export const EDIT_CART_LOADING = 'EDIT_CART_LOADING';

export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL';
export const GET_WISHLIST_LOADING = 'GET_WISHLIST_LOADING';

export const GET_SAVE_FOR_LATER_SUCCESS = 'GET_SAVE_FOR_LATER_SUCCESS';
export const GET_SAVE_FOR_LATER_FAIL = 'GET_SAVE_FOR_LATER_FAIL';
export const GET_SAVE_FOR_LATER_LOADING = 'GET_SAVE_FOR_LATER_LOADING';

export const CartListActionTypes = {
  GET_CART_SUCCESS: 'GET_CART_SUCCESS',
  GET_CART_FAIL: 'GET_CART_FAIL',
  GET_CART_LOADING: 'GET_CART_LOADING',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAIL: 'ADD_TO_CART_FAIL',
  ADD_TO_CART_LOADING: 'ADD_TO_CART_LOADING',
  REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
  REMOVE_FROM_CART_FAIL: 'REMOVE_FROM_CART_FAIL',
  REMOVE_FROM_CART_LOADING: 'REMOVE_FROM_CART_LOADING',
  EDIT_CART_SUCCESS: 'EDIT_CART_SUCCESS',
  EDIT_CART_FAIL: 'EDIT_CART_FAIL',
  EDIT_CART_LOADING: 'EDIT_CART_LOADING',
  GET_WISHLIST_SUCCESS: 'GET_WISHLIST_SUCCESS',
  GET_WISHLIST_FAIL: 'GET_WISHLIST_FAIL',
  GET_WISHLIST_LOADING: 'GET_WISHLIST_LOADING',
  GET_SAVE_FOR_LATER_SUCCESS: 'GET_SAVE_FOR_LATER_SUCCESS',
  GET_SAVE_FOR_LATER_FAIL: 'GET_SAVE_FOR_LATER_FAIL',
  GET_SAVE_FOR_LATER_LOADING: 'GET_SAVE_FOR_LATER_LOADING',
}