export const GET_CATEGORY_LIST_LOADING = 'GET_CATEGORY_LIST_LOADING';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL';

export const GET_SUB_CATEGORY_LIST_LOADING = 'GET_SUB_CATEGORY_LIST_LOADING';
export const GET_SUB_CATEGORY_LIST_SUCCESS = 'GET_SUB_CATEGORY_LIST_SUCCESS';
export const GET_SUB_CATEGORY_LIST_FAIL = 'GET_SUB_CATEGORY_LIST_FAIL';

export const GET_SUB_SUB_CATEGORY_LIST_LOADING = 'GET_SUB_SUB_CATEGORY_LIST_LOADING';
export const GET_SUB_SUB_CATEGORY_LIST_SUCCESS = 'GET_SUB_SUB_CATEGORY_LIST_SUCCESS';
export const GET_SUB_SUB_CATEGORY_LIST_FAIL = 'GET_SUB_SUB_CATEGORY_LIST_FAIL';

export const CategoriesActionTypes = {
  GET_CATEGORY_LIST_LOADING: 'GET_CATEGORY_LIST_LOADING',
  GET_CATEGORY_LIST_SUCCESS: 'GET_CATEGORY_LIST_SUCCESS',
  GET_CATEGORY_LIST_FAIL: 'GET_CATEGORY_LIST_FAIL',
  GET_SUB_CATEGORY_LIST_LOADING: 'GET_SUB_CATEGORY_LIST_LOADING',
  GET_SUB_CATEGORY_LIST_SUCCESS: 'GET_SUB_CATEGORY_LIST_SUCCESS',
  GET_SUB_CATEGORY_LIST_FAIL: 'GET_SUB_CATEGORY_LIST_FAIL',
  GET_SUB_SUB_CATEGORY_LIST_LOADING: 'GET_SUB_SUB_CATEGORY_LIST_LOADING',
  GET_SUB_SUB_CATEGORY_LIST_SUCCESS: 'GET_SUB_SUB_CATEGORY_LIST_SUCCESS',
  GET_SUB_SUB_CATEGORY_LIST_FAIL: 'GET_SUB_SUB_CATEGORY_LIST_FAIL'
}