export const CREATE_COLLECTION_LOADING = "CREATE_COLLECTION_LOADING";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_FAIL = "CREATE_COLLECTION_FAIL";

export const GET_COLLECTION_LIST_LOADING = "GET_COLLECTION_LIST_LOADING";
export const GET_COLLECTION_LIST_SUCCESS = "GET_COLLECTION_LIST_SUCCESS";
export const GET_COLLECTION_LIST_FAIL = "GET_COLLECTION_LIST_FAIL";

export const GET_COLLECTION_DETAILS_LOADING = "GET_COLLECTION_DETAILS_LOADING";
export const GET_COLLECTION_DETAILS_SUCCESS = "GET_COLLECTION_DETAILS_SUCCESS";
export const GET_COLLECTION_DETAILS_FAIL = "GET_COLLECTION_DETAILS_FAIL";

export const EDIT_COLLECTION_LOADING = "EDIT_COLLECTION_LOADING";
export const EDIT_COLLECTION_SUCCESS = "EDIT_COLLECTION_SUCCESS";
export const EDIT_COLLECTION_FAIL = "EDIT_COLLECTION_FAIL";

export const EDIT_MULTI_COLLECTION_LOADING = "EDIT_MULTI_COLLECTION_LOADING";
export const EDIT_MULTI_COLLECTION_SUCCESS = "EDIT_MULTI_COLLECTION_SUCCESS";
export const EDIT_MULTI_COLLECTION_FAIL = "EDIT_MULTI_COLLECTION_FAIL";

export const DELETE_COLLECTION_LOADING = "DELETE_COLLECTION_LOADING";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAIL = "GET_COLLECTION_LIST_FAIL";

export const GET_WISHLIST_LOADING = "GET_WISHLIST_LOADING";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL";

export const MOVE_WISHLIST_TO_CART_LOADING = "MOVE_WISHLIST_TO_CART_LOADING";
export const MOVE_WISHLIST_TO_CART_SUCCESS = "MOVE_WISHLIST_TO_CART_SUCCESS";
export const MOVE_WISHLIST_TO_CART_FAIL = "MOVE_WISHLIST_TO_CART_FAIL";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";


export const CollectionActionTypes = {
  CREATE_COLLECTION_LOADING: "CREATE_COLLECTION_LOADING",
  CREATE_COLLECTION_SUCCESS: "CREATE_COLLECTION_SUCCESS",
  CREATE_COLLECTION_FAIL: "CREATE_COLLECTION_FAIL",
  GET_COLLECTION_LIST_LOADING: "GET_COLLECTION_LIST_LOADING",
  GET_COLLECTION_LIST_SUCCESS: "GET_COLLECTION_LIST_SUCCESS",
  GET_COLLECTION_LIST_FAIL: "GET_COLLECTION_LIST_FAIL",
  GET_COLLECTION_LIST_RESET: "GET_COLLECTION_LIST_RESET",


  GET_ADD_PRODUCT_COLLECTION_LIST_LOADING: "GET_ADD_PRODUCT_COLLECTION_LIST_LOADING",
  GET_ADD_PRODUCT_COLLECTION_LIST_SUCCESS: "GET_ADD_PRODUCT_COLLECTION_LIST_SUCCESS",
  GET_ADD_PRODUCT_COLLECTION_LIST_RESET: "GET_ADD_PRODUCT_COLLECTION_LIST_RESET",

  CREATE_ADD_PRODUCT_COLLECTION_LOADING: "CREATE_ADD_PRODUCT_COLLECTION_LOADING",
  CREATE_ADD_PRODUCT_COLLECTION_SUCCESS: "CREATE_ADD_PRODUCT_COLLECTION_SUCCESS",
  CREATE_ADD_PRODUCT_COLLECTION_RESET: "CREATE_ADD_PRODUCT_COLLECTION_RESET",



  GET_COLLECTION_DETAILS_LOADING: "GET_COLLECTION_DETAILS_LOADING",
  GET_COLLECTION_DETAILS_SUCCESS: "GET_COLLECTION_DETAILS_SUCCESS",
  GET_COLLECTION_DETAILS_FAIL: "GET_COLLECTION_DETAILS_FAIL",
  EDIT_COLLECTION_LOADING: "EDIT_COLLECTION_LOADING",
  EDIT_COLLECTION_SUCCESS: "EDIT_COLLECTION_SUCCESS",
  EDIT_COLLECTION_FAIL: "EDIT_COLLECTION_FAIL",
  EDIT_MULTI_COLLECTION_LOADING: "EDIT_MULTI_COLLECTION_LOADING",
  EDIT_MULTI_COLLECTION_SUCCESS: "EDIT_MULTI_COLLECTION_SUCCESS",
  EDIT_MULTI_COLLECTION_FAIL: "EDIT_MULTI_COLLECTION_FAIL",
  DELETE_COLLECTION_LOADING: "DELETE_COLLECTION_LOADING",
  DELETE_COLLECTION_SUCCESS: "DELETE_COLLECTION_SUCCESS",
  DELETE_COLLECTION_FAIL: "GET_COLLECTION_LIST_FAIL",
  GET_WISHLIST_LOADING: "GET_WISHLIST_LOADING",
  GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
  GET_WISHLIST_FAIL: "GET_WISHLIST_FAIL",
  GET_WISHLIST_RESET: "GET_WISHLIST_RESET",
  MOVE_WISHLIST_TO_CART_LOADING: "MOVE_WISHLIST_TO_CART_LOADING",
  MOVE_WISHLIST_TO_CART_SUCCESS: "MOVE_WISHLIST_TO_CART_SUCCESS",
  MOVE_WISHLIST_TO_CART_FAIL: "MOVE_WISHLIST0_TO_CART_FAIL"
}
