
export const inventoryActions = {
  GET_ADMIN_INVENTORY_LIST_LOADING: "GET_ADMIN_INVENTORY_LIST_LOADING",
  GET_ADMIN_INVENTORY_LIST_SUCCESS: "GET_ADMIN_INVENTORY_LIST_SUCCESS",
  GET_ADMIN_INVENTORY_LIST_ERROR: "GET_ADMIN_INVENTORY_LIST_ERROR",

  INVENTORY_DELETE_LOADING: "INVENTORY_DELETE_LOADING",
  INVENTORY_DELETE_SUCCESS: "INVENTORY_DELETE_SUCCESS",
  INVENTORY_DELETE_RESET: "INVENTORY_DELETE_RESET",

  SAERCH_INVENTORY: "SAERCH_INVENTORY",

  GET_INVENTORY_LIST_IN_STOCK_OUT_STOCK_LOADING: "GET_INVENTORY_LIST_IN_STOCK_OUT_STOCK_LOADING",
  GET_INVENTORY_LIST_IN_STOCK_OUT_STOCK_SUCCESS: "GET_INVENTORY_LIST_IN_STOCK_OUT_STOCK_SUCCESS",
  GET_INVENTORY_LIST_IN_STOCK_OUT_STOCK_ERROR: "GET_INVENTORY_LIST_IN_STOCK_OUT_STOCK_ERROR",
}
