// export const CREATE_PRODUCT_LOADING = "CREATE_PRODUCT_LOADING";
// export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
// export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

// export const GET_PRODUCT_LIST_LOADING = "GET_PRODUCT_LIST_LOADING";
// export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
// export const GET_PRODUCT_LIST_FAIL = "GET_PRODUCT_LIST_FAIL";

// export const GET_PRODUCT_LIST_STATUS_SUCCESS = "GET_PRODUCT_LIST_STATUS_SUCCESS";

// export const GET_PRODUCT_DETAIL_LOADING = "GET_PRODUCT_DETAIL_LOADING";
// export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
// export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL";

// export const GET_DASHBOARD_COUNT_LOADING = "GET_DASHBOARD_COUNT_LOADING";
// export const GET_DASHBOARD_COUNT_SUCCESS = "GET_DASHBOARD_COUNT_SUCCESS";
// export const GET_DASHBOARD_COUNT_FAIL = "GET_DASHBOARD_COUNT_FAIL";

// export const PRODUCT_EDIT_LOADING = "PRODUCT_EDIT_LOADING";
// export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
// export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";

// export const MULTI_PRODUCT_EDIT_LOADING = "MULTI_PRODUCT_EDIT_LOADING";
// export const MULTI_PRODUCT_EDIT_SUCCESS = "MULTI_PRODUCT_EDIT_SUCCESS";
// export const MULTI_PRODUCT_EDIT_FAIL = "MULTI_PRODUCT_EDIT_FAIL";

// export const PRODUCT_DELETE_LOADING = "PRODUCT_DELETE_LOADING";
// export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
// export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

// export const CUSTOMER_PRODUCT_LIST_LOADING = "CUSTOMER_PRODUCT_LIST_LOADING";
// export const CUSTOMER_PRODUCT_LIST_SUCCESS = "CUSTOMER_PRODUCT_LIST_SUCCESS";
// export const CUSTOMER_PRODUCT_LIST_FAIL = "CUSTOMER_PRODUCT_LIST_FAIL";

// export const CUSTOMER_PRODUCT_DETAIL_LOADING =
//   "CUSTOMER_PRODUCT_DETAIL_LOADING";
// export const CUSTOMER_PRODUCT_DETAIL_SUCCESS =
//   "CUSTOMER_PRODUCT_DETAIL_SUCCESS";
// export const CUSTOMER_PRODUCT_DETAIL_FAIL = "CUSTOMER_PRODUCT_DETAIL_FAIL";

// export const GET_SEARCHED_PRODUCT_LIST_LOADING =
//   "GET_SEARCHED_PRODUCT_LIST_LOADING";
// export const GET_SEARCHED_PRODUCT_LIST_SUCCESS =
//   "GET_SEARCHED_PRODUCT_LIST_SUCCESS";
// export const GET_SEARCHED_PRODUCT_LIST_FAIL = "GET_SEARCHED_PRODUCT_LIST_FAIL";

// export const HOME_PRODUCTS_LOADING = "PRODUCT_STATUS_CHANGE_LOADING";
// export const HOME_PRODUCTS_SUCCESS = "PRODUCT_STATUS_CHANGE_SUCCESS";
// export const HOME_PRODUCTS_FAIL = "PRODUCT_STATUS_CHANGE_FAIL";

// export const VARIATION_CHANGE_LOADING = 'VARIATION_CHANGE_LOADING';
// export const VARIATION_CHANGE_SUCCESS = 'VARIATION_CHANGE_SUCCESS';
// export const VARIATION_CHANGE_FAIL = 'VARIATION_CHANGE_FAIL';

export const ProductActionTypes = {
  PRODUCT_EDIT_LOADING: "PRODUCT_EDIT_LOADING",
  PRODUCT_EDIT_SUCCESS: "PRODUCT_EDIT_SUCCESS",
  PRODUCT_EDIT_ERROR: "PRODUCT_EDIT_ERROR",
  PRODUCT_EDIT_RESET: "PRODUCT_EDIT_RESET",

  CREATE_PRODUCT_LOADING: "CREATE_PRODUCT_LOADING",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",
  CREATE_PRODUCT_RESET: "CREATE_PRODUCT_RESET",

  GET_EDIT_SINGLE_PRODUCT_LOADING: "GET_EDIT_SINGLE_PRODUCT_LOADING",
  GET_EDIT_SINGLE_PRODUCT_SUCCESS: "GET_EDIT_SINGLE_PRODUCT_SUCCESS",
  GET_EDIT_SINGLE_PRODUCT_RESET: "GET_EDIT_SINGLE_PRODUCT_RESET",

  GET_PRODUCT_LIST_LOADING: "GET_PRODUCT_LIST_LOADING",
  GET_PRODUCT_LIST_SUCCESS: "GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_RESET: "GET_PRODUCT_LIST_RESET",
  //Filters
  GET_PRODUCT_LIST_BY_CATEGORY_COLL: "GET_PRODUCT_LIST_BY_CATEGORY_COLL",
  GET_PRODUCT_LIST_BY_SORTBY: "GET_PRODUCT_LIST_BY_SORTBY",
  GET_PRODUCT_LIST_SEARCH: "GET_PRODUCT_LIST_SEARCH",

  ADD_MULTIPLE_PRODUCT_TO_COLLCAT_LOADING: "ADD_MULTIPLE_PRODUCT_TO_COLLCAT_LOADING",
  ADD_MULTIPLE_PRODUCT_TO_COLLCAT_SUCCESS: "ADD_MULTIPLE_PRODUCT_TO_COLLCAT_SUCCESS",
  ADD_MULTIPLE_PRODUCT_TO_COLLCAT_ERROR: "ADD_MULTIPLE_PRODUCT_TO_COLLCAT_ERROR",


  SEND_CATEGORY_DATA_TO_PRODUCTLIST: "SEND_CATEGORY_DATA_TO_PRODUCTLIST",
  RESET_SEND_CATEGORY_DATA_TO_PRODUCTLIST: "RESET_SEND_CATEGORY_DATA_TO_PRODUCTLIST",
  SEND_UNCATEGORY_DATA_TO_PRODUCTLIST: "SEND_UNCATEGORY_DATA_TO_PRODUCTLIST",
  RESET_SEND_UNCATEGORY_DATA_TO_PRODUCTLIST: "RESET_SEND_UNCATEGORY_DATA_TO_PRODUCTLIST",

  GET_PRODUCT_LIST_STATUS_SUCCESS: "GET_PRODUCT_LIST_STATUS_SUCCESS",

  GET_SLUG_SUCCESS: "GET_SLUG_SUCCESS",
  GET_SLUG_ERROR: "GET_SLUG_ERROR",

  GET_SKU_SUCCESS: "GET_SKU_SUCCESS",
  GET_SKU_ERROR: "GET_SKU_ERROR",
  GET_SKU_RESET: "GET_SKU_RESET",

  GET_DASHBOARD_COUNT_LOADING: "GET_DASHBOARD_COUNT_LOADING",
  GET_DASHBOARD_COUNT_SUCCESS: "GET_DASHBOARD_COUNT_SUCCESS",
  GET_DASHBOARD_COUNT_FAIL: "GET_DASHBOARD_COUNT_FAIL",
  GET_PRODUCT_LIST_FAIL: "GET_PRODUCT_LIST_FAIL",
  GET_PRODUCT_DETAIL_LOADING: "GET_PRODUCT_DETAIL_LOADING",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_DETAIL_FAIL: "GET_PRODUCT_DETAIL_FAIL",
  MULTI_PRODUCT_EDIT_LOADING: "MULTI_PRODUCT_EDIT_LOADING",
  MULTI_PRODUCT_EDIT_SUCCESS: "MULTI_PRODUCT_EDIT_SUCCESS",
  MULTI_PRODUCT_EDIT_FAIL: "MULTI_PRODUCT_EDIT_FAIL",
  PRODUCT_DELETE_LOADING: "PRODUCT_DELETE_LOADING",
  PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  PRODUCT_DELETE_FAIL: "PRODUCT_DELETE_FAIL",
  CUSTOMER_PRODUCT_DETAIL_LOADING: "CUSTOMER_PRODUCT_DETAIL_LOADING",
  CUSTOMER_PRODUCT_DETAIL_SUCCESS: "CUSTOMER_PRODUCT_DETAIL_SUCCESS",
  CUSTOMER_PRODUCT_DETAIL_REST: "CUSTOMER_PRODUCT_DETAIL_REST",
  CUSTOMER_PRODUCT_DETAIL_FAIL: "CUSTOMER_PRODUCT_DETAIL_FAIL",
  GET_SEARCHED_PRODUCT_LIST_LOADING: "GET_SEARCHED_PRODUCT_LIST_LOADING",
  GET_SEARCHED_PRODUCT_LOADER_SHOW: "GET_SEARCHED_PRODUCT_LOADER_SHOW",
  GET_SEARCHED_PRODUCT_LIST_SUCCESS: "GET_SEARCHED_PRODUCT_LIST_SUCCESS",
  GET_SEARCHED_PRODUCT_LIST_FAIL: "GET_SEARCHED_PRODUCT_LIST_FAIL",
  HOME_PRODUCTS_LOADING: "HOME_PRODUCTS_LOADING",
  HOME_PRODUCTS_SUCCESS: "HOME_PRODUCTS_SUCCESS",
  HOME_PRODUCTS_FAIL: "HOME_PRODUCTS_FAIL",
  DYNAMIC_FILTER_GET_LOADING: " DYNAMIC_FILTER_GET_LOADING",
  DYNAMIC_FILTER_GET_SUCCESS: "DYNAMIC_FILTER_GET_SUCCESS",
  DYNAMIC_FILTER_GET_FAIL: "DYNAMIC_FILTER_GET_FAIL",

  PRODUCT_LIST_CURRENT_PAGE:"PRODUCT_LIST_CURRENT_PAGE"

};