export const ADMIN_USER_LIST_LOADING = "ADMIN_USER_LIST_LOADING";
export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS";
export const ADMIN_USER_LIST_FAIL = "ADMIN_USER_LIST_FAIL";


export const UserActionTypes = {
  ADMIN_USER_LIST_LOADING: "ADMIN_USER_LIST_LOADING",
  ADMIN_USER_LIST_SUCCESS: "ADMIN_USER_LIST_SUCCESS",
  ADMIN_USER_LIST_FAIL: "ADMIN_USER_LIST_FAIL"
}
