export const GET_VENDOR_SHOP_LOADING = 'GET_VENDOR_SHOP_LOADING';
export const GET_VENDOR_SHOP_SUCCESS = 'GET_VENDOR_SHOP_SUCCESS';
export const GET_VENDOR_SHOP_FAIL = 'GET_VENDOR_SHOP_FAIL';

export const GET_VENDOR_PRODUCTS_LOADING = 'GET_VENDOR_PRODUCTS_LOADING';
export const GET_VENDOR_PRODUCTS_SUCCESS = 'GET_VENDOR_PRODUCTS_SUCCESS';
export const GET_VENDOR_PRODUCTS_FAIL = 'GET_VENDOR_PRODUCTS_FAIL';


export const VendorActionTypes = {
  GET_VENDOR_SHOP_LOADING: 'GET_VENDOR_SHOP_LOADING',
  GET_VENDOR_SHOP_SUCCESS: 'GET_VENDOR_SHOP_SUCCESS',
  GET_VENDOR_SHOP_FAIL: 'GET_VENDOR_SHOP_FAIL',
  GET_VENDOR_PRODUCTS_LOADING: 'GET_VENDOR_PRODUCTS_LOADING',
  GET_VENDOR_PRODUCTS_SUCCESS: 'GET_VENDOR_PRODUCTS_SUCCESS',
  GET_VENDOR_PRODUCTS_FAIL: 'GET_VENDOR_PRODUCTS_FAIL'
}