export const studentRegActionType = {
    "STD_REG_LOADING":"STD_REG_LOADING",
    "STD_REG_LOADED":"STD_REG_LOADED",
    "STD_REG_LOADING_ERROR":"STD_REG_LOADING_ERROR",
    "STD_TOKEN_LOADING":"STD_TOKEN_LOADING",
    "STD_TOKEN_LOADED":"STD_TOKEN_LOADED",
    "STD_TOKEN_LOADING_ERROR":"STD_TOKEN_LOADING_ERROR"
}