export const Ecommerce = {
  GET_PRIVACY_POLICY_LOADING: "GET_PRIVACY_POLICY_LOADING",
  GET_PRIVACY_POLICY_SUCCESS: "GET_PRIVACY_POLICY_SUCCESS",
  GET_PRIVACY_POLICY_ERROR: "GET_PRIVACY_POLICY_ERROR",
  GET_PRIVACY_POLICY_RESET: "GET_PRIVACY_POLICY_RESET",

  CREATE_PRIVACY_POLICY_LOADING: "CREATE_PRIVACY_POLICY_LOADING",
  CREATE_PRIVACY_POLICY_SUCCESS: "CREATE_PRIVACY_POLICY_SUCCESS",
  CREATE_PRIVACY_POLICY_ERROR: "CREATE_PRIVACY_POLICY_ERROR",
  CREATE_PRIVACY_POLICY_RESET: "CREATE_PRIVACY_POLICY_RESET",

  UPDATE_PRIVACY_POLICY_LOADING: "UPDATE_PRIVACY_POLICY_LOADING",
  UPDATE_PRIVACY_POLICY_SUCCESS: "UPDATE_PRIVACY_POLICY_SUCCESS",
  UPDATE_PRIVACY_POLICY_ERROR: "UPDATE_PRIVACY_POLICY_ERROR",
  UPDATE_PRIVACY_POLICY_RESET: "UPDATE_PRIVACY_POLICY_RESET",

  DELETE_PRIVACY_POLICY_LOADING: "DELETE_PRIVACY_POLICY_LOADING",
  DELETE_PRIVACY_POLICY_SUCCESS: "DELETE_PRIVACY_POLICY_SUCCESS",
  DELETE_PRIVACY_POLICY_ERROR: "DELETE_PRIVACY_POLICY_ERROR",
  DELETE_PRIVACY_POLICY_RESET: "DELETE_PRIVACY_POLICY_RESET"
}