export const REQUEST_TYPE = {
  LMS_GET_FEE: "LMS_GET_FEE",
  LMS_POST_FEE: "LMS_POST_FEE",
  LMS_UPDATE_FEE: "LMS_UPDATE_FEE",
  LMS_FEE_LOADING: "LMS_FEE_LOADING",
  LMS_DELETE_FEE: "LMS_DELETE_FEE",
  LMS_SORT_BY_LTH: "LMS_SORT_BY_LTH",
  LMS_SORT_BY_HTL: "LMS_SORT_BY_HTL",
  LMS_SORT_BY_ACTIVE: "LMS_SORT_BY_ACTIVE",
  LMS_SORT_BY_INACTIVE: "LMS_SORT_BY_INACTIVE",
  LMS_SEARCH_FEE: "LMS_SEARCH_FEE",
  LMS_GET_PAYMENT_MODE: "LMS_GET_PAYMENT_MODE",
  LMS_SINGLE_FEE: "LMS_SINGLE_FEE",
  LMS_SINGLE_FEE_LOADING: "LMS_SINGLE_FEE_LOADING",
  LMS_SORT_BY_SAVED: "LMS_SORT_BY_SAVED",
  LMS_RESET_SINGLE_FEE_INFO: "LMS_RESET_SINGLE_FEE_INFO",
  LMS_UPDATE_SINGLE_FEE: "LMS_UPDATE_SINGLE_FEE",
  LMS_UPDATE_SINGLE_FEE_ERROR_SAMECLASSROOM: "LMS_UPDATE_SINGLE_FEE_ERROR_SAMECLASSROOM",
  LMS_UPDATE_SINGLE_FEE_ERROR_SAMECLASSROOM_RESET: "LMS_UPDATE_SINGLE_FEE_ERROR_SAMECLASSROOM_RESET",
  LMS_SORT_BY_FEETYPE: "LMS_SORT_BY_FEETYPE",



  LMS_GET_FEE_LOADING: "LMS_GET_FEE_LOADING",
  LMS_GET_FEE_LOADED: "LMS_GET_FEE_LOADED",
  LMS_GET_FEE_ERROR: "LMS_GET_FEE_ERROR",
  LMS_GET_FEE_RESET: "LMS_GET_FEE_RESET",


  LMS_GET_AVAILABLE_COURSES_LOADING: "LMS_GET_AVAILABLE_COURSES_LOADING",
  LMS_GET_AVAILABLE_COURSES_LOADED: "LMS_GET_AVAILABLE_COURSES_LOADED",
  LMS_GET_AVAILABLE_COURSES_ERROR: "LMS_GET_AVAILABLE_COURSES_ERROR",
  LMS_GET_AVAILABLE_COURSES_RESET: "LMS_GET_AVAILABLE_COURSES_RESET",

  LMS_POST_FEE_LOADING: "LMS_POST_FEE_LOADING",
  LMS_POST_FEE_LOADED: "LMS_POST_FEE_LOADED",
  LMS_POST_FEE_ERROR: "LMS_POST_FEE_ERROR",
  LMS_POST_FEE_RESET: "LMS_POST_FEE_RESET",


  LMS_EDIT_FEE_LOADING: "LMS_EDIT_FEE_LOADING",
  LMS_EDIT_FEE_LOADED: "LMS_EDIT_FEE_LOADED",
  LMS_EDIT_FEE_ERROR: "LMS_EDIT_FEE_ERROR",
  LMS_EDIT_FEE_RESET: "LMS_EDIT_FEE_RESET",


};
