export const NOTICE_BOARD_ACTION_TYPES={
 CREATE_NOTICE_LOADING:"CREATE_NOTICE_LOADING",
  CREATE_NOTICE_LOADED:"CREATE_NOTICE_LOADED",
  CREATE_NOTICE_ERROR:"CREATE_NOTICE_ERROR",
  CREATE_NOTICE_RESET:"CREATE_NOTICE_RESET",

  GET_NOTICE_LIST_LOADING:"GET_NOTICE_LIST_LOADING",
  GET_NOTICE_LIST_LOADED:"GET_NOTICE_LIST_LOADED",
  GET_NOTICE_LIST_ERROR:"GET_NOTICE_LIST_ERROR",
  GET_NOTICE_LIST_RESET:"GET_NOTICE_LIST_RESET",

  GET_SINGLE_NOTICE_LOADING:"GET_SINGLE_NOTICE_LOADING",
  GET_SINGLE_NOTICE_SUCCESS:"GET_SINGLE_NOTICE_SUCCESS",
  GET_SINGLE_NOTICE_ERROR:"GET_SINGLE_NOTICE_ERROR",
  GET_SINGLE_NOTICE_RESET:"GET_SINGLE_NOTICE_RESET",
 
  EDIT_NOTICE_LOADING:"EDIT_NOTICE_LOADING",
  EDIT_NOTICE_LOADED:"EDIT_NOTICE_LOADED",
  EDIT_NOTICE_ERROR:"EDIT_NOTICE_ERROR",
  EDIT_NOTICE_RESET:"EDIT_NOTICE_RESET",

  SEARCH_SORT_NOTICE:"SEARCH_SORT_NOTICE",
  // CLASSROOM_FILTER_NOTICE:"CLASSROOM_FILTER_NOTICE",

  DELETE_NOTICE_LOADING:"DELETE_NOTICE_LOADING",
  DELETE_NOTICE_SUCCESS:"DELETE_NOTICE_SUCCESS",
  DELETE_NOTICE_RESET:"DELETE_NOTICE_RESET",
  DELETE_NOTICE_ERROR:"DELETE_NOTICE_ERROR",
}