export const INS_ACTION_TYPES = {
    INS_SUBDOMAIN_LOADING: "INS_SUBDOMAIN_LOADING",
    INS_SUBDOMAIN_LOADED: "INS_SUBDOMAIN_LOADED",
    INS_SUBDOMAIN_LOADING_ERROR: "INS_SUBDOMAIN_LOADING_ERROR",
    INS_SUBDOMAIN_NOT_FOUND: "INS_SUBDOMAIN_NOT_FOUND",

    INS_SUBDOMIAN_LIKE: "INS_SUBDOMIAN_LIKE",
    INS_SUBDOMAIN_LIKE_INFO: "INS_SUBDOMAIN_LIKE_INFO",
    INS_DOMAIN_PWA_LOADING: "INS_DOMAIN_PWA_LOADING",
    INS_DOMAIN_PWA_LOADED: "INS_DOMAIN_PWA_LOADED",
    INS_DOMAIN_PWA_LOADING_ERROR: "INS_DOMAIN_PWA_LOADING_ERROR",
    INS_DOMAIN_PWA_NOT_FOUND: "INS_DOMAIN_PWA_NOT_FOUND",

    INS_WEBSITE_HEADER_LOADING: "INS_WEBSITE_HEADER_LOADING",
    INS_WEBSITE_HEADER: "INS_WEBSITE_HEADER",
}