export const StudentAttendanceActionTypes = {
  GET_STUDENT_ATTENDANCE_LIST: "GET_STUDENT_ATTENDANCE_LIST",
  GET_STUDENT_ATTENDANCE_LIST_LOADING: "GET_STUDENT_ATTENDANCE_LIST_LOADING",
  GET_STUDENT_ATTENDANCE_LIST_RESET: "GET_STUDENT_ATTENDANCE_LIST_RESET",

  SEND_LEAVE_REQUEST_LOADING: "SEND_LEAVE_REQUEST_LOADING",
  SEND_LEAVE_REQUEST: "SEND_LEAVE_REQUEST",
  SEND_LEAVE_REQUEST_RESET: "SEND_LEAVE_REQUEST_RESET",

  GET_LEAVE_REQUEST_LIST_LOADING: "GET_LEAVE_REQUEST_LIST_LOADING",
  GET_LEAVE_REQUEST_LIST: "GET_LEAVE_REQUEST_LIST",
  GET_LEAVE_REQUEST_LIST_RESET: "GET_LEAVE_REQUEST_LIST_RESET",

  SORT_STUDENT_LEAVE_REQUEST_LIST: "SORT_STUDENT_LEAVE_REQUEST_LIST",

  CANCEL_LEAVE_REQUEST_LOADING: "CANCEL_LEAVE_REQUEST_LOADING",
  CANCEL_LEAVE_REQUEST: "CANCEL_LEAVE_REQUEST",
  CANCEL_LEAVE_REQUEST_RESET: "CANCEL_LEAVE_REQUEST_RESET",
}