export const EMPLOYEETYPES = {
  EMPLOYEE_LIST_LOADING: "EMPLOYEE_LIST_LOADING",
  EMPLOYEE_LIST_SUCCESS: "EMPLOYEE_LIST_SUCCESS",
  EMPLOYEE_LIST_RESET: "EMPLOYEE_LIST_RESET",

  DELETE_EMPLOYEE_LOADING:"DELETE_EMPLOYEE_LOADING",
  DELETE_EMPLOYEE_LOADED:"DELETE_EMPLOYEE_LOADED",
  
}