export const Ecomm_Reviews_ActionTypes = {
  GET_ADMIN_REVIEW_LOADING: "GET_ADMIN_REVIEW_LOADING",
  GET_ADMIN_REVIEW_LOADED: "GET_ADMIN_REVIEW_LOADED",
  GET_ADMIN_REVIEW_ERROR: "GET_ADMIN_REVIEW_ERROR",
  GET_ADMIN_REVIEW_RESET: "GET_ADMIN_REVIEW_RESET",

  POST_ADMIN_REVIEW_LOADING: "POST_ADMIN_REVIEW_LOADING",
  POST_ADMIN_REVIEW_LOADED: "POST_ADMIN_REVIEW_LOADED",
  POST_ADMIN_REVIEW_ERROR: "POST_ADMIN_REVIEW_ERROR",
  POST_ADMIN_REVIEW_RESET: "POST_ADMIN_REVIEW_RESET",

  GET_SINGLE_REVIEW_LOADING: "GET_SINGLE_REVIEW_LOADING",
  GET_SINGLE_REVIEW_LOADED: "GET_SINGLE_REVIEW_LOADED",
  GET_SINGLE_REVIEW_ERROR: "GET_SINGLE_REVIEW_ERROR",
  GET_SINGLE_REVIEW_RESET: "GET_SINGLE_REVIEW_RESET",

  PATCH_ADMIN_REVIEW_LOADING: "PATCH_ADMIN_REVIEW_LOADING",
  PATCH_ADMIN_REVIEW_LOADED: "PATCH_ADMIN_REVIEW_LOADED",
  PATCH_ADMIN_REVIEW_ERROR: "PATCH_ADMIN_REVIEW_ERROR",
  PATCH_ADMIN_REVIEW_RESET: "PATCH_ADMIN_REVIEW_RESET",

  DELETE_REVIEW_LOADING: "DELETE_REVIEW_LOADING",
  DELETE_REVIEW_LOADED: "DELETE_REVIEW_LOADED",
  DELETE_REVIEW_ERROR: "DELETE_REVIEW_ERROR",
  DELETE_REVIEW_RESET: "DELETE_REVIEW_RESET",

  MULTIPLE_DELETE_REVIEW_LOADED: "MULTIPLE_DELETE_REVIEW_LOADED",

  READ_UNREAD_REVIEWS_SUCCESS: "READ_UNREAD_REVIEWS_SUCCESS",

  REPLY_STATUS_UPDATE_SUCCESS: "REPLY_STATUS_UPDATE_SUCCESS",

  POST_REVIEW_REPLY_LOADING: "POST_REVIEW_REPLY_LOADING",
  POST_REVIEW_REPLY_LOADED: "POST_REVIEW_REPLY_LOADED",
  POST_REVIEW_REPLY_ERROR: "POST_REVIEW_REPLY_ERROR",
  POST_REVIEW_REPLY_RESET: "POST_REVIEW_REPLY_RESET",

  DELETE_REVIEW_REPLY_LOADING: "DELETE_REVIEW_REPLY_LOADING",
  DELETE_REVIEW_REPLY_LOADED: "DELETE_REVIEW_REPLY_LOADED",
  DELETE_REVIEW_REPLY_ERROR: "DELETE_REVIEW_REPLY_ERROR",
  DELETE_REVIEW_REPLY_RESET: "DELETE_REVIEW_REPLY_RESET",

  REVIEW_STATUS_UPDATE_SUCCESS: "REVIEW_STATUS_UPDATE_SUCCESS",

  MULTIPLE_RESTORE_REVIEW_LOADED: "MULTIPLE_RESTORE_REVIEW_LOADED",

  MULTIPLE_PERMANANT_DELETE_LOADED: "MULTIPLE_PERMANANT_DELETE_LOADED",

  SET_REVIEW_ID_SUCCESS: "SET_REVIEW_ID_SUCCESS",

  GET_PRODUCT_REVIEW_LOADING: "GET_PRODUCT_REVIEW_LOADING",
  GET_PRODUCT_REVIEW_LOADED: "GET_PRODUCT_REVIEW_LOADED",
  GET_PRODUCT_REVIEW_ERROR: "GET_PRODUCT_REVIEW_ERROR",
  GET_PRODUCT_REVIEW_RESET: "GET_PRODUCT_REVIEW_RESET",

  GET_BUYER_PRODUCT_RELATION:"GET_BUYER_PRODUCT_RELATION"
}