export const ShippingActionTypes = {

  SHIPPING_CREATE_LOADING: "SHIPPING_CREATE_LOADING",
  SHIPPING_CREATE_LOADED: "SHIPPING_CREATE_LOADED",
  SHIPPING_CREATE_ERROR: "SHIPPING_CREATE_ERROR",
  SHIPPING_CREATE_RESET: "SHIPPING_CREATE_RESET",

  SHIPPING_GET_LOADING: "SHIPPING_GET_LOADING",
  SHIPPING_GET_LOADED: "SHIPPING_GET_LOADED",
  SHIPPING_GET_ERROR: "SHIPPING_GET_ERROR",
  SHIPPING_GET_RESET: "SHIPPING_GET_RESET",

  SHIPPING_SINGLE_GET_LOADING: "SHIPPING_SINGLE_GET_LOADING",
  SHIPPING_SINGLE_GET_LOADED: "SHIPPING_SINGLE_GET_LOADED",
  SHIPPING_SINGLE_GET_ERROR: "SHIPPING_SINGLE_GET_ERROR",
  SHIPPING_SINGLE_GET_RESET: "SHIPPING_SINGLE_GET_RESET",

  SHIPPING_EDIT_LOADING: "SHIPPING_EDIT_LOADING",
  SHIPPING_EDIT_LOADED: "SHIPPING_EDIT_LOADED",
  SHIPPING_EDIT_ERROR: "SHIPPING_EDIT_ERROR",
  SHIPPING_EDIT_RESET: "SHIPPING_EDIT_RESET",

  SHIPPING_EXISTING_STATES_LOADING: "SHIPPING_EXISTING_STATES_LOADING",
  SHIPPING_EXISTING_STATES_LOADED: "SHIPPING_EXISTING_STATES_LOADED",
  SHIPPING_EXISTING_STATES_RESET: "SHIPPING_EXISTING_STATES_RESET",

  SHIPPING_DELETE_LOADING: "SHIPPING_DELETE_LOADING",
  SHIPPING_DELETE_SUCCESS: "SHIPPING_DELETE_SUCCESS",
  SHIPPING_DELETE_RESET: "SHIPPING_DELETE_RESET",
}

