export const REQUEST_TYPE = {
  GET_TESTIMONIAL: "GET_TESTIMONIAL",
  POST_TESTIMONIAL: "POST_TESTIMONIAL",
  POST_TESTIMONIAL_LOADING: "POST_TESTIMONIAL_LOADING",
  POST_TESTIMONIAL_RESET: "POST_TESTIMONIAL_RESET",
  UPDATE_TESTIMONIAL: "UPDATE_TESTIMONIAL",
  TESTIMONIAL_LOADING: "TESTIMONIAL_LOADING",
  DELETE_TESTIMONIAL: "DELETE_TESTIMONIAL",
  TESTIMONIAL_FEATURE_MARKED: "TESTIMONIAL_FEATURE_MARKED",
  TESTIMONIAL_FEATURE_NOT_MARKED: "TESTIMONIAL_FEATURE_NOT_MARKED",
  TESTIMONIAL_SORT_BY_LTH: "TESTIMONIAL_SORT_BY_LTH",
  TESTIMONIAL_SORT_BY_HTL: "TESTIMONIAL_SORT_BY_HTL",
  SEARCH_TESTIMONIAL: "SEARCH_TESTIMONIAL",
  RATING: "RATING",
  SINGLE_TESTIMONIAL_DATA: "SINGLE_TESTIMONIAL_DATA",
  CLEAR_TESTIMONIAL_DATA: "CLEAR_TESTIMONIAL_DATA",
  UPDATE_SINGLE_TESTIMONIAL: "UPDATE_SINGLE_TESTIMONIAL",

  GET_ALL_REVIEWS_FOR_USER: "GET_ALL_REVIEWS_FOR_USER",
  GET_ALL_REVIEWS_FOR_USER_LOADING: "GET_ALL_REVIEWS_FOR_USER_LOADING",
  GET_ALL_REVIEWS: "GET_ALL_REVIEWS",
  GET_ALL_REVIEWS_LOADING: "GET_ALL_REVIEWS_LOADING",

  POST_EDNEED_REVIEW: "POST_EDNEED_REVIEW",
  POST_EDNEED_REVIEW_LOADING: "POST_EDNEED_REVIEW_LOADING",
  SEARCH_FOR_USER_REVIEW: "SEARCH_FOR_USER_REVIEW",
  SEARCH_REVIEWS: "SEARCH_REVIEWS",

  GET_SINGLE_EDNEED_REVIEW: "GET_SINGLE_EDNEED_REVIEW",
  GET_SINGLE_EDNEED_REVIEW_LOADING: "GET_SINGLE_EDNEED_REVIEW_LOADING",
  UPDATE_EDNEED_REVIEW: "UPDATE_EDNEED_REVIEW",
  UPDATE_EDNEED_REVIEW_LOADING: "UPDATE_EDNEED_REVIEW_LOADING",
  DELETE_REVIEW: "DELETE_REVIEW",
  DELETE_REVIEW_LOADING: "DELETE_REVIEW_LOADING",
  RESET_EDNEED_REVIEW: "RESET_EDNEED_REVIEW",


  ALL_TESTIMONIAL_LOADING: "ALL_TESTIMONIAL_LOADING",
  ALL_TESTIMONIAL_LOADED: 'ALL_TESTIMONIAL_LOADED',
  ALL_TESTIMONIAL_RESET: "ALL_TESTIMONIAL_RESET"
};
