export const CHECKDOMAIN_LIST_AT = {

    CHECKDOMAIN_READ: "CHECKDOMAIN_READ",
    CHECKDOMAIN_LOADING: "CHECKDOMAIN_LOADING",
    CHECKDOMAIN_CREATE: "CHECKDOMAIN_CREATE",
    CHECKDOMAIN_PATCH: "CHECKDOMAIN_PATCH",
    CHECKDOMAIN_PATCH_REST: "CHECKDOMAIN_PATCH_REST",
    DOMAIN_READ: "DOMAIN_READ",
    DOMAIN_READ_LOADING: "DOMAIN_READ_LOADING",
    CHECKDOMAIN_PATCH_RESET: "CHECKDOMAIN_PATCH_RESET"
}