export const USERSIDEAPPOINTMENTTYPES = {
  //User Side Booking List 
  GET_USER_SIDE_BOOKING_LIST_LOADING: "GET_USER_SIDE_BOOKING_LIST_LOADING",
  GET_USER_SIDE_BOOKING_LIST_LOADED: "GET_USER_SIDE_BOOKING_LIST_LOADED",
  GET_USER_SIDE_BOOKING_LIST_ERROR: "GET_USER_SIDE_BOOKING_LIST_ERROR",
  GET_USER_SIDE_BOOKING_LIST_RESET: "GET_USER_SIDE_BOOKING_LIST_RESET",

  // USER SIDE BOOKING LIST SORT
  GET_USER_SIDE_BOOKING_LIST_SORT_LOADED: "GET_USER_SIDE_BOOKING_LIST_SORT_LOADED",

  // USER SIDE BOOKING LIST SEARCH
  GET_SEARCH_USER_SIDE_BOOKING_LIST_LOADED: "GET_SEARCH_USER_SIDE_BOOKING_LIST_LOADED",
  GET_SEARCH_USER_SIDE_BOOKING_LIST_RESET: "GET_SEARCH_USER_SIDE_BOOKING_LIST_RESET",

  // USER SIDE BOOKING LIST EDIT
  EDIT_USER_LIST_LOADING: "EDIT_USER_LIST_LOADING",
  EDIT_USER_LIST_LOADED: "EDIT_USER_LIST_LOADED",
  EDIT_USER_LIST_ERROR: "EDIT_USER_LIST_ERROR",
  EDIT_USER_LIST_RESET: "EDIT_USER_LIST_RESET",
}