export const WhatsAppSupportActionTypes = {
GET_WHATSAPP_PRIVATE_DOMAIN: "GET_WHATSAPP_PRIVATE_DOMAIN",
GET_WHATSAPP_SUBDOMAIN : "GET_WHATSAPP_SUBDOMAIN",
WHATSAPP_PRIVATE_DOMAIN_LOADING : "WHATSAPP_PRIVATE_DOMAIN_LOADING"
}