export const ContactUsActionType = {
    CONTACT_US: "CONTACT_US",
    CONTACT_US_RESET: "CONTACT_US_RESET",

    GET_CONTACTS_LIST_LOADING: "GET_CONTACTS_LIST_LOADING",
    GET_CONTACTS_LIST_LOADED: "GET_CONTACTS_LIST_LOADED",
    GET_CONTACTS_LIST_ERROR: "GET_CONTACTS_LIST_ERROR",
    GET_CONTACTS_LIST_RESET: "GET_CONTACTS_LIST_RESET",

    SORT_CONTACTS_LIST: "SORT_CONTACTS_LIST",

    SEARCH_CONTACTS_LIST: "SEARCH_CONTACTS_LIST",

    DOWNLOAD_EXCEL_SHEET: "DOWNLOAD_EXCEL_SHEET",

    DOWNLOAD_EXCEL_SHEET_RESET: "DOWNLOAD_EXCEL_SHEET_RESET"
}