export const ASSIGNMENT_TYPE = {
  ASSIGNMENT_LOADING: "ASSIGNMENT_LOADING",
  ASSIGNMENT_LOADED: "ASSIGNMENT_LOADED",

  STUDENT_INFO_READ: "STUDENT_INFO_READ",
  ALL_ASSIGNMENT_STUDENT_READ: "ALL_ASSIGNMENT_STUDENT_READ",
  ALL_ASSIGNMENT_STUDENT_READ_RESET: "ALL_ASSIGNMENT_STUDENT_READ_RESET",
  SINGLE_ASSIGNMENT_READ_STUDENT: "SINGLE_ASSIGNMENT_READ_STUDENT",
  ASSIGNMENT_READ: "ASSIGNMENT_READ",
  ASSIGNMENT_CREATE: "ASSIGNMENT_CREATE",
  ASSIGNMENT_CREATE_LOADING: "ASSIGNMENT_CREATE_LOADING",
  ASSIGNMENT_CREATE_RESET: "ASSIGNMENT_CREATE_RESET",
  ASSIGNMENT_EDIT: "ASSIGNMENT_EDIT",
  ASSIGNMENT_UPDATE_SELECTION: "ASSIGNMENT_UPDATE_SELECTION",
  ASSIGNMENT_UPDATE: "ASSIGNMENT_UPDATE",
  ASSIGNMENT_UPDATE_ERROR: "ASSIGNMENT_UPDATE_ERROR",
  ASSIGNMENT_UPDATED: "ASSIGNMENT_UPDATED",
  CLEAR_ASSIGNMENT_VIEW: "CLEAR_ASSIGNMENT_VIEW",
  SINGLE_ASSIGNMENT_READ_STUDENT_LOADING:
    "SINGLE_ASSIGNMENT_READ_STUDENT_LOADING",
  STUDENT_ASSIGNMENT_CLASS_AND_COURSE: "STUDENT_ASSIGNMENT_CLASS_AND_COURSE",

  SORT_BY_STUDENT_ASSIGNMENT_OTR1: "SORT_BY_STUDENT_ASSIGNMENT_OTR1",
  SORT_BY_STUDENT_ASSIGNMENT_OTR2: "SORT_BY_STUDENT_ASSIGNMENT_OTR2",
  SORT_BY_STUDENT_ASSIGNMENT_RTO1: "SORT_BY_STUDENT_ASSIGNMENT_RTO1",
  SORT_BY_STUDENT_ASSIGNMENT_RTO2: "SORT_BY_STUDENT_ASSIGNMENT_RTO2",
  SORT_BY_STUDENT_ASSIGNMENT_SUBMITED: "SORT_BY_STUDENT_ASSIGNMENT_SUBMITED",
  SORT_BY_STUDENT_ASSIGNMENT_PENDING: "SORT_BY_STUDENT_ASSIGNMENT_PENDING",
  SORT_BY_STUDENT_ASSIGNMENT_GRADED: "SORT_BY_STUDENT_ASSIGNMENT_GRADED",
  SORT_BY_STUDENT_ASSIGNMENT_MISSED:"SORT_BY_STUDENT_ASSIGNMENT_MISSED"
};
