export const InsActionTypes = {
  INS_CREATING: "INS_CREATING",
  INS_CREATED: "INS_CREATED",
  INS_CREATE_ERROR: "INS_CREATE_ERROR",
  INS_CREATE_RESET: "INS_CREATE_RESET",
  INS_CREATE_CHANGE_STATE: "INS_CREATE_CHANGE_STATE",
  INS_INFORMATION_LOADING: "INS_INFORMATION_LOADING",
  INS_INFORMATION_LOADED: "INS_INFORMATION_LOADED",
  INS_INFORMATION_ERROR: "INS_INFORMATION_ERROR",
  INS_UPDATING: "INS_UPDATING",
  INS_UPDATED: "INS_UPDATED",
  INS_UPDATE_ERROR: "INS_UPDATE_ERROR",
  INS_RESET_INFORMATION: "INS_RESET_INFORMATION"
};
