export const ZOOMAPITYPES = {
  GET_EDNEED_USER: "GET_EDNEED_USER",
  POST_EDNEED_USER: "POST_EDNEED_USER",
  GET_ZOOM_USER: "GET_ZOOM_USER",
  POST_ZOOM_USER: "POST_ZOOM_USER",
  SUCCESS_FALSE: "SUCCESS_FALSE",
  GET_JOINEE_LIST: "GET_JOINEE_LIST",
  RESET_JOINEE_LIST: "RESET_JOINEE_LIST",
};

export const scheduleClassActionTypes = {
  SC_CREATE_LOADING: "SC_CREATE_LOADING",
  SC_CREATE_LOADED: "SC_CREATE_LOADED",
  SC_CREATE_LOADING_ERROR: "SC_CREATE_LOADING_ERROR",
  HIDE_ZOOM_POPUP: "HIDE_ZOOM_POPUP",
  SHOW_ZOOM_POPUP: "SHOW_ZOOM_POPUP",
};

export const scheduleClaassViaGoogle = {
  SCMEET_CREATE_LOADING: "SCMEET_CREATE_LOADING",
  SCMEET_CREATE_LOADED: "SCMEET_CREATE_LOADED",
  SCMEET_CREATE_EVENT: "SCMEET_CREATE_EVENT",
  SCMEET_CREATE_EVENT_LOADING: "SCMEET_CREATE_EVENT_LOADING",
};
