export const CLASSROOMTYPE = {
    
    CLASSROOM_LOADING:"COURSE_LOADING",
    CLASSROOM_LOADED:"COURSE_LOADED",

    CLASSROOM_GET_INVITE_FACULTY:"CLASSROOM_GET_INVITE_FACULTY",
    CLASSROOM_READ:"CLASSROOM_READ",
    COURSE_INFO_DATA:"COURSE_INFO_DATA",
    CLASSROOM_CREATE:"CLASSROOM_CREATE",
    CLASSROOM_EDIT:"CLASSROOM_EDIT",
    CLASSROOM_DELETE:"CLASSROOM_DELETE",
    CLASSROOM_UPDATE_SELECTION:"CLASSROOM_UPDATE_SELECTION",
    COURSE_NAME_UPDATE:"COURSE_NAME_UPDATE",
    CLASSROOM_UPDATE:"CLASSROOM_UPDATE",
    CLASSROOM_UPDATE_ERROR:"CLASSROOM_UPDATE_ERROR",
    CLASSROOM_UPDATED:"CLASSROOM_UPDATED",
    RESET_CLASSROOM_DATA:"RESET_CLASSROOM_DATA"
}