export const Catergory_Filter_ActionTypes = {

  CATEGORY_PUSH: "CATEGORY_PUSH",
  SUB_CATEGORY_PUSH: "SUB_CATEGORY_PUSH",
  SUB_SUB_CATEGORY_PUSH: "SUB_SUB_CATEGORY_PUSH",

  CATEGORY_POP: "CATEGORY_POP",
  SUB_CATEGORY_POP: "SUB_CATEGORY_POP",
  SUB_SUB_CATEGORY_POP: "SUB_SUB_CATEGORY_POP",

  ALL_SUB_CATEGORY_PUSH: "ALL_SUB_CATEGORY_PUSH",
  ALL_SUB_SUB_CATEGORY_PUSH: "ALL_SUB_SUB_CATEGORY_PUSH",

  ALL_SUB_CATEGORY_POP: "ALL_SUB_CATEGORY_POP",
  ALL_SUB_SUB_CATEGORY_POP: "ALL_SUB_SUB_CATEGORY_POP",

  SUB_CATEGORY_PUSH_IF_PARENT_SELECTED: "SUB_CATEGORY_PUSH_IF_PARENT_SELECTED",



  SHOW_REMOVE_CAT:"SHOW_REMOVE_CAT",
  SHOW_REMOVE_SUB_CAT:"SHOW_REMOVE_SUB_CAT",
  SHOW_REMOVE_SUB_SUB_CAT:"SHOW_REMOVE_SUB_SUB_CAT",

 
  SHOW_ADD_CAT:"SHOW_ADD_CAT",
  SHOW_ADD_SUB_CAT:"SHOW_ADD_SUB_CAT",
  SHOW_ADD_SUB_SUB_CAT:"SHOW_ADD_SUB_SUB_CAT",

  CLEAR_ALL_CATEGRY:"CLEAR_ALL_CATEGRY",
  CLEAR_SEARCH_FILTER:"CLEAR_SEARCH_FILTER"


}