export const SUCCESS_MSG_POPUP = {
    "SET_SUCCESS": "SET_SUCCESS",
    "HIDE_SUCCESS": "HIDE_SUCCESS",
    "SUCCESS_TOAST": "SUCCESS_TOAST",
    "ERROR_TOAST": "ERROR_TOAST",
    "WARNING_TOAST": "WARNING_TOAST",
}