export const ASSIGNMENT_TYPE = {
  ASSIGNMENT_LOADING: "ASSIGNMENT_LOADING",
  ASSIGNMENT_LOADED: "ASSIGNMENT_LOADED",

  ASSIGNMENT_READ: "ASSIGNMENT_READ",
  ASSIGNMENT_CREATEDBY: "ASSIGNMENT_CREATEDBY",
  ASSIGNMENT_SEARCH_READ: "ASSIGNMENT_SEARCH_READ",
  ASSIGNMENT_READ_LOADING: "ASSIGNMENT_READ_LOADING",
  ASSIGNMENT_READ_RESET: "ASSIGNMENT_READ_RESET",
  SINGLE_ASSIGNMENT_READ: "SINGLE_ASSIGNMENT_READ",

  ASSIGNMENT_CREATE: "ASSIGNMENT_CREATE",
  ASSIGNMENT_CREATE_LOADING: "ASSIGNMENT_CREATE_LOADING",
  ASSIGNMENT_CREATE_ERROR: "ASSIGNMENT_CREATE_ERROR",

  ASSIGNMENT_REMARK_RESET: "ASSIGNMENT_REMARK_RESET",
  ASSIGNMENT_REMARK: "ASSIGNMENT_REMARK",
  ASSIGNMENT_REMARK_LOADING: "ASSIGNMENT_REMARK_LOADING",
  ASSIGNMENT_EDIT: "ASSIGNMENT_EDIT",

  ASSIGNMENT_DELETE_LOADING: "ASSIGNMENT_DELETE_LOADING",
  ASSIGNMENT_DELETE: "ASSIGNMENT_DELETE",
  ASSIGNMENT_DELETE_ERROR: "ASSIGNMENT_DELETE_ERROR",

  TEACHER_ASSIGNMENT_UPDATE_SELECTION: "TEACHER_ASSIGNMENT_UPDATE_SELECTION",
  TEACHER_ASSIGNMENT_UPDATE_SELECTION_RESET:
    "TEACHER_ASSIGNMENT_UPDATE_SELECTION_RESET",

  ASSIGNMENT_UPDATE_TEACHER_LOADING: "ASSIGNMENT_UPDATE_TEACHER_LOADING",
  ASSIGNMENT_UPDATE_TEACHER: "ASSIGNMENT_UPDATE_TEACHER",
  ASSIGNMENT_UPDATE_TEACHER_RESET: "ASSIGNMENT_UPDATE_TEACHER_RESET",
  ASSIGNMENT_UPDATE_TEACHER_ERROR: "ASSIGNMENT_UPDATE_TEACHER_ERROR",
  ASSIGNMENT_UPDATE_ERROR: "ASSIGNMENT_UPDATE_ERROR",
  ASSIGNMENT_UPDATED: "ASSIGNMENT_UPDATED",

  SINGLE_ASSIGNMENT_READ_TEACHER_VIEW: "SINGLE_ASSIGNMENT_READ_TEACHER_VIEW",

  ASSIGNMENT_SORTBYRTO1: "ASSIGNMENT_SORTBYRTO1",
  ASSIGNMENT_SORTBYOTR1: "ASSIGNMENT_SORTBYOTR1",

  ASSIGNMENT_SORTBYRTO2: "ASSIGNMENT_SORTBYRTO2",
  ASSIGNMENT_SORTBYOTR2: "ASSIGNMENT_SORTBYOTR2",

  ASSIGNMENT_SORTBYRTO3: "ASSIGNMENT_SORTBYRTO3",
  ASSIGNMENT_SORTBYOTR3: "ASSIGNMENT_SORTBYOTR3",

  ASSIGNMENT_CREATED_BY: "ASSIGNMENT_CREATED_BY",
  SET_FILTERED_ASSIGNMENT_TEACHERS: "SET_FILTERED_ASSIGNMENT_TEACHERS",

  ASSIGNMENT_COURSE_AND_CLASSROOM_FILTER:
    "ASSIGNMENT_COURSE_AND_CLASSROOM_FILTER",

  SORT_BY_RTO_VIEW_ASSIGNMENT: "SORT_BY_RTO_VIEW_ASSIGNMENT",
  SORT_BY_OTR_VIEW_ASSIGNMENT: "SORT_BY_OTR_VIEW_ASSIGNMENT",

  SORT_BY_SUBMITTED_VIEW_ASSIGNMENT: "SORT_BY_SUBMITTED_VIEW_ASSIGNMENT",
  SORT_BY_PENDING_VIEW_ASSIGNMENT: "SORT_BY_PENDING_VIEW_ASSIGNMENT",

  SORT_BY_GRADED_YES_VIEW_ASSIGNMENT: "SORT_BY_GRADED_YES_VIEW_ASSIGNMENT",
  SORT_BY_GRADED_NO_VIEW_ASSIGNMENT: "SORT_BY_GRADED_NO_VIEW_ASSIGNMENT",
};
