export const GalleryPopupActionTypes = {
    "GALLERY_POPUP_LOADING":"GALLERY_POPUP_LOADING",
    "GALLERY_POPUP_LOADED":"GALLERY_POPUP_LOADED",
    "GALLERY_POPUP_LOADING_ERROR":"GALLERY_POPUP_LOADING_ERROR",
    "GALLERY_POPUP_SHOW":"GALLERY_POPUP_SHOW",
    "GALLERY_POPUP_HIDE":"GALLERY_POPUP_HIDE",
    "GALLERY_POPUP_MORE_LOADING":"GALLERY_POPUP_MORE_LOADING",
    "GALLERY_POPUP_MORE_LOADED":"GALLERY_POPUP_MORE_LOADED",
    "GALLERY_POPUP_MORE_LOADING_ERROR":"GALLERY_POPUP_MORE_LOADING_ERROR",
}