const PAYMENT_MODE_TYPES = {
  PAYMENT_MODE_LIST: "PAYMENT_MODE_LIST",
  POST_BANK_DETAILS: "POST_BANK_DETAILS",
  POST_CHEQUE_DETAILS: "POST_CHEQUE_DETAILS",
  POST_UPI_DETAILS: "POST_UPI_DETAILS",
  POST_PAYPAL_DETAILS: "POST_PAYPAL_DETAILS",
  PAYMENT_LIST_DETAILS: "PAYMENT_LIST_DETAILS",
  UPDATE_PAYMENT_DETAILS: "UPDATE_PAYMENT_DETAILS",
  DELETE_PAYMENT_DETAILS: "DELETE_PAYMENT_DETAILS",
  IFSC_VALIDATOR: "IFSC_VALIDATOR",

  SEND_DATA_STORE: "SEND_DATA_STORE",
  SEND_DATA_RESET: "SEND_DATA_RESET",

  GET_PAYMENT_MODE_LOADING: "GET_PAYMENT_MODE_LOADING",
  GET_PAYMENT_MODE_LOADED: "GET_PAYMENT_MODE_LOADED",
  GET_PAYMENT_MODE_ERROR: "GET_PAYMENT_MODE_ERROR",
  GET_PAYMENT_MODE_RESET: "GET_PAYMENT_MODE_RESET",


  KYC_VERIFICATION_LOADING: "KYC_VERIFICATION_LOADING",
  KYC_VERIFICATION_LOADED: "KYC_VERIFICATION_LOADED",

  SELECTED_KYC_BANK_LOADING: "SELECTED_KYC_BANK_LOADING",
  SELECTED_KYC_BANK_LOADED: "SELECTED_KYC_BANK_LOADED",
  SELECTED_KYC_BANK_RESET: "SELECTED_KYC_BANK_RESET",

  INSITITUTE_EMAIL_CHECK_LOADING: "INSITITUTE_EMAIL_CHECK_LOADING",
  INSITITUTE_EMAIL_CHECK_LOADED: "INSITITUTE_EMAIL_CHECK_LOADED",
  INSITITUTE_EMAIL_CHECK_ERROR: "INSITITUTE_EMAIL_CHECK_ERROR",
  INSITITUTE_EMAIL_CHECK_RESET: "INSITITUTE_EMAIL_CHECK_RESET"

}

export default PAYMENT_MODE_TYPES;