export const REPORTCARD_ACTION_TYPES = {
  ADD_GRADES_LOADING: "ADD_GRADES_LOADING",
  ADD_GRADE_SUCCESS: "ADD_GRADE_SUCCESS",
  ADD_GRADE_ERROR: "ADD_GRADE_ERROR",

  GET_GRADES_LOADING: "GET_GRADES_LOADING",
  GET_GRADES_SUCCESS: "GET_GRADES_SUCCESS",
  GET_GRADES_ERROR: "GET_GRADES_ERROR",

  UPDATE_GRADES_LOADING: "UPDATE_GRADES_LOADING",
  UPDATE_GRADES_SUCCESS: "UPDATE_GRADES_SUCCESS",
  UPDATE_GRADES_ERROR: "UPDATE_GRADES_ERROR",

  GET_REPORT_LOADING: "GET_REPORT_LOADING",
  GET_REPORT_SUCCESS: "GET_REPORT_SUCCESS",
  GET_REPORT_ERROR: "GET_REPORT_ERROR",

  ADD_REPORTCARD_TERM: "ADD_REPORTCARD_TERM",

  GET_TERM_LIST: "GET_TERM_LIST",
  CLEAR_TERM_LIST: "CLEAR_TERM_LIST",

  GET_STUDENT_REPORT: "GET_STUDENT_REPORT",

  UPDATE_STUDENT_REPORT: "UPDATE_STUDENT_REPORT"
};
