export const TeacherSubjectsListActionTypes = {

    TEACHER_SUBJECTS_LIST_LOADING: "TEACHER_SUBJECTS_LIST_LOADING",
    TEACHER_SUBJECTS_LIST_LOADED: "TEACHER_SUBJECTS_LIST_LOADED",
    TEACHER_SUBJECTS_LIST_ERROR: "TEACHER_SUBJECTS_LIST_ERROR",
    TEACHER_SUBJECTS_LIST_RESET: "TEACHER_SUBJECTS_LIST_RESET",

    TEACHER_CLASSROOM_DATA_LOADING: "TEACHER_CLASSROOM_DATA_LOADING",
    TEACHER_CLASSROOM_DATA_LOADED: "TEACHER_CLASSROOM_DATA_LOADED",
    TEACHER_CLASSROOM_DATA_ERROR: "TEACHER_CLASSROOM_DATA_ERROR",
    TEACHER_CLASSROOM_DATA_RESET: "TEACHER_CLASSROOM_DATA_RESET",

    TEACHER_SUBJECTS_LIST_SORTBY_LOADING: "TEACHER_SUBJECTS_LIST_SORTBY_LOADING",
    TEACHER_SUBJECTS_LIST_SORTBY_LOADED: "TEACHER_SUBJECTS_LIST_SORTBY_LOADED",
    TEACHER_SUBJECTS_LIST_SORTBY_ERROR: "TEACHER_SUBJECTS_LIST_SORTBY_ERROR",
    TEACHER_SUBJECTS_LIST_SORTBY_RESET: "TEACHER_SUBJECTS_LIST_SORTBY_RESET",

    TEACHER_SUBJECTS_LIST_SEARCH_LOADING: "TEACHER_SUBJECTS_LIST_SEARCH_LOADING",
    TEACHER_SUBJECTS_LIST_SEARCH_LOADED: "TEACHER_SUBJECTS_LIST_SEARCH_LOADED",
    TEACHER_SUBJECTS_LIST_SEARCH_ERROR: "TEACHER_SUBJECTS_LIST_SEARCH_ERROR",
    TEACHER_SUBJECTS_LIST_SEARCH_RESET: "TEACHER_SUBJECTS_LIST_SEARCH_RESET",

}