export const Access_ControlActionTypes = {
  ACCESS_CONTROL_STAFF_CREATING: "ACCESS_CONTROL_STAFF_CREATING",
  ACCESS_CONTROL_STAFF_CREATED: "ACCESS_CONTROL_STAFF_CREATED",
  ACCESS_CONTROL_STAFF_CREATE_ERROR: "ACCESS_CONTROL_STAFF_CREATE_ERROR",
  ACCESS_CONTROL_STAFF_CREATE_RESET: "ACCESS_CONTROL_STAFF_CREATE_RESET",

  ACCESS_CONTROL_STAFF_LIST_LOADING: "ACCESS_CONTROL_STAFF_LIST_LOADING",
  ACCESS_CONTROL_STAFF_LIST_LOADED: "ACCESS_CONTROL_STAFF_LIST_LOADED",
  ACCESS_CONTROL_STAFF_LIST_ERROR: "ACCESS_CONTROL_STAFF_LIST_ERROR",
  ACCESS_CONTROL_STAFF_LIST_RESET: "ACCESS_CONTROL_STAFF_LIST_RESET",

}