export const SERVICESTYPES = {
  SERVICESREAD: "SERVICESREAD",
  POSTSERVICE: "POSTSERVICE",
  SERVICESUPDATE : "SERVICESUPDATE",
  SERVICESLOADING : "SERVICESLOADING",
  SERVICESLOADED : "SERVICESLOADED",
  RESETSERVICES : "RESETSERVICES",
  DELETESERVICE: "DELETESERVICE",
  SEARCHSERVICE:"SEARCHSERVICE",
  POSTSERVICELOADING:"POSTSERVICELOADING",
  POST_SERVICE_LOADING_SAVE : "POST_SERVICE_LOADING_SAVE",
  SORTSERVICE: "SORTSERVICE",
  SERVICES_UPDATE_SELECTION : "SERVICES_UPDATE_SELECTION",
  SERVICES_UPDATE_SELECTION_CLEAR :"SERVICES_UPDATE_SELECTION_CLEAR",
  SERVICES_UPDATE_SELECTION_LOADING: "SERVICES_UPDATE_SELECTION_LOADING",
  SERVICE_LIST_UPDATE : "SERVICE_LIST_UPDATE",
  SERVICE_UPDATING : "SERVICE_UPDATING",

  SERVICES_UPDATING_CLEAR: "SERVICES_UPDATING_CLEAR",

}