export const BUSINESS_INFO = {
  //EDITOVERVIEW
  PATCH_INSTITUTE_INFO_EDIT_LOADING: "PATCH_INSTITUTE_INFO_EDIT_LOADING",
  PATCH_INSTITUTE_INFO_EDIT_LOADED: "PATCH_INSTITUTE_INFO_EDIT_LOADED",
  PATCH_INSTITUTE_INFO_EDIT_ERROR: "PATCH_INSTITUTE_INFO_EDIT_ERROR",
  PATCH_INSTITUTE_INFO_EDIT_RESET: "PATCH_INSTITUTE_INFO_EDIT_RESET",

  GET_INSTITUTE_DATA_LOADING: "GET_INSTITUTE_DATA_LOADING",
  GET_INSTITUTE_DATA_LOADED: "GET_INSTITUTE_DATA_LOADED",
  GET_INSTITUTE_DATA_ERROR: "GET_INSTITUTE_DATA_ERROR",
  GET_INSTITUTE_DATA_RESET: "GET_INSTITUTE_DATA_RESET",

  GET_BUSINESS_CATEGORY_LOADING: "GET_BUSINESS_CATEGORY_LOADING",
  GET_BUSINESS_CATEGORY_LOADED: "GET_BUSINESS_CATEGORY_LOADED",
  GET_BUSINESS_CATEGORY_ERROR: "GET_BUSINESS_CATEGORY_ERROR",
  GET_BUSINESS_CATEGORY_RESET: "GET_BUSINESS_CATEGORY_RESET",


  GET_ECOM_WEBSITE_LOADING: "GET_ECOM_WEBSITE_LOADING",
  GET_ECOM_WEBSITE_LOADED: "GET_ECOM_WEBSITE_LOADED",
  GET_ECOM_WEBSITE_ERROR: "GET_ECOM_WEBSITE_ERROR",
  GET_ECOM_WEBSITE_RESET: "GET_ECOM_WEBSITE_RESET",

  POST_SMTP_TEST_MAIL_LOADING: "POST_SMTP_TEST_MAIL_LOADING",
  POST_SMTP_TEST_MAIL_LOADED: "POST_SMTP_TEST_MAIL_LOADED",
  POST_SMTP_TEST_MAIL_ERROR: "POST_SMTP_TEST_MAIL_ERROR",
  POST_SMTP_TEST_MAIL_RESET: "POST_SMTP_TEST_MAIL_RESET",


}