export const ONLINE_CLASS_TYPE = {
  ONLINE_CLASS_READ_LOADING: "ONLINE_CLASS_READ_LOADING",
  ONLINE_CLASS_READ_LOADED: "ONLINE_CLASS_READ_LOADED",
  ONLINE_CLASS_READ_ERROR: "ONLINE_CLASS_READ_ERROR",
  ONLINE_CLASS_READ_RESET: "ONLINE_CLASS_READ_RESET",

  ZOOM_VERIFICATION_LOADING: "ZOOM_VERIFICATION_LOADING",
  ZOOM_VERIFICATION_LOADED: "ZOOM_VERIFICATION_LOADED",
  ZOOM_VERIFICATION_ERROR: "ZOOM_VERIFICATION_ERROR",
  ZOOM_VERIFICATION_RESET: "ZOOM_VERIFICATION_RESET",


  ONLINE_CLASS_READ_ADMIN_LOADING: "ONLINE_CLASS_READ_ADMIN_LOADING",
  ONLINE_CLASS_READ_ADMIN_LOADED: "ONLINE_CLASS_READ_ADMIN_LOADED",
  ONLINE_CLASS_READ_ADMIN_ERROR: "ONLINE_CLASS_READ_ADMIN_ERROR",
  ONLINE_CLASS_READ_ADMIN_RESET: "ONLINE_CLASS_READ_ADMIN_RESET",


  STUDENT_ONLINE_CLASS_READ_LOADING: " STUDENT_ONLINE_CLASS_READ_LOADING",
  STUDENT_ONLINE_CLASS_READ_LOADED: " STUDENT_ONLINE_CLASS_READ_LOADED",
  STUDENT_ONLINE_CLASS_READ_ERROR: " STUDENT_ONLINE_CLASS_READ_ERROR",
  STUDENT_ONLINE_CLASS_READ_RESET: " STUDENT_ONLINE_CLASS_READ_RESET",


  STUDENT_LIST_LOADING: "STUDENT_LIST_LOADING",
  STUDENT_LIST_LOADED: "STUDENT_LIST_LOADED",
  STUDENT_LIST_ERROR: "STUDENT_LIST_ERROR",
  STUDENT_LIST_RESET: "STUDENT_LIST_RESET",


  ATTENDEES_LIST_LOADING: "ATTENDEES_LIST_LOADING",
  ATTENDEES_LIST_LOADED: "ATTENDEES_LIST_LOADED",
  ATTENDEES_LIST_ERROR: "ATTENDEES_LIST_ERROR",
  ATTENDEES_LIST_RESET: "ATTENDEES_LIST_RESET",



  ONLINE_CLASS_READ: "ONLINE_CLASS_READ",

  CLASS_FILTER_LOADING: "CLASS_FILTER_LOADING",
  CLASS_FILTER_LOADED: "CLASS_FILTER_LOADED",
  CLASS_FILTER_ERROR: "CLASS_FILTER_ERROR",
  CLASS_FILTER_RESET: "CLASS_FILTER_RESET",

  ONLINE_CLASS_READSINGLE_LOADING: "ONLINE_CLASS_READSINGLE_LOADING",
  ONLINE_CLASS_READSINGLE_LOADED: "ONLINE_CLASS_READSINGLE_LOADED",
  ONLINE_CLASS_READSINGLE_ERROR: "ONLINE_CLASS_READSINGLE_ERROR",
  ONLINE_CLASS_READSINGLE_RESET: "ONLINE_CLASS_READSINGLE_RESET",


  // class create
  ONLINE_CLASS_CREATE_LOADING: "ONLINE_CLASS_CREATE_LOADING",
  ONLINE_CLASS_CREATE_LOADED: "ONLINE_CLASS_CREATE_LOADED",
  ONLINE_CLASS_CREATE_ERROR: "ONLINE_CLASS_CREATE_ERROR",
  ONLINE_CLASS_CREATE_RESET: "ONLINE_CLASS_CREATE_RESET",


  ONLINE_CLASS_EDIT_LOADING: "ONLINE_CLASS_EDIT_LOADING",
  ONLINE_CLASS_EDIT_LOADED: "ONLINE_CLASS_EDIT_LOADED",
  ONLINE_CLASS_EDIT_ERROR: "ONLINE_CLASS_EDIT_ERROR",
  ONLINE_CLASS_EDIT_RESET: "ONLINE_CLASS_EDIT_RESET",

  ONLINE_CLASS_REMOVE_LOADING: "ONLINE_CLASS_REMOVE_LOADING",
  ONLINE_CLASS_REMOVE_LOADED: "ONLINE_CLASS_REMOVET_LOADED",
  ONLINE_CLASS_REMOVE_ERROR: "ONLINE_CLASS_REMOVE_ERROR",
  ONLINE_CLASS_REMOVE_RESET: "ONLINE_CLASS_REMOVE_RESET",

  ONLINE_CLASS_CREATE: "ONLINE_CLASS_CREATE",
  ONLINE_CLASS_EDIT: "ONLINE_CLASS_EDIT",
  ONLINE_CLASS_DELETE: "ONLINE_CLASS_DELETE",
  SEARCH_CLASS: "SEARCH_CLASS",
  ONLINE_CLASS_SORT_BY_DHTL: "ONLINE_CLASS_SORT_BY_DHTL",
  ONLINE_CLASS_SORT_BY_DLTH: "ONLINE_CLASS_SORT_BY_DLTH",
  SORT_BY_RTO: "SORT_BY_RTO",
  SORT_BY_OTR: "SORT_BY_OTR",
  SORT_BY_ZOOM: "SORT_BY_ZOOM",
  SORT_BY_MEET: "SORT_BY_MEET",
  SORT_BY_HTLA: "SORT_BY_HTLA",
  SORT_BY_LTHA: "SORT_BY_LTHA",
  SORT_BY_TOGGLE: "SORT_BY_TOGGLE",
  COURSE_AND_CLASSROOM: "COURSE_AND_CLASSROOM",
  SET_ONLINE_CLASSROOM: "SET_ONLINE_CLASSROOM",
  SET_ONLINE_COURSE: "SET_ONLINE_COURSE",
  COURSE_AND_CLASSROOM_FILTER: "COURSE_AND_CLASSROOM_FILTER",
  GET_LIST_OF_CREATED_BY: "GET_LIST_OF_CREATED_BY",
  SET_FILTERED_TEACHERS: "SET_FILTERED_TEACHERS",
  CLASSROOM_ASSIGNED: "CLASSROOM_ASSIGNED",
  GOOGLE_MEET_RESPONSE_DATA: "GOOGLE_MEET_RESPONSE_DATA",
  GOOGLE_MEET_RESPONSE_DATA_EDIT: "GOOGLE_MEET_RESPONSE_DATA_EDIT",
  ONLINE_CLASS_STUDENT_LIST: "ONLINE_CLASS_STUDENT_LIST",
  POST_ONLINE_CLASS_STUDENT_LIST: "POST_ONLINE_CLASS_STUDENT_LIST",
  SET_SELECTED_STUDENT_DATA: "SET_SELECTED_STUDENT_DATA",

  RESET_ONLINE_CLASSES: "RESET_ONLINE_CLASSES"
};
