export const Reseller={

    RESELLER_API_CALL_SUCCESS:"RESELLER_API_CALL_SUCCESS",
    RESELLER_API_CALL_LOADING:"RESELLER_API_CALL_LOADING",
    RESELLER_API_CALL_ERROR:"RESELLER_API_CALL_ERROR",

}