export const Ecomm_Currency_ActionTypes = {
  GET_CURRENCY_LIST_LOADING: "GET_CURRENCY_LIST_LOADING",
  GET_CURRENCY_LIST_LOADED: "GET_CURRENCY_LIST_LOADED",
  GET_CURRENCY_LIST_ERROR: "GET_CURRENCY_LIST_ERROR",
  GET_CURRENCY_LIST_RESET: "GET_CURRENCY_LIST_RESET",

  POST_CURRENCY_DATA_LOADING: "POST_CURRENCY_DATA_LOADING",
  POST_CURRENCY_DATA_LOADED: "POST_CURRENCY_DATA_LOADED",
  POST_CURRENCY_DATA_ERROR: "POST_CURRENCY_DATA_ERROR",
  POST_CURRENCY_DATA_RESET: "POST_CURRENCY_DATA_RESET",

  GET_SELECTED_CURRENCY_LOADING: "GET_SELECTED_CURRENCY_LOADING",
  GET_SELECTED_CURRENCY_LOADED: "GET_SELECTED_CURRENCY_LOADED",
  GET_SELECTED_CURRENCY_ERROR: "GET_SELECTED_CURRENCY_ERROR",
  GET_SELECTED_CURRENCY_RESET: "GET_SELECTED_CURRENCY_RESET",

  DELETE_CURRENCY_DATA_LOADING: "DELETE_CURRENCY_DATA_LOADING",
  DELETE_CURRENCY_DATA_LOADED: "DELETE_CURRENCY_DATA_LOADED",
  DELETE_CURRENCY_DATA_ERROR: "DELETE_CURRENCY_DATA_ERROR",
  DELETE_CURRENCY_DATA_RESET: "DELETE_CURRENCY_DATA_RESET",
}