export const MULTI_SELECT_DROPDOWN_AT = {

  REMOVE_SELECTED_ENTRY: "REMOVE_SELECTED_ENTRY",
  ADD_SELECTED_ENTRY: "ADD_SELECTED_ENTRY",
  RESET_SELECTED_ENTRY: "RESET_SELECTED_ENTRY",
  ALL_ENTRY_SELECTED: "ALL_ENTRY_SELECTED",
  REMOVE_SELECTED_ENTRY_SWITCH: "REMOVE_SELECTED_ENTRY_SWITCH",
  ADD_SELECTED_ENTRY_SWITCH: "ADD_SELECTED_ENTRY_SWITCH",
  RESET_SELECTED_ENTRY_SWITCH: "RESET_SELECTED_ENTRY_SWITCH",
  ALL_ENTRY_SELECTED_SWITCH: "ALL_ENTRY_SELECTED_SWITCH",

  RESET_MULTI_SELECT: "RESET_MULTI_SELECT",

  REMOVE_SELECTED_ENTRY_STUDENTS: "REMOVE_SELECTED_ENTRY_STUDENTS",
  ADD_SELECTED_ENTRY_STUDENTS: "ADD_SELECTED_ENTRY_STUDENTS",
  RESET_SELECTED_ENTRY_STUDENTS: "RESET_SELECTED_ENTRY_STUDENTS",
  ALL_ENTRY_SELECTED_STUDENTS: "ALL_ENTRY_SELECTED_STUDENTS",
  REMOVE_SELECTED_ENTRY_SWITCH_STUDENTS: "REMOVE_SELECTED_ENTRY_SWITCH_STUDENTS",
  ADD_SELECTED_ENTRY_SWITCH_STUDENTS: "ADD_SELECTED_ENTRY_SWITCH_STUDENTS",
  RESET_SELECTED_ENTRY_SWITCH_STUDENTS: "RESET_SELECTED_ENTRY_SWITCH_STUDENTS",
  ALL_ENTRY_SELECTED_SWITCH_STUDENTS: "ALL_ENTRY_SELECTED_SWITCH_STUDENTS",

}