export const onlineExamActionTypes = {
  OES_INFO_LOADING: "OES_INFO_LOADING",
  OES_INFO_LOADED: "OES_INFO_LOADED",
  OES_INFO_LOADING_ERROR: "OES_INFO_LOADING_ERROR",
  OES_INFO_RESET: "OES_INFO_RESET",

  OES_RESULT_LOADING: "OES_RESULT_LOADING",
  OES_RESULT_LOADED: "OES_RESULT_LOADED",
  OES_RESULT_LOADING_ERROR: "OES_RESULT_LOADING_ERROR",
  OES_RESULT_RESET: "OES_RESULT_RESET",

  OES_POST_EXAM: "OES_POST_EXAM",
  OES_POST_EXAM_LOADING: "OES_POST_EXAM_LOADING",
  OES_GRACE_EXAM_LOADING: "OES_GRACE_EXAM_LOADING",
  OES_GRACE_EXAM: "OES_GRACE_EXAM",
  OES_PATCH_ANSWER: "OES_PATCH_ANSWER",
  OES_PATCH_ANSWER_LOADING: "OES_PATCH_ANSWER_LOADING",
  
  OES_PATCH_ANSWER_RESET: "OES_PATCH_ANSWER_RESET",

  OES_EXAM_SUBMIT: "OES_EXAM_SUBMIT",
  OES_EXAM_SUBMIT_LOADING: "OES_EXAM_SUBMIT_LOADING",
  OES_EXAM_SUBMIT_RESET: "OES_EXAM_SUBMIT_RESET",
  OES_GET_ANSWER: "OES_GET_ANSWER",
  OES_GET_ANSWER_LOADING: "OES_GET_ANSWER_LOADING",
  RESET_ONLINE_EXAM_STUDENT: "RESET_ONLINE_EXAM_STUDENT",
  RESET_OES_LOADED_DETAIL: "RESET_OES_LOADED_DETAIL",
  OES_EXAM_UPLOAD_SET: "OES_EXAM_UPLOAD_SET",
  OES_EXAM_UPLOAD_RESET: "OES_EXAM_UPLOAD_RESET",
  OES_EXAM_STUDENT_UPLOAD_SET: "OES_EXAM_STUDENT_UPLOAD_SET",
  OES_EXAM_STUDENT_UPLOAD_RESET: "OES_EXAM_STUDENT_UPLOAD_RESET",

  // update timer 
  OES_UPDATE_TIMER: "OES_UPDATE_TIMER",
  // attempted questions
  OES_ATTEMPTED_QUESTION: "OES_ATTEMPTED_QUESTION",

  OES_ASSIGN_LOADING: "OES_ASSIGN_LOADING",
  OES_ASSIGN_LOADED: "OES_ASSIGN_LOADED",
  OES_ASSIGN_LOADING_ERROR: "OES_ASSIGN_LOADING_ERROR",
  OES_RESET_WARNING_TIMER:"OES_RESET_WARNING_TIMER"

};
