export const AdmissionActionTypes = {
    ADMISSION_CREATING: "ADMISSION_CREATING",
    ADMISSION_CREATING_SAVE: "ADMISSION_CREATING_SAVE",
    ADMISSION_CREATED: "ADMISSION_CREATED",
    ADMISSION_CREATE_ERROR: "ADMISSION_CREATE_ERROR",
    ADMISSION_CREATE_RESET: "ADMISSION_CREATE_RESET",

    ADMISSION_LIST_LOADING: "ADMISSION_LIST_LOADING",
    ADMISSION_LIST_LOADED: "ADMISSION_LIST_LOADED",
    ADMISSION_LIST_ERROR: "ADMISSION_LIST_ERROR",
    ADMISSION_LIST_RESET: "ADMISSION_LIST_RESET",

    ADMISSION_APPLICANT_LIST_LOADING: "ADMISSION_APPLICANT_LIST_LOADING",
    ADMISSION_APPLICANT_LIST_LOADED: "ADMISSION_APPLICANT_LIST_LOADED",
    ADMISSION_APPLICANT_LIST_ERROR: "ADMISSION_APPLICANT_LIST_ERROR",
    ADMISSION_APPLICANT_LIST_RESET: "ADMISSION_APPLICANT_LIST_RESET",

    ADMISSION_LIST_SELECTION_LOADING: "ADMISSION_LIST_SELECTION_LOADING",
    ADMISSION_LIST_SELECTION_LOADED: "ADMISSION_LIST_SELECTION_LOADED",
    ADMISSION_LIST_SELECTION_ERROR: "ADMISSION_LIST_SELECTION_ERROR",
    ADMISSION_LIST_SELECTION_RESET: "ADMISSION_LIST_SELECTION_RESET",


    ADMISSION_UPDATING: "ADMISSION_UPDATING",
    ADMISSION_UPDATED: "ADMISSION_UPDATED",
    ADMISSION_UPDATE_ERROR: "ADMISSION_UPDATE_ERROR",
    ADMISSION_UPDATE_RESET: "ADMISSION_UPDATE_RESET",

    ADMISSION_SELECTION_UPDATING: "ADMISSION_SELECTION_UPDATING",
    ADMISSION_SELECTION_UPDATED: "ADMISSION_SELECTION_UPDATED",
    ADMISSION_UPDATE_SELECTION_ERROR: "ADMISSION_UPDATE_SELECTION_ERROR",

    ADMISSION_DELETE_LOADING: "ADMISSION_DELETE_LOADING",
    ADMISSION_DELETE: "ADMISSION_DELETE",
    ADMISSION_DELETE_RESET: "ADMISSION_DELETE_RESET",
    ADMISSION_DELETE_ERROR: "ADMISSION_DELETE_ERROR",

    ADMISSION_UPDATE_LIST_STATUS: "ADMISSION_UPDATE_LIST_STATUS",

    ADMISSION_APPLICANT_UPDATE_LIST_STATUS: "ADMISSION_APPLICANT_UPDATE_LIST_STATUS",

    ADMISSION_CANCEL: "ADMISSION_CANCEL",

    ADMISSION_DETAIL_LOADING: "ADMISSION_DETAIL_LOADING",
    ADMISSION_DETAIL_LOADED: "ADMISSION_DETAIL_LOADED",
    ADMISSION_DETAIL_LOADING_ERROR: "ADMISSION_DETAIL_LOADING_ERROR",
    ADMISSION_DETAIL_LOADING_RESET: "ADMISSION_DETAIL_LOADING_RESET",

    ADMISSION_TITLE_LOADING: "ADMISSION_TITLE_LOADING",
    ADMISSION_TITLE_LOADED: " ADMISSION_TITLE_LOADED",
    ADMISSION_TITLE_LOADING_ERROR: " ADMISSION_TITLE_LOADING_ERROR",
    ADMISSION_TITLE_LOADING_RESET: " ADMISSION_TITLE_LOADING_RESET",
}