export const USER_DETAIL_POPUP = {
  GET_USER_LOADING: "GET_USER_LOADING",
  GET_USER_LOADED: "GET_USER_LOADED",
  GET_USER_ERROR: "GET_USER_ERROR",
  // GET_USER_RESET: "GET_USER_RESET"
  POST_USER_LOADING: "POST_USER_LOADING",
  POST_USER_LOADED: "POST_USER_LOADED",
  POST_USER_ERROR: "POST_USER_ERROR",
  POST_USER_RESET: "POST_USER_RESET",

  POST_USER_BASIC_LOADING: "POST_USER_BASIC_LOADING",
  POST_USER_BASIC_LOADED: "POST_USER_BASIC_LOADED",
  POST_USER_BASIC_ERROR: "POST_USER_BASIC_ERROR",
  POST_USER_BASIC_RESET: "POST_USER_BASIC_RESET",

  GET_USER_BASIC_LOADING: "GET_USER_BASIC_LOADING",
  GET_USER_BASIC_LOADED: "GET_USER_BASIC_LOADED",
  GET_USER_BASIC_ERROR: "GET_USER_BASIC_ERROR",
  // GET_USER_BASIC_RESET: "GET_USER_BASIC_RESET",

};

