export const JOIN_CLASS_TYPE = {
  JOIN_CLASS_READ: "JOIN_CLASS_READ",
  JOIN_CLASS_READ_LOADING:"JOIN_CLASS_READ_LOADING",


  ASIGNED_STUDENT_LOADING: "ASIGNED_STUDENT_LOADING",
  ASIGNED_STUDENT_LOADED: "ASIGNED_STUDENT_LOADED",
  ASIGNED_STUDENT_ERROR: "ASIGNED_STUDENT_ERROR",
  ASIGNED_STUDENT_RESET: "ASIGNED_STUDENT_RESET",

  SEARCH_CLASS: "SEARCH_CLASS",
  UPCOMING_CLASS: "UPCOMING_CLASS",
  ONGOING_CLASS: "ONGOING_CLASS",
  ATTENDED_CLASS: "ATTENDED_CLASS",
  MISSED_CLASS: "MISSED_CLASS",
  CLASS_CREATED_BY_SELF: "CLASS_CREATED_BY_SELF",
  CLASS_CREATED_BY_INSTITUTE: "CLASS_CREATED_BY_INSTITUTE",
  CLASS_CREATED_BY_OTHER: "CLASS_CREATED_BY_OTHER",
  STUDENT_COURSE_AND_CLASSROOM: "STUDENT_COURSE_AND_CLASSROOM",
  SORT_BY_TOGGLE_VALUE_STUDENT: "SORT_BY_TOGGLE_VALUE_STUDENT",
  GET_UPCOMING_CLASSES_LOADING:"GET_UPCOMING_CLASSES_LOADING",
  GET_UPCOMING_CLASSES:"GET_UPCOMING_CLASSES",
  POST_STUDENT_JOIN_CLASS_TIMING:"POST_STUDENT_JOIN_CLASS_TIMING",
  POST_STUDENT_JOIN_CLASS_TIMING_LOADING:"POST_STUDENT_JOIN_CLASS_TIMING_LOADING",
  POST_STUDENT_JOIN_CLASS_TIMING_RESET:"POST_STUDENT_JOIN_CLASS_TIMING_RESET",
  ONLINE_CLASS_FILTER_LOADED:"ONLINE_CLASS_FILTER_LOADED",
  CLASS_FILTER_LOADING:"CLASS_FILTER_LOADING"
};
