export const LOGINTYPES = {
  EMAIL_LOGIN_LOADING:"EMAIL_LOGIN_LOADING",
  EMAIL_LOGIN_SUCCESS:"EMAIL_LOGIN_SUCCESS",
  EMAIL_LOGIN_ERROR:"EMAIL_LOGIN_ERROR",
  EMAIL_LOGIN_RESET:"EMAIL_LOGIN_RESET"
}