export const TeacherCourseActionTypes = {
  GET_TEACHER_COURSES_LIST_LOADING:"GET_STUDENT_COURSES_LIST_LOADING",
  GET_TEACHER_COURSES_LIST_LOADED:"GET_STUDENT_COURSES_LIST_LOADED",
  GET_TEACHER_COURSES_LIST_RESET:"GET_STUDENT_COURSES_LIST_RESET",
  

  SORT_BY_TEACHER_COURSES_LIST:"SORT_BY_TEACHER_COURSES_LIST",

  GET_TEACHER_COURSE_DETAILS:"GET_STUDENT_COURSE_DETAILS",
  GET_TEACHER_COURSE_DETAILS_LOADING:"GET_STUDENT_COURSE_DETAILS_LOADING",
  GET_TEACHER_COURSE_DETAILS_RESET:"GET_STUDENT_COURSE_DETAILS_RESET",

  DELETE_TEACHER_COURSE_LOADING:"DELETE_TEACHER_COURSE_LOADING",
  DELETE_TEACHER_COURSE:"DELETE_TEACHER_COURSE",
  DELETE_TEACHER_COURSE_RESET:"DELETE_TEACHER_COURSE_RESET",

  FILTER_COURSE_CLASSROOM_TEACHER_LIST:"FILTER_COURSE_CLASSROOM_TEACHER_LIST",
  CREATED_BY_FILTER_TEACHER_LIST:"CREATED_BY_FILTER_TEACHER_LIST"
}