export const REQUEST_TYPE = {
  GET_FACULTY: "GET_FACULTY",
  POST_FACULTY: "POST_FACULTY",
  UPDATE_FACULTY: "UPDATE_FACULTY",
  FACULTY_LOADING: "FACULTY_LOADING",
  DELETE_FACULTY: "DELETE_FACULTY",
  GET_FACULTY_BY_ID: "GET_FACULTY_BY_ID",
  GET_FACULTY_BY_ID_LOADING: "GET_FACULTY_BY_ID_LOADING",
  RESET_SINGLE_FACULTY_INFO: "RESET_SINGLE_FACULTY_INFO",
  FACULTY_CREATING:"FACULTY_CREATING",
  FACULTY_UPDATING : "FACULTY_UPDATING",
};
