export const INS_GAL_ACTION_TYPES = {
    INS_GAL_LOADING:"INS_GAL_LOADING",
    INS_GAL_LOADED:"INS_GAL_LOADED",
    INS_GAL_LOADING_ERROR:"INS_GAL_LOADING_ERROR",
    INS_GAL_MORE_LOADING:"INS_GAL_MORE_LOADING",
    INS_GAL_MORE_LOADED:"INS_GAL_MORE_LOADED",
    INS_GAL_MORE_LOADING_ERROR:"INS_GAL_MORE_LOADING_ERROR",
}