export const Business_Notification_Type = {
  GET_ALL_BUSINESS_NOTIFICATIONS_LOADING: "GET_ALL_BUSINESS_NOTIFICATIONS_LOADING",
  GET_ALL_BUSINESS_NOTIFICATIONS_LOADED: "GET_ALL_BUSINESS_NOTIFICATIONS_LOADED",
  GET_ALL_BUSINESS_NOTIFICATIONS_RESET: "GET_ALL_BUSINESS_NOTIFICATIONS_RESET",
  GET_ALL_BUSINESS_NOTIFICATIONS_ERROR: "GET_ALL_BUSINESS_NOTIFICATIONS_ERROR",
  RESET_SEEN_NOTIFICATIONS: "RESET_SEEN_NOTIFICATIONS",

  UPDATE_BUSINESS_NOTIFICATIONS: "UPDATE_BUSINESS_NOTIFICATIONS"
};
