export const CUSTOMERLOGINTYPES = {
  CUSTOMER_LOGIN_LOADING: "CUSTOMER_LOGIN_LOADING",
  CUSTOMER_LOGIN_SUCCESS: "CUSTOMER_LOGIN_SUCCESS",
  CUSTOMER_LOGIN_RESET: "CUSTOMER_LOGIN_RESET",
  CUSTOMER_LOGIN_ERROR: "CUSTOMER_LOGIN_ERROR"
}