export const COURSEHEADERTYPES = {
  COURSEHEADERREAD: "COURSEHEADERREAD",
  COURSEHEADERPOST : "COURSEHEADERPOST",
  COURSEHEADERUPDATE : "COURSEHEADERUPDATE",
  COURSEHEADERLOADING : "COURSEHEADERLOADING",
  POSTCOURSELOADING: "POSTCOURSELOADING",
  RESETCOURSEHEADER : "RESETCOURSEHEADER",
}