export const EDITSTUDENTLIST = {

    EDIT_COURSE_LIST_READ: "EDIT_COURSE_LIST_READ",
    EDIT_STUDENT_LIST_USERNAME_READ: "EDIT_STUDENT_LIST_USERNAME_READ",
    EDIT_STUDENT_LIST_READ: "EDIT_STUDENT_LIST_READ",
    EDIT_STUDENT_LIST_READ_RESET: "EDIT_STUDENT_LIST_READ_RESET",
    EDIT_STUDENT_LIST_CREATE: "EDIT_STUDENT_LIST_CREATE",
    EDIT_STUDENT_LIST_EDIT: "EDIT_STUDENT_LIST_EDIT",
    EDIT_STUDENT_LIST_DELETE: "EDIT_STUDENT_LIST_DELETE",
    EDIT_STUDENT_LIST_UPDATE_SELECTION: "EDIT_STUDENT_LIST_UPDATE_SELECTION",
    EDIT_STUDENT_LIST_UPDATE: "EDIT_STUDENT_LIST_UPDATE",
    EDIT_STUDENT_LIST_UPDATE_ERROR: "EDIT_STUDENT_LIST_UPDATE_ERROR",
    EDIT_STUDENT_LIST_UPDATED: "EDIT_STUDENT_LIST_UPDATED",
    EDIT_STUDENT_LIST_COUNT: "EDIT_STUDENT_LIST_COUNT",

}