export const SECTIONTITLETYPES = {
  SECTIONTITLEREAD: "SECTIONTITLEREAD",
  SECTIONTITLEUPDATE : "SECTIONTITLEUPDATE",
  SECTIONTITLELOADING : "SECTIONTITLELOADING",
  SECTIONTITLELOADED : "SECTIONTITLELOADED",
  RESETSECTIONTITLE : "RESETSECTIONTITLE",
}