export const examSubmissionActionTypes = {
    "EXAM_SUB_LIST_LOADING":"EXAM_SUB_LIST_LOADING",
    "EXAM_SUB_LIST_LOADED":"EXAM_SUB_LIST_LOADED",
    "EXAM_SUB_LIST_LOADING_ERROR":"EXAM_SUB_LIST_LOADING_ERROR",
    "EXAM_SUB_LIST_MORE_LOADING":"EXAM_SUB_LIST_MORE_LOADING",
    "EXAM_SUB_LIST_MORE_LOADED":"EXAM_SUB_LIST_MORE_LOADED",
    "EXAM_SUB_LIST_MORE_LOADING_ERROR":"EXAM_SUB_LIST_MORE_LOADING_ERROR"
}