export const REQUEST_TYPE = {
  GET_FEE: "GET_FEE",
  POST_FEE: "POST_FEE",
  UPDATE_FEE: "UPDATE_FEE",
  FEE_LOADING: "FEE_LOADING",
  DELETE_FEE: "DELETE_FEE",
  SORT_BY_LTH: "SORT_BY_LTH",
  SORT_BY_HTL: "SORT_BY_HTL",
  SORT_BY_ACTIVE: "SORT_BY_ACTIVE",
  SORT_BY_INACTIVE: "SORT_BY_INACTIVE",
  SEARCH_FEE: "SEARCH_FEE",
  GET_PAYMENT_MODE: "GET_PAYMENT_MODE",
  SINGLE_FEE: "SINGLE_FEE",
  SINGLE_FEE_LOADING: "SINGLE_FEE_LOADING",
  SORT_BY_SAVED: "SORT_BY_SAVED",
  RESET_SINGLE_FEE_INFO: "RESET_SINGLE_FEE_INFO",
  UPDATE_SINGLE_FEE: "UPDATE_SINGLE_FEE",
  SORT_BY_FEETYPE: "SORT_BY_FEETYPE"
};
