export const Ecomm_Admin_ActionTypes = {
  ECOMM_ADMIN_CATEGORY_CREATING: "ECOMM_ADMIN_CATEGORY_CREATING",
  ECOMM_ADMIN_CATEGORY_CREATED: "ECOMM_ADMIN_CATEGORY_CREATED",
  ECOMM_ADMIN_CATEGORY_CREATE_ERROR: "ECOMM_ADMIN_CATEGORY_CREATE_ERROR",
  ECOMM_ADMIN_CATEGORY_CREATE_RESET: "ECOMM_ADMIN_CATEGORY_CREATE_RESET",

  ECOMM_ADMIN_CATEGORY_LIST_LOADING: "ECOMM_ADMIN_CATEGORY_LIST_LOADING",
  ECOMM_ADMIN_CATEGORY_LIST_LOADED: "ECOMM_ADMIN_CATEGORY_LIST_LOADED",
  ECOMM_ADMIN_CATEGORY_LIST_ERROR: "ECOMM_ADMIN_CATEGORY_LIST_ERROR",
  ECOMM_ADMIN_CATEGORY_LIST_RESET: "ECOMM_ADMIN_CATEGORY_LIST_RESET",

  ECOMM_ADMIN_CATEGORY_EDIT_LOADING: "ECOMM_ADMIN_CATEGORY_EDIT_LOADING",
  ECOMM_ADMIN_CATEGORY_EDIT_LOADED: "ECOMM_ADMIN_CATEGORY_EDIT_LOADED",
  ECOMM_ADMIN_CATEGORY_EDIT_ERROR: "ECOMM_ADMIN_CATEGORY_EDIT_ERROR",
  ECOMM_ADMIN_CATEGORY_EDIT_RESET: "ECOMM_ADMIN_CATEGORY_EDIT_RESET",

  ECOMM_ADMIN_CATEGORY_EDIT_POSITION_LOADING: "ECOMM_ADMIN_CATEGORY_EDIT_POSITION_LOADING",
  ECOMM_ADMIN_CATEGORY_EDIT_POSITION_LOADED: "ECOMM_ADMIN_CATEGORY_EDIT_POSITION_LOADED",
  ECOMM_ADMIN_CATEGORY_EDIT_POSITION_ERROR: "ECOMM_ADMIN_CATEGORY_EDIT_POSITION_ERROR",
  ECOMM_ADMIN_CATEGORY_EDIT_POSITION_RESET: "ECOMM_ADMIN_CATEGORY_EDIT_POSITION_RESET",

  ECOMM_ADMIN_CATEGORY_EDIT_DRAG_LOADING: "ECOMM_ADMIN_CATEGORY_EDIT_DRAG_LOADING",
  ECOMM_ADMIN_CATEGORY_EDIT_DRAG_LOADED: "ECOMM_ADMIN_CATEGORY_EDIT_DRAG_LOADED",
  ECOMM_ADMIN_CATEGORY_EDIT_DRAG_ERROR: "ECOMM_ADMIN_CATEGORY_EDIT_DRAG_ERROR",
  ECOMM_ADMIN_CATEGORY_EDIT_DRAG_RESET: "ECOMM_ADMIN_CATEGORY_EDIT_DRAG_RESET",

  ECOMM_ADMIN_CATEGORY_EDIT_SELECTION_LOADING: "ECOMM_ADMIN_CATEGORY_EDIT_SELECTION_LOADING",
  ECOMM_ADMIN_CATEGORY_EDIT_SELECTION_LOADED: "ECOMM_ADMIN_CATEGORY_EDIT_SELECTION_LOADED",
  ECOMM_ADMIN_CATEGORY_EDIT_SELECTION_ERROR: "ECOMM_ADMIN_CATEGORY_EDIT_SELECTION_ERROR",
  ECOMM_ADMIN_CATEGORY_EDIT_SELECTION_RESET: "ECOMM_ADMIN_CATEGORY_EDIT_SELECTION_RESET",

  ECOMM_ADMIN_CATEGORY_EXPAND_LIST: "ECOMM_ADMIN_CATEGORY_EXPAND_LIST",
  ECOMM_ADMIN_CATEGORY_EXPAND_LIST_REST: "ECOMM_ADMIN_CATEGORY_EXPAND_LIST_REST",

}