const communityType = {

    ASKED_QUESTIONS: 'ASKED_QUESTIONS',
    LIST_QUESTIONS: 'LIST_QUESTIONS',
    LIST_MORE_QUESTIONS: 'LIST_MORE_QUESTIONS',
    LIST_ANSWERS: 'LIST_ANSWERS',
    DELETE_QUESTION: 'DELETE_QUESTION',
    FIND_QUESTION_LOADING: 'FIND_QUESTION_LOADING',
    FIND_QUESTION_LOADED: 'FIND_QUESTION_LOADED',
    FIND_QUESTION_LOADING_ERROR: 'FIND_QUESTION_LOADING_ERROR',
    POST_ANSWER: 'POST_ANSWER',
    DELETE_ANSWER: 'DELETE_ANSWER',
    VOTE_QUESTION: 'VOTE_QUESTION',
    VOTE_ANSWER: 'VOTE_ANSWER',
    SEARCH_WORDS: 'SEARCH_WORDS',
    LIST_MORE_ANSWERS: 'LIST_MORE_ANSWERS',
    VOTE_CHECK_ANS: "VOTE_CHECK_ANS",
    VOTE_CHECK: "VOTE_CHECK",
}

export default communityType;