export const InstituteListingActionTypes = {
    IL_LIKE_INFO_LOADING: "IL_LIKE_INFO_LOADING",
    IL_LIKE_INFO_LOADED: "IL_LIKE_INFO_LOADED",
    IL_LIKE_INFO_ERROR: "IL_LIKE_INFO_ERROR",


    IL_LIST_LOADING: "IL_LIST_LOADING",
    IL_LIST_LOADED: "IL_LIST_LOADED",
    IL_LIST_ERROR: "IL_LIST_ERROR",

    IL_LIST_REVERSE_LOADING: "IL_LIST_REVERSE_LOADING",
    IL_LIST_REVERSE_LOADED: "IL_LIST_REVERSE_LOADED",
    IL_LIST_REVERSE_ERROR: "IL_LIST_REVERSE_ERROR",

    IL_SINGLE_LIST_LOADING: "IL_SINGLE_LIST_LOADING",
    IL_SINGLE_LIST_LOADED: "IL_SINGLE_LIST_LOADED",
    IL_SINGLE_LIST_ERROR: "IL_SINGLE_LIST_ERROR",

    IL_FEATURED_LIST_LOADING: "IL_FEATURED_LIST_LOADING",
    IL_FEATURED_LIST_LOADED: "IL_FEATURED_LIST_LOADED",
    IL_FEATURED_LIST_ERROR: "IL_FEATURED_LIST_ERROR",

    IL_LIST_SCROLL_LOADING: "IL_LIST_SCROLL_LOADING",
    IL_LIST_SCROLL_LOADED: "IL_LIST_SCROLL_LOADED",
    IL_LIST_SCROLL_ERROR: "IL_LIST_SCROLL_ERROR",

    IL_LIST_SEARCH_LOADING: "IL_LIST_SEARCH_LOADING",
    IL_LIST_SEARCH_LOADED: "IL_LIST_SEARCH_LOADED",
    IL_LIST_SEARCH_ERROR: "IL_LIST_SEARCH_ERROR",

    IL_LIKED_LOADING: "IL_LIKED_LOADING",
    IL_LIKED_LOADED: "IL_LIKED_LOADED",
    IL_LIKED_ERROR: "IL_LIKED_ERROR",

    IL_MY_INS_LOADING: "IL_MY_INS_LOADING",
    IL_MY_INS_LOADED: "IL_MY_INS_LOADED",
    IL_MY_INS_ERROR: "IL_MY_INS_ERROR",


    IL_LIKE_ID: "IL_LIKE_ID",
    IL_LIKE_ID_RESET: "IL_LIKE_ID_RESET",

}