export const INS_ANN_ACTION_TYPES = {
    INS_ANN_LOADING:"INS_ANN_LOADING",
    INS_ANN_LOADED:"INS_ANN_LOADED",
    INS_ANN_LOADING_ERROR:"INS_ANN_LOADING_ERROR",
    INS_ANN_MORE_LOADING:"INS_ANN_MORE_LOADING",
    INS_ANN_MORE_LOADED:"INS_ANN_MORE_LOADED",
    INS_ANN_MORE_LOADING_ERROR:"INS_ANN_MORE_LOADING_ERROR",
    INS_ANN_POPUP_OPEN:"INS_ANN_POPUP_OPEN",
    INS_ANN_POPUP_CLOSE:"INS_ANN_POPUP_CLOSE",
}